### ISSUE TITLE
Create mock search UI

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#1]

**Comment by sebworks** [comment]
The files can be previewed on UXPin: https://preview.uxpin.com/99fdc918db3bdbfc388130aed50d6c64052c8685. ### **The highly subject to change.** 

![0-homepage-0-wide-1440-89823872-1531745227](https://user-images.githubusercontent.com/1696212/42761835-adbc1144-88dc-11e8-98cc-e0864d4d339f.png)
![3-browse-0-wide-1440-90112388-1531746528](https://user-images.githubusercontent.com/1696212/42761836-ae3cc640-88dc-11e8-98cc-16719519dfc5.png)
![4-detail-0-wide-1440-90112389-1531746867](https://user-images.githubusercontent.com/1696212/42761837-aeb6bb9e-88dc-11e8-83f8-73f47580df3f.png)

**Comment by pa-w** [comment]
Excellent work! @sebworks
