### ISSUE TITLE
Add logos for new Sources

### ISSUE THREAD

**Issue by mathemancer** [creativecommons/cccatalog-frontend#1015]
## Problem

We have the following sources come online soon:
- NASA (nasa.gov)
- Biodiversity Library (https://www.biodiversitylibrary.org/)
- SMK (https://www.smk.dk/)
- Science Museum (https://www.sciencemuseumgroup.org.uk/)
-- _Note this may already exist, since we previously integrated, but updated the integration now_
- Europeana (https://www.europeana.eu/en)

We need to make sure that we have the logos set up in the front end for them.

Note also, that currently the Collections page is split into "Museums" and "Other Collections".

NASA and Biodiversity Library should be in the "Other Collections" section, and SMK, Science Museum, and Europeana should be in the Museums section.

**Comment by annatuma** [comment]
@mathemancer I added Europeana to the list, just flagging that for you in case it's premature for some reason.

Also added notes on what part of the page these belong on. (Not sure how that's currently handled, so if it's outside the scope of this, it can be ignored).

**Comment by Tanuj22** [comment]
@mathemancer Can you please tell what would be the `source_name` in the [api](https://api.creativecommons.engineering/v1/sources) for each of them?

**Comment by krysal** [comment]
Where should we get the logos from? Just take it from each link?

**Comment by kgodey** [comment]
Sometimes the sources will have a press kit with logo images, other times they're available on Wikimedia Commons.

**Comment by kgodey** [comment]
The `source_names` are:
`nasa`
`bio_diversity`

**Comment by aldenstpage** [comment]
There's `sciencemuseum` and `europeana`, but I can't say for sure what SMK is (I would imagine it's `smk` but Brent will have to confirm)

**Comment by mathemancer** [comment]
SMK is `statensmuseum`

**Comment by Tanuj22** [comment]
Thanks everyone. Opening a PR soon.

**Comment by mathemancer** [comment]
To summarize:
```
         provider_name          | provider_identifier |             domain_name
--------------------------------+---------------------+--------------------------------------
 Biodiversity Heritage Library  | bio_diversity       | https://www.biodiversitylibrary.org/
 Europeana                      | europeana           | https://www.europeana.eu
 NASA                           | nasa                | https://www.nasa.gov/
 Science Museum – UK            | sciencemuseum       | https://www.sciencemuseum.org.uk
 Statens Museum for Kunst (SMK) | statensmuseum       | https://smk.dk
```

**Comment by ChariniNana** [comment]
@mathemancer should SpaceX be part of this list since I plan to pull it out from Flickr?

**Comment by Tanuj22** [comment]
@ChariniNana  #1021 solves it I guess?

**Comment by ChariniNana** [comment]
Ah yes, it does
