### ISSUE TITLE
Add tooltip in Browse Collection Page

### ISSUE THREAD

**Issue by wajeehamushtaq** [creativecommons/cccatalog-frontend#1017]
## Problem
When hovering over any card in Collection page it must popup about that collection

## Description
Adding customizable & reactive tooltips/popovers/dropdowns with smart positioning. When hovering over any Collection Card.

## Implementation:
By adding Vuejs Plugin:
```
npm install --save v-tooltip
```

**Comment by abhisheknaiidu** [comment]
Thanks, @wajeehamushtaq  for suggesting with the changes, but I think We don't need any custom tooltips or anything else that justifies loading hundreds of KBs in extra `NPM` packages. which will eventually have a high cost for users loading the page.

But anyways, deferring to @akmadian and @kgodey

**Comment by kgodey** [comment]
Feature requests need to go through @annatuma

**Comment by annatuma** [comment]
Thanks for the suggestion @wajeehamushtaq and the proactive triage @abhisheknaiidu 

From a technical perspective, your instincts @abhisheknaiidu are correct here.

From a user perspective, we do need to improve the Collections page, and this is on the roadmap. While we likely won't go the route of tooltips/modals, we do plan to reorganize the content into different groups of sources (currently only "Museum" and "Other"), and are considering building into the design short descriptions of each source.

Thank you again for the suggestion, and if my comment triggers any other ideas you're welcome to share them in a new ticket, or start a thread in the #cc-search channel on Slack.
