### ISSUE TITLE
search returning photos that no longer exist on flickr

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#102]
e.g. https://ccsearch.creativecommons.org/photos/fc83df33-7855-41b5-8026-a62d6270731b

![screenshot_20181006-082459](https://user-images.githubusercontent.com/1696212/46557011-76f26400-c8b6-11e8-8b37-862dca0c4ab2.png)

**Comment by aldenstpage** [comment]
This should only happen in exceptional circumstances now that we filter dead links from search results.
