### ISSUE TITLE
Add SpaceX logo

### ISSUE THREAD

**Issue by mathemancer** [creativecommons/cccatalog-frontend#1021]
## Problem

SpaceX (https://www.spacex.com/)
will soon be added as a source of images for CC Search, so we need to set up a logo in the front end for the collections page.

**Comment by abhisheknaiidu** [comment]
Where should we get the SpaceX logo from?

**Comment by kgodey** [comment]
@abhisheknaiidu https://en.wikipedia.org/wiki/File:SpaceX_logo.svg

**Comment by mathemancer** [comment]
The source identifier will be `spacex`

**Comment by kgodey** [comment]
Done in #1022.
