### ISSUE TITLE
Wrong example link for dog|cat in Search Guide page

### ISSUE THREAD

**Issue by AyanChoudhary** [creativecommons/cccatalog-frontend#1026]
## Description

The example links for **dog+cat** and **dog|cat** in the search-help page both point to the same query which is **dog+cat**

## Reproduction

1. Go to the search help page
2. Navigate to the example links for **dog+cat** and **dog|cat**
3. Check the query string and results
4. See error.

## Expectation

The example for **dog|cat** should point to the search query for **dog|cat**

## Environment

 - Device: Laptop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.106
 - Other info: 

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by annatuma** [comment]
I see this too (on Firefox on a Mac). Thanks for reporting this!
