### ISSUE TITLE
Update Google Analytics Code on Dev and Prod

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1027]
## Description

Our Google Analytics tracking code is incorrectly set up.

Currently, we use the following:

```
<script>
        // Use production Google Analytics ID if ccsearch is in the URL, otherwise use development/staging ID
        // TODO: Refactor this to use environment variables instead of hardcoding IDs here.
        var gaID = document.location.hostname.indexOf('ccsearch') >= 0 ? 'UA-2010376-36' : 'UA-2010376-33';
        /* eslint-disable */
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
        /* eslint-enable */

        ga('create', gaID, 'auto');
        ga('send', 'pageview');
      </script>
```

In production, we have two subdomains that work for CC Search:
search.creativecommons.org
ccsearch.creativecommons.org

For dev, we have one subdomain:
ccsearch-dev.creativecommons.org

Currently, _all_ traffic going to ccsearch.creativecommons.org is being recorded in the GA Dev account, because of how our tracking code is written.

(Note that the current set-up would work if we didn't have ccsearch.creativecommons.org as a subdomain).

## Resolution

To avoid any issues in the future, we should simply use the standard GA tracking code in the `<head>` of the Prod and Dev sites.

**For production**

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-2010376-33"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-2010376-33');
</script>
```

**For development**

```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-2010376-36"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-2010376-36');
</script>
```

**Comment by Tanuj22** [comment]
@annatuma @kgodey  I was looking into this issue. The production environment uses [index-server.html](https://github.com/creativecommons/cccatalog-frontend/blob/develop/index-server.html) to serve the website. From what I could tell `https://ccsearch-dev.creativecommons.org/` is also using the production version. So using the development and production version of GA Tracking code in the development environment( [index.html ](https://github.com/creativecommons/cccatalog-frontend/blob/develop/index.html)) and the production environment ([index-server.html](https://github.com/creativecommons/cccatalog-frontend/blob/develop/index-server.html)) respectively won't solve the issue I think. Am I missing something?

**Comment by annatuma** [comment]
Oh interesting. That might explain why the code is currently set up the way it is.

My first question is whether it is appropriate to use the production version of index-server.html on the development site. Any thoughts on that?

If, instead of changing how we do things with index-server.html, it makes more sense to rewrite the existing code to accurately break down the traffic to the Dev and Prod GA IDs, that's fine by me. We'll re-audit the integration after update.

Happy to hear what the best technical approach is here, given what you've found @Tanuj22

**Comment by Tanuj22** [comment]
@annatuma I am not sure the exact reason for using production server on the development site but I think it may be a good idea to use it as the production version is using `Server Side Rendering` and it may be a good idea to test it now in development environment as most of the contributors use the default `Client Side Rendering` for development. So if there is any problem with `Server Side Rendering` we will know it in `https://ccsearch-dev.creativecommons.org/`. 

Rewriting the existing code may be a better option imo.

**Comment by annatuma** [comment]
Got it! You up for tackling that? At some point we may retire the ccsearch. subdomain, but for now we just need to ensure that:

ccsearch. and search. as subdomains track to the GA production ID UA-2010376-33
ccsearch-dev. as a subdomain tracks to the GA development ID UA-2010376-36

**Comment by Tanuj22** [comment]
Okay!
