### ISSUE TITLE
Add Global Header to CC Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1030]
## Description

The Global Header in the Design Library is now live in Vocabulary: https://cc-vocabulary.netlify.app/?path=/story/patterns-global-header--interactive

This should be added to CC Search.

**Comment by abhisheknaiidu** [comment]
@annatuma seems like Global Header has not been updated!, I'm not able to actually see it properly

**Comment by zackkrida** [comment]
@abhisheknaiidu I fixed Anna's link for you 😸

**Comment by abhisheknaiidu** [comment]
> @abhisheknaiidu I fixed Anna's link for you 😸

Yea I get it, but what exactly we need to do?

**Comment by zackkrida** [comment]
@abhisheknaiidu We would like to implement the global header on cc search! It doesn't have that component yet. So we want to show the 'explore cc' tab at the top of cc search that, when clicked, reveals the full global header with the exact same contents as in vocabulary.

**Comment by abhisheknaiidu** [comment]
@zackkrida yea, but how do we add
 `const globalHeaderInstance = vocabulary.createGlobalHeader()`  to `HeaderSection.vue` file?

**Comment by zackkrida** [comment]
Ah I see, I didn't look at the actual implementation. That's interesting—yes we need to decide if we want to use that or create a vue version of the global header. I need to learn a little more about this and get back to you.

**Comment by kgodey** [comment]
The original plan was to add the global header to Vue Vocabulary and use it from there, but we'd still want to use the content from the WordPress API as part of it. The Vue Vocabulary plan pre-dated the WordPress API, so maybe we'd want to do things differently, I'm not sure.

**Comment by zackkrida** [comment]
I think we'll definitely want to continue to use the github api. the js to add the global header is pretty lightweight so i think it makes sense to use it for consistency's sake
