### ISSUE TITLE
Change location of the mature content filter in search results

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#1033]
## Description
We need to change how we show the filter that shows/hides mature content on the search result page.

Currently, we have a "Search Settings" filter in the left hand side bar, within which users can enable mature content:
<img width="347" alt="Screen Shot 2020-06-26 at 11 07 51 AM" src="https://user-images.githubusercontent.com/3051816/85851048-7cd05d00-b79d-11ea-952c-284fff65cc8d.png">

We want to change the location, design, and interaction of this filter, given its importance. The new location should be in the top right hand corner of the search results page.

[The mockups are available](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A353&viewport=123%2C72%2C0.06821192055940628) (Mockup - S3) as three pages:
1. Default state.
2. Showing the filter box.
3. Filter activated. (Looks same as default state, i.e. no change when filter is selected).

### Default state
<img width="127" alt="Screen Shot 2020-06-25 at 10 44 29" src="https://user-images.githubusercontent.com/895819/85742115-f9e1d080-b6d0-11ea-9d14-c657699deac5.png">

### Showing the filter box
<img width="279" alt="Screen Shot 2020-06-25 at 10 44 34" src="https://user-images.githubusercontent.com/895819/85742127-fd755780-b6d0-11ea-9c80-2f16f383e171.png">

### Filter activated
<img width="143" alt="Screen Shot 2020-06-25 at 10 44 42" src="https://user-images.githubusercontent.com/895819/85742145-0108de80-b6d1-11ea-8a48-ba86303e3ad3.png">

**Comment by Rudresh22** [comment]
Hello, please assign this issue to me. I would like to work on this issue with your guidance.

**Comment by zackkrida** [comment]
Hi @Rudresh22 I actually just completed ~80% of this issue earlier today: https://github.com/creativecommons/cccatalog-frontend/pull/1037

Thanks you for your interest! You may be able to find some other issues [here](https://github.com/creativecommons/cccatalog-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22).
