### ISSUE TITLE
Use Source Logos from Endpoint on Collections UI

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1035]

**Comment by annatuma** [comment]
Blocked by: https://github.com/creativecommons/cccatalog-api/issues/512

**Comment by zackkrida** [comment]
FYI, #512 is no longer blocked 😸 the next step would be for someone to input all the source logos, I imagine.

**Comment by dos077** [comment]
The source logo used to be on the top left corner of the thumbnail when hovered. It was removed during the redesign. Maybe it's time to add it back? Just styling all of them into a circle with black border to match the other two icons?

**Comment by zackkrida** [comment]
That's an interesting idea @dos077. We plan to use the logos in fewer places moving forward, so I'm not sure it makes sense quite yet, but it _would_ be an interesting way of showing the source of each image in the results page.

**Comment by annatuma** [comment]
@zackkrida all logos have been uploaded now, so this is unblocked and can be worked on.
