### ISSUE TITLE
Maintenance: Enforce consistient code style

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1038]
## Problem
Currently the repo enforces _some_ cosmetic linting rules, regarding things like dangling commas, single quotes, and tab size, but there are several inconsistencies. We are also not enforcing formatting for the `template` blocks of single-file vue components, which I have seen be a barrier to many developers. 

## Description
I would recommend we add add some additional automated styling configuration to the repositiory.  Many JavaScript developers now use [`prettier`](https://prettier.io/) to auto-format code on file save or as part of CI. We could develop a prettier configuration for the project that would match our existing enforced styling but also enforce additional rules. This is particularly useful in single file .vue components, where developer opinion on how to format props can vary greatly. 

The project as it stands uses some conventions, but they aren't programmatically enforced.

- [x] I would be interested in implementing this feature.

**Comment by abhisheknaiidu** [comment]
@zackkrida Is this issue allowed for work?

**Comment by zackkrida** [comment]
Sure @abhisheknaiidu! I would suggest adding a [prettier config file](https://prettier.io/docs/en/configuration.html#docsNav) in the root of the project or a `prettier` key in the `package.json`.

Thank you!

**Comment by abhisheknaiidu** [comment]
@zackkrida I made those changes
