### ISSUE TITLE
Styling Error and Missing Link on License Explanation Modals

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1047]
## Description

There are issues with the styling and content of the License Explanation Modals.
 
## Reproduction
Clicking on any of the License Explanation Modals in the License filter section of the filter side bar, you'll see that the explanation text per license "bullet" is not correctly aligned, and the link to the license deed is missing.

In production:
<img width="382" alt="Screen Shot 2020-07-09 at 11 52 41 AM" src="https://user-images.githubusercontent.com/3051816/87037171-579b1000-c1db-11ea-8ad2-93c12d2de07f.png">

<img width="352" alt="Screen Shot 2020-07-09 at 11 55 24 AM" src="https://user-images.githubusercontent.com/3051816/87037191-5d90f100-c1db-11ea-871f-5cbf635bdc4f.png">

## Expectation

The expectation is that the modal design should match what we had outlined in Figma, and there should be a link to the License Deed on each modal.

<img width="437" alt="Screen Shot 2020-07-09 at 11 55 44 AM" src="https://user-images.githubusercontent.com/3051816/87037243-726d8480-c1db-11ea-8069-de0671996bda.png">

The links are detailed in the [content document for this feature](https://docs.google.com/document/d/12mfwy1fvWUYJhs1gKHyAoC1GVoqO0iEj6NP4uBA-SsU/edit) but are likely also stored elsewhere, since we reference these deeds across numerous parts of the site.

**Comment by annatuma** [comment]
FYI @panchovm there's a ticket for this now.

**Comment by ritesh-pandey** [comment]
I had a look at it.

- The markup needs to be changed. We should use `ul li` instead of `div span`
- Icons inside the modal can be rendered using `list-style-type` CSS property. We can preserve alignment in this way

**Comment by zackkrida** [comment]
@ritesh-pandey switching the markup sounds great—I would recommend we use `flexbox` for the alignment and keep the icons as `<i />` tags inside the `li`s. There are some browser inconsistencies around `list-style-type` I would prefer to avoid.

**Comment by ritesh-pandey** [comment]
Agreed.

Not all browsers have implemented it. https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style 

Let us go with `flexbox`. How do I find all the pre-defined classes for project e.g. `font-size`, `margin-left-small` etc.?

Here is a WIP.
![image](https://user-images.githubusercontent.com/1433681/87335525-16e62280-c55e-11ea-92f7-32d590d782fb.png)

**Comment by zackkrida** [comment]
The project uses the following design system (wip): https://cc-vocabulary.netlify.app/?path=/story/vocabulary-introduction--page

which is built on top of bulma:
https://bulma.io/
https://github.com/jgthms/bulma/blob/master/css/bulma.css

I'll be happy to review code & guide you if you miss any existing styles and/or need to write a few lines of custom css. Thank you!
