### ISSUE TITLE
Changes to showing provider and source on single result page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1049]
We want to implement some updates to the Information tab on the Single Result Page in CC Search.

New design of Information tab in [Figma](https://www.figma.com/proto/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1224%3A27&scaling=min-zoom).

Changes:
- Show file type
- Show provider (not linked)
- Show source (active link to image landing page)
- No more logos being shown

**Comment by annatuma** [comment]
Was blocked by API work, completed here: https://github.com/creativecommons/cccatalog-api/issues/559 (Just need to double check this was released to production, before starting work on this ticket).

**Comment by zackkrida** [comment]
This should be a part of the next api release, but has not been pushed to production yet: https://github.com/creativecommons/cccatalog-api/releases

**Comment by zackkrida** [comment]
No longer blocked :)
