### ISSUE TITLE
Change Current Collections Search Flow

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1051]
We currently have two search flows for users on CC Search:

1) Search term entered on homepage, entire Catalog can be searched, filters can be applied, including filters for the Source.

2) User goes to Collections page, clicks on a Collection, and is taken to a URL dedicated to that Collection, that looks and feels like our Results page, but isn't.
Example: https://search.creativecommons.org/collections/clevelandmuseum
After search: https://search.creativecommons.org/collections/clevelandmuseum?license=&license_type=&categories=&extension=&aspect_ratio=&size=&source=&q=stuff&searchBy=&mature=

We are about to make other changes to the Collections page - we plan to retire it and replace it with a page that contains a table of all Sources. We'd like to change the second flow described above at the same time to this:

User goes to new Sources page (or current Collections page, if this gets worked on before the Sources page is built), clicks on a Source, and is taken to the Search Results page with all results for that source loaded, and the source is applied as a filter (visible with a filter pill below the search box, and in the left hand side bar).

We need to make sure when doing this that the /collections/collection-name URLs all redirect to the new page we're taking users to.

**Comment by annatuma** [comment]
FYI @zackkrida ticket is now created for what we discussed earlier. Tentatively figuring this can go in the next sprint (i.e. last week of July).

**Comment by zackkrida** [comment]
Definitely! I will look into how we currently handle redirects for CC Search (if we do at all), because there's some interesting behavior to figure out:

- Currently the 'collection' results pages allow for viewing without a search query: https://search.creativecommons.org/collections/clevelandmuseum
- That behavior is *not allowed* on the main results page (this link will redirect to the home page): https://search.creativecommons.org/search?source=clevelandmuseum, it requires a search term: https://search.creativecommons.org/search?source=clevelandmuseum&q=dogs

So we may ultimately have to redirect the `/collections/clevelandmuseum` just to the homepage like you thought originally

**Comment by zackkrida** [comment]
@annatuma given the above context, could you confirm, do you think redirecting these to the homepage will be okay, or should i try to make urls like `https://search.creativecommons.org/search?source=animaldiversity` work without a search query?

**Comment by annatuma** [comment]
Perhaps we should redirect them to /collections for the time being, which will subsequently be redirected to the new /sources page when that is built (design not yet finalized). So, someone coming in to https://search.creativecommons.org/collections/met will just end up at https://search.creativecommons.org/collections, where they'll be able to see the Met listed as a collection (and in the future, a source).

I do expect the number of inbound links to specific collections is very, very low, but at least this points the user in the right direction if they're coming in through one.

What do you think?

**Comment by zackkrida** [comment]
@annatuma that sounds good to me, and i imagine we'd want to _remove_ these links entirely:

<img width="632" alt="Screen Shot 2020-07-27 at 1 18 50 PM" src="https://user-images.githubusercontent.com/6351754/88571510-c4037500-d00b-11ea-909d-a1d9177cf2f9.png">

**Comment by annatuma** [comment]
Sorry - missed that crucial step in the logic here - if we don't load results in CC Search with no search term, then both the current Collections page and future Sources page are less useful. They just become information lists, with no actionable ability if a user views them.

Is this functionality we need at the API level, in terms of filtering the Catalog without a query?

**Comment by zackkrida** [comment]
that's a great question—i know the front-end has a lot of protections and redirects in place to prevent executing a search without a query but i don't know at the api level.

**Comment by zackkrida** [comment]
cool, quick test @annatuma, the api _does_ allow you not to specify a url. So I can do everything we need, just need to wrestle the front-end into shape 👍 


```shell
❯ curl http://api.creativecommons.engineering/v1/images\?source=clevelandmuseum | jq '.results[].url'

"https://openaccess-cdn.clevelandart.org/2008.293.b/2008.293.b_web.jpg"
"https://openaccess-cdn.clevelandart.org/1961.205/1961.205_web.jpg"
"https://openaccess-cdn.clevelandart.org/1963.673/1963.673_web.jpg"
"https://openaccess-cdn.clevelandart.org/1931.449/1931.449_web.jpg"
"https://openaccess-cdn.clevelandart.org/1967.29/1967.29_web.jpg"
"https://openaccess-cdn.clevelandart.org/1988.148/1988.148_web.jpg"
"https://openaccess-cdn.clevelandart.org/1923.120.7/1923.120.7_web.jpg"
"https://openaccess-cdn.clevelandart.org/1928.631/1928.631_web.jpg"
"https://openaccess-cdn.clevelandart.org/1940.37/1940.37_web.jpg"
"https://openaccess-cdn.clevelandart.org/1941.653/1941.653_web.jpg"
"https://openaccess-cdn.clevelandart.org/1947.455/1947.455_web.jpg"
"https://openaccess-cdn.clevelandart.org/1955.672/1955.672_web.jpg"
"https://openaccess-cdn.clevelandart.org/1964.457/1964.457_web.jpg"
"https://openaccess-cdn.clevelandart.org/1964.502/1964.502_web.jpg"
"https://openaccess-cdn.clevelandart.org/1968.222/1968.222_web.jpg"
"https://openaccess-cdn.clevelandart.org/1978.1054/1978.1054_web.jpg"
"https://openaccess-cdn.clevelandart.org/1915.1/1915.1_web.jpg"
"https://openaccess-cdn.clevelandart.org/1916.311/1916.311_web.jpg"
"https://openaccess-cdn.clevelandart.org/1916.648/1916.648_web.jpg"
"https://openaccess-cdn.clevelandart.org/1918.560.1.f/1918.560.1.f_web.jpg"
```

**Comment by annatuma** [comment]
OK super, I'm glad this isn't contingent on changes in any other code bases.

Given this, can we go with the original redirect approach then?

**Comment by zackkrida** [comment]
Yes, with the caveat that we need to think about what to show on /search when there is no query or collection filter applied.

We could either show the default results from the api, or some onboardng messaging.

I think the original idea of forcing a query is that /search shouldn't be used as an 'entrypoint' to cc search, but I think it's kind of inevitable that it is if we do the original approach
