### ISSUE TITLE
"Copy to wordpress" button or similar

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#106]
We should discuss this one, but I thought it was interesting in terms of user feedback and could be an enhancement down the line.

> "Copy to wordpress" button or something similiar, so users can paste the attribution to the wordpress (or similiar) WYSIWYG editors with intact hyperlinks

Is this significantly different from html?

**Comment by janeatcc** [comment]
would love to see your solution! currently not being worked on by anyone, so go ahead. we would not deploy before discussing and reviewing though, as we haven't decided 100 percent if we would add this.

**Comment by dhruvkb** [comment]
I've submitted the PR although it is still in a draft stage. I am yet to remove the `clipboard` pacakage from the `package.json` file after which the PR will no longer be WIP.

**Comment by brenoferreira** [comment]
Doesn't the "Copy Rich Text" attribution button solve this @janeatcc?

**Comment by janeatcc** [comment]
Yes.
