### ISSUE TITLE
Clarify 'Use' and 'License' filter behavior

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1067]
The current interaction between these two filters confuses me, and I could use some clarification to guide #1065. @kgodey you may be the best person to examine this in anna's absence. 

<img width="349" alt="Screen Shot 2020-07-20 at 5 15 18 PM" src="https://user-images.githubusercontent.com/6351754/87987582-dda53980-caac-11ea-9a54-3d3b3c3006f9.png">

## Current behavior

- Selecting a 'use' filter (Use commercially / Modify or adapt) _disables all license filters_
- Selecting a 'license' filter disables both use filters

## Desired behavior

Per #845 the desired behavior is:

- If “Use commercially” is checked, NC licenses should not be available for selection from License filter.
- If “Modify or adapt” is checked, ND licenses should not be available for selection from License filter.

## Question

- What should happen if various license checkboxes are clicked and then the user then clicks on a 'use' filter? Should we _disable_ the use filter, or disable and un-check the active but no-longer-applicable license checkboxes?
- Confirm: the 'use' filters should indicate that a _sub-set of the licenses is relevant_. Should the use filter 'talk' to the api (as it currently does), or simply indicate which licenses can be chosen?

**Comment by kgodey** [comment]
> What should happen if various license checkboxes are clicked and then the user then clicks on a 'use' filter? Should we disable the use filter, or disable and un-check the active but no-longer-applicable license checkboxes?

If various license checkboxes are clicked, the "use" filters should be disabled conditionally. e.g. if any NC license checkbox is clicked, then "Use commercially" should be disabled. If any ND license checkbox is clicked, then "Modify or adapt" should be disabled. This will ensure there are no contradictory filters.

> Confirm: the 'use' filters should indicate that a sub-set of the licenses is relevant. Should the use filter 'talk' to the api (as it currently does), or simply indicate which licenses can be chosen?

Yes, both should talk to the API. They are searching the same thing but are aimed at different audiences, the "use" filter is aimed at folks not familiar with the specifics of our licenses, the license filter is aimed at folks who know exactly what license they're looking for.

**Comment by zackkrida** [comment]
Got it, thank you! Disabling the use filters _conditionally_ was the main piece i needed to unblock. Closing.
