### ISSUE TITLE
Switch from `axios` to `redaxios`

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1075]
Help decrease the size of our js bundle by switching to https://github.com/developit/redaxios, same api as axios at 1/5 the size.

Just need to confirm we're polyfilling fetch for IE11 support (we likely already are).

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by brisibe** [comment]
would love to work on this.

**Comment by brisibe** [comment]
I see issue had already being worked on by someone else. :slightly_smiling_face:

**Comment by zackkrida** [comment]
Decided not to implement, savings was minimal and there were some compat issues
