### ISSUE TITLE
Add 'all contributors' block to README

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1078]
This is a really nice way to showcase all of our contributors: https://github.com/all-contributors/all-contributors

**Comment by Aakash2408** [comment]
Can i work on this?

**Comment by Aakash2408** [comment]
@all-contributors please add @Aakash2408  for adding all contributors

**Comment by Aakash2408** [comment]
@zackkrida  the bot tells to use the above command to add the contributor to the readme but it doesn't work the ways they have shown on the website
![Screenshot from 2020-08-15 20-49-01](https://user-images.githubusercontent.com/47134609/90315399-e3216280-df38-11ea-8b39-5fc26b1bf5e8.png)

**Comment by Aakash2408** [comment]
The bot will only work when someone from authors can install the bot for this original repository and then these pull requests will be created by the Bot . This can't be done on the forked repositories.

**Comment by ooyeraju** [comment]
@zackkrida  is this issue still open? If yes, I can take it.

**Comment by zackkrida** [comment]
Hi @ooyeraju, we need to install a GitHub bot to make this work. I've updated the labels to indicate that this is `staff only` for now. Thanks!

**Comment by KarenEfereyan** [comment]
Is this still open?

**Comment by zackkrida** [comment]
> I've updated the labels to indicate that this is staff only for now. Thanks!

No @KarenEfereyan, I can let you know when it is though! 😄

**Comment by zackkrida** [comment]
I've decided to close this. The new Github UI for repositories has a nice contributors block that I think is good enough, and we've also standarzided thanking contributors in our [release notes](https://github.com/creativecommons/cccatalog-frontend/releases)

## New GitHub UI

<img width="342" alt="Screen Shot 2020-09-28 at 7 32 13 AM" src="https://user-images.githubusercontent.com/6351754/94466449-276d6880-015d-11eb-9534-5316cc15eefd.png">

If we want to further thank contributors, I think we could do a 'contributors' page on our open source site, that has a databag pulling all contributors from our repos and sorting them by # of commits, total LoC, or other metric.
