### ISSUE TITLE
Collections cards should be buttons not hyperlink

### ISSUE THREAD

**Issue by rochisha0** [creativecommons/cccatalog-frontend#1081]
## Problem

Hovering on collections' titles creates an underline under their name. This makes it look less aesthetic. Moreover, The whole card isn't hyperlinked whereas only images and titles are.

## Possible fixes
The whole card is hyperlinked

## Implementation

- [x] I would be interested in implementing this feature.

![image](https://user-images.githubusercontent.com/45593458/88385073-50732500-cdcb-11ea-97db-d50428df2012.png)

**Comment by AyanChoudhary** [comment]
@rochisha0 we are in the process of redesigning this page, so we probably won't need to fix this. Still, you can wait for confirmation from @zackkrida

**Comment by zackkrida** [comment]
Agreed, I'd like to see this change _if_ we keep the cards but they are going away, so I'm going to close this. If we end up keeping them for any reason I will create an issue on vocabulary and add you to it @rochisha0 . Thank you!
