### ISSUE TITLE
Return to masonry-style layout

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1084]
Even with the current SSR implementation, images are loaded into the markup client-side. You can confirm this by viewing source (paste the following text into your browser's url bar) and observing there is no image markup:

`view-source:https://search.creativecommons.org/search?q=dogs`

The current layout preserves aspect ratio, which is nice, but can lead to large gaps of whitespace in the image results: https://ccsearch-dev.creativecommons.org/search?q=kittens

We should explore switching back to a js-based layout, but a lighter version that also allows us to implement lazy loading so get the initial page render down.

**Comment by dos077** [comment]
I did the image grid redesign/code move from masonry to the flex grid (at least supposedly) code last time. The design idea was to make it like an older version of google image or the current [bing one](https://www.bing.com/images/search?q=kittens&form=HDRSC2&first=1&scenario=ImageBasicHover&cw=1117&ch=859)

Looks like some had change the grid css and added a .masonry-layout without understand how the current system works. I know there are always design changes around here, but designer or whoever is writing the stylesheet should have check what they are changing.

As far as I know image grid with non uniform aspect ratio images can have uniform columns or the rows, but not both. The current image grid cell has flex grow ratio to grow into uniform rows, if the grid class is not getting in the way. What is the current design goal? Uniform height? Uniform width? Or just want to crop everything into square, like Apple or Instagram? Without a feasible design to guide code, it will just be a mess down the road.

**Comment by zackkrida** [comment]
@dos077 I hugely appreciate this historical context! The only goals of this work are:

1. Preserve image aspect ratio
2. Uniform white space between rows

So you are saying you had a working masonry, flexbox-based layout merged here: https://github.com/creativecommons/cccatalog-frontend/pull/538 and it has been broken since? 


That `.masonry-layout` class is in the code, but is not actually being used in the site.

I am curious how your flexbox solution broke, I would be happy to go back to it.

**Comment by zackkrida** [comment]
@dos077 looks like it was broken by how img width/height was being detected (it wasn't!). Care to check out this PR? #1085 

<img width="241" alt="Screen Shot 2020-07-25 at 3 22 44 PM" src="https://user-images.githubusercontent.com/6351754/88464870-2a618980-ce8c-11ea-99ce-b4e84427c1f3.png">

**Comment by dos077** [comment]
Okay, I've found the issue. You are right, they have yet to revert back to masonry grid. Seems like the back-end is not sending height and width or the data processor is discarding those metas, AND the image is loading after the cell component is mounted. I have a fix and will submit a pull request later, currently looking at the filter list modal/aside component. That thing is a bug fests...

**Comment by zackkrida** [comment]
@dos077 i think the simplest is just to set the width/height on actual load of the image: https://github.com/creativecommons/cccatalog-frontend/pull/1085


The filters list isn't the cleanest implementation api design-wise, but we're not currently seeing bugs on https://ccsearch-dev.creativecommons.org/. Could you describe what you mean more?

**Comment by dos077** [comment]
Yeah that fix works. I tested it with changing img src and it updates the dimension as well. Should works with place holders, or infinite scrolling. In that case server side meta is almost unnecessary. This should be merge ASAP.
