### ISSUE TITLE
Remove "License CC" from CC0 and PDM Modals on Filters

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1100]
## Problem

We are currently using license language for CC0 and PDM, which are actually legal tools and not licenses, on the informational modals in the filter side bar.

## Description

We need to remove "License CC" from the top line of the modal, leaving just the name of the tool. We also need to change the link to say "tool" and not "license". Screenshots indicate changes:

<img width="320" alt="pdm in license filters" src="https://user-images.githubusercontent.com/3051816/89029128-40a09700-d31d-11ea-87ed-188093af5a3f.png">
<img width="329" alt="cc0 in license filters" src="https://user-images.githubusercontent.com/3051816/89029130-41392d80-d31d-11ea-82fd-2ab1314bf2c1.png">

**Comment by rochisha0** [comment]
Hey, @annatuma ! I will like to work on this issue.

**Comment by zackkrida** [comment]
thank you @rochisha0 !

**Comment by zackkrida** [comment]
@rochisha0 this issue: https://github.com/creativecommons/cccatalog-frontend/issues/1099
uses some of the same code, so it would be great to fix them at the same time. Thank you 😸

**Comment by rochisha0** [comment]
Hey, @zackkrida! I cannot find Reuse tab in CCSerach to fix #1099.

**Comment by AyanChoudhary** [comment]
@rochisha0 we have integrated the i18n code into the codebase recently so it might throw you off. The relevant code sections which you are looking for are probably these:

1. https://github.com/creativecommons/cccatalog-frontend/blob/4a4e8c092e6b0dd9813a65d553fbbb8256007c68/src/components/ImageDetails/PhotoDetails.vue#L68
2. https://github.com/creativecommons/cccatalog-frontend/blob/4a4e8c092e6b0dd9813a65d553fbbb8256007c68/src/components/ImageDetails/PhotoDetails.vue#L103
3. https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/ImageDetails/ImageInfo.vue

**Comment by rochisha0** [comment]
Thank you so much, @AyanChoudhary !
