### ISSUE TITLE
Add subtitle to homepage below "Search for content to reuse"

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1125]
Add a subtitle below "Search for content to reuse" giving some context on what can be search, # of images, etc. Will defer to @annatuma for copy suggestions.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by annatuma** [comment]
I suggest "Browse over 500 million images, available for reuse"

And then we can expand that to include other content types as they become available :)

**Comment by zackkrida** [comment]
Fixed by #1129
