### ISSUE TITLE
Research for interactive 3D models on the frontend

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#1126]
## To Do

- [ ] Compare various 3D rendering JavaScript libraries 
- [ ] Review possible catalog api changes and make appropriate tickets
- [ ] Explore requirements to make 3d its own content type in the front-end (with its own tab)

**Comment by zackkrida** [comment]
Closed in favor of https://github.com/creativecommons/cccatalog-frontend/issues/1157
