### ISSUE TITLE
Implement Lighthouse CI

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1130]
We will implement [Lighthouse CI](https://github.com/GoogleChrome/lighthouse-ci) to get some CI on front-end performance and a11y.

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by neeraj-2** [comment]
Can ,i work on this?But ,please guide me what exactly we need to do?

**Comment by zackkrida** [comment]
Hi @neeraj-2, this actually needs to be done by CC staff, since there's some edits to the repo configuration needed.
