### ISSUE TITLE
Broken Links for tools

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1132]
Our non-license tools `cc0` and `pdm` have incorrect links in the license info popups.

<img width="1274" alt="Screen Shot 2020-08-13 at 11 38 39 AM" src="https://user-images.githubusercontent.com/6351754/90155842-c844c780-dd59-11ea-96bd-3e0eb3ecf2ce.png">

The links should be:

- pdm creativecommons.org/publicdomain/mark/1.0
- cc0 creativecommons.org/publicdomain/zero/1.0

**Comment by kgodey** [comment]
Please verify URLs with @TimidRobot

**Comment by annatuma** [comment]
I believe linking to the summary pages (equivalent type of page as license deeds) is in fact the correct approach, and what we're currently doing:
https://creativecommons.org/publicdomain/mark/1.0/
https://creativecommons.org/publicdomain/zero/1.0/

I'll surface this with @sarahpearson too.

**Comment by sarahpearson** [comment]
Not sure of the full context here, but those links you included are correct, @annatuma.

**Comment by kgodey** [comment]
Should we close this?

**Comment by zackkrida** [comment]
@kgodey No, there are still incorrect links, I just updated the ticket to indicate where.
