### ISSUE TITLE
Change to two Filter names

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1133]
We want to change two Filter names in the filter side bar.

1) "Licenses" should become "License or Public Domain", opting for singular and more correctly including the public domain tools (CC0 and PDM), which are not technically licenses.

2) "Sources" should become "Source", in keeping with singular across all other filter names.

<img width="324" alt="filter heading changes" src="https://user-images.githubusercontent.com/3051816/89929980-869d0b00-dbf9-11ea-9ee8-3e043b7b4042.png">

**Comment by rochisha0** [comment]
I'd like to work on this issue @annatuma !

**Comment by zackkrida** [comment]
Go for it @rochisha0 you can work on issues without asking anytime 😄
