### ISSUE TITLE
Plain text attribution typos for tools

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1155]
## Description

Anything marked with CC0 or PDM has two typos in the "Plain text" attribution tab:

1. Says "licensed" instead of "marked"
2. Says "to the terms" instead of "to view the terms"

You may view an adorable example here: https://search.creativecommons.org/photos/44874d17-45db-48d2-ab5d-fff03fb96a30

<img width="479" alt="Screen Shot 2020-08-17 at 4 20 42 PM" src="https://user-images.githubusercontent.com/6351754/90440848-e5ed9600-e0a5-11ea-8776-c05474c279dc.png">

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by avats-dev** [comment]
Can I work on this?

**Comment by zackkrida** [comment]
Sure @avats-dev

**Comment by avats-dev** [comment]
I think I have to edit this [here](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/ImageDetails/CopyLicense.vue).
Can you please explain what this line means, specifically what `isTool ? a : b` means?
https://github.com/creativecommons/cccatalog-frontend/blob/9735f560364519c4e8a7b35bcad1ae2937dcd7bb/src/components/ImageDetails/CopyLicense.vue#L118

**Comment by avats-dev** [comment]
Opened the PR #1159 , @zackkrida feel free to review and suggest any edits.
