### ISSUE TITLE
Change placeholder text on search bar

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1160]
## Problem

Our search bar currently has placeholder text that says "Search all images". This is potentially confusing if a user tabs to a different content type, like Audio or Video, where we offer meta search now.

## Description

We should:
- Update the placeholder text in the Search Bar on the homepage to say "Search all content"
- Dynamically update the placeholder text in the Search Bar depending on what content type tab the user is on in the Results page, to say "Search all content_type". When a user is in the Image tab, it'll say "Search all images", in the Audio tab it'll say "Search all audio", etc.

**Comment by annatuma** [comment]
@zackkrida and @panchovm (or anyone else), what's your preference here regarding the placeholder text? Should we have none, or edit the copy?

**Comment by rochisha0** [comment]
I'll like to work on this issue.

**Comment by zackkrida** [comment]
@annatuma We use the placeholder "I would like to see" on the homepage—maybe we unify and use it everywhere? 

Otherwise, I think we'd want it to be dynamic: "Search all images", "Search all audio" etc.

**Comment by annatuma** [comment]
Good point in that it differs currently. "I would like to see" doesn't really work for audio, so we'll need to change it on the homepage.

Perhaps "Search all content" on the homepage, and then dynamic for content type on the results pages?

**Comment by zackkrida** [comment]
@annatuma I like that!

**Comment by annatuma** [comment]
Awesome. In that case, @rochisha0 you're welcome to dive into this issue. I'll update the description too.

**Comment by panchovm** [comment]
I like that too. Agree
