### ISSUE TITLE
Add Vimeo to Video Meta Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1162]
###  Description
Vimeo supports searching by CC license. We should include them in Meta Search.

They don't allow filtering by All CC licenses, or multiple license at once - only by individual licenses. As such, we need to settle on what the default CC license filter we want to apply to our search queries is.

I suggest we go with CC BY, which means that if both **Use** filters are checked, the results are still correct.

Example query:
https://vimeo.com/search?license=by&q=cats

License selection filter:
<img width="215" alt="vimeo license selection filter" src="https://user-images.githubusercontent.com/3051816/90534825-b6a05d00-e169-11ea-841a-5617299741e6.png">

**Comment by zackkrida** [comment]
@annatuma I agree with your thoughts on CC BY!

**Comment by P1YU5H-50N1** [comment]
Can I help?

**Comment by zackkrida** [comment]
Sure @P1YU5H-50N1, to get you started in the right direction, you'd want to add vimeo to the JavaScript object here: https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/utils/getLegacySourceUrl.js

**Comment by P1YU5H-50N1** [comment]
Thanks for the guidance @zackkrida ! I am on it.
