### ISSUE TITLE
[Meta] Add Issue Template for Meta search suggestions

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1168]
Create a new issue template for suggestions of meta search providers.

- Name
- URL
- Type (video|audio|image)
- Supports use filtering? (yes|no|don't know)|

## Implementation

- [x] I would be interested in implementing this feature.

**Comment by kgodey** [comment]
All source suggestions should happen in https://github.com/creativecommons/cccatalog
