### ISSUE TITLE
Extra spaces in  CC Search Guide

### ISSUE THREAD

**Issue by rochisha0** [creativecommons/cccatalog-frontend#1169]
## Description

There is an extra space after operator definition and it's example.

## Reproduction

1. Go to https://ccsearch.creativecommons.org/search-help
2. Notice the extra space between the example and the definition of operator

## Expectation
This extra space looks odd and is confusing, and it becomes less evident as to which operator the example belongs.

## Screenshots

![image](https://user-images.githubusercontent.com/45593458/90689956-7edf0580-e28e-11ea-9c2e-39dd6bb3cb82.png)

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Go ahead and work on this—thanks @rochisha0!
