### ISSUE TITLE
Create Meta Search explainer page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1180]
We'd like to create a new page on CC Search called Meta Search. It should be a sub-page of the About navigation item.

[Here is the text content for the page](https://docs.google.com/document/d/1qK3Gczmb9NsS6dgXDbA1G3KzJ_pcFE1AtrOZRVv6bPo/edit).

We also reference three GIFs in the article, they can be accessed via:

Meta Search - Images - Cars example: https://drive.google.com/file/d/1zFHJt9stxHWwLBWeKBPbm3rL22hsA375/view?usp=sharing

Meta Search - Audio - Drums example: https://drive.google.com/file/d/1ZCvxw2Z7E6VCnwdzwCgSgSlc7NG5Bsxp/view?usp=sharing

CC Search Meta Search Portal - Example: https://drive.google.com/file/d/1_tb3L6RuTovCSPnrb8v1zW5nchg4NN09/view?usp=sharing

**Comment by rochisha0** [comment]
Can I take this issue?

**Comment by kgodey** [comment]
go ahead!
