### ISSUE TITLE
Fix Smithsonian link on Sources page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1187]
We need to update a link on the Sources page. The link to the Smithsonian Institution should direct to: `https://www.si.edu/`

**Comment by zackkrida** [comment]
@annatuma Noted regarding the Smithsonian link—could you confirm that the new source button is incorrect? It's going to the right place for me: 

<img width="1448" alt="Screen Shot 2020-08-26 at 3 42 20 AM" src="https://user-images.githubusercontent.com/6351754/91311288-a0d4fe00-e74e-11ea-960a-afc802044641.png">

**Comment by annatuma** [comment]
I don't know what I saw that looked wrong earlier today, but it is indeed correct. Sorry about that!

**Comment by megha070** [comment]
@zackkrida I would like to take this up.

**Comment by AlexARNcode** [comment]
Hi, is this issue solved then?

**Comment by zackkrida** [comment]
@AlexARNcode multiple people are encouraged to work in issues and make prs 😀 you can try if you like

**Comment by AlexARNcode** [comment]
But I mean : It looks like this specific problem isn't really a problem, i.e this

> @annatuma Noted regarding the Smithsonian link—could you confirm that the new source button is incorrect? It's going to the right place for me:
> 
> <img alt="Screen Shot 2020-08-26 at 3 42 20 AM" width="1448" src="https://user-images.githubusercontent.com/6351754/91311288-a0d4fe00-e74e-11ea-960a-afc802044641.png">
?

**Comment by zackkrida** [comment]
> The link to the Smithsonian Institution should direct to: https://www.si.edu/

this is the part that still needs to be done @AlexARNcode
