### ISSUE TITLE
Update donate icon in footer button

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1190]
The icon in the footer donate button needs to be updated to use the `cc-letterheart-filled` icon.

Original Issue: creativecommons/vocabulary#589

**Comment by StTronn** [comment]
Hey @zackkrida Is it up for grabs? I have looked at the original issue and the FooterSection seems like a quick fix.

**Comment by zackkrida** [comment]
Sure @StTronn! One tip—you'll need to update vocabulary with `npm install @creativecommons/vocabulary@latest` to have access to the `cc-letterheart-filled` icon class.

**Comment by StTronn** [comment]
@zackkrida  Thanks for the quick tip saved me a lot of time. I have made pull req #1192 added screenshot here as well. Sorry If I had messed your commit guidelines, would create a new pull req quickly with a single commit message.

![Screenshot from 2020-08-27 01-24-29](https://user-images.githubusercontent.com/42781659/91352291-43e94e80-e807-11ea-88dc-ff08574f3222.png)
