### ISSUE TITLE
Add Donation Banner to top of CC Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1199]
We'd like to add a Donation banner to the top of CC Search, to help drive community support for the project.

[Design](https://www.figma.com/file/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1606%3A0).

The "Yes..." button should link to this form: https://www.classy.org/give/297881/#!/donation/checkout

The "Not Today" button and the "X" should close the banner.

We should show the banner once per session, meaning that if a user chooses to close the banner, we should remember that for the duration of their session. This banner should be visible on every page on CC Search, unless closed.

For smaller screen sizes, let's go with logical break points, doing line breaks for text on the left, and stacking the buttons on the right.

**Comment by annatuma** [comment]
@zackkrida this is ready to go. I've also marked it as "help wanted" in case someone from the community wants to help out.

**Comment by neeraj-2** [comment]
can i work on this?

> @zackkrida this is ready to go. I've also marked it as "help wanted" in case someone from the community wants to help out.
> 
> p.s. if something could be improved with the design or language, feel free to flag that.

**Comment by zackkrida** [comment]
and @annatuma I like the design a lot. Not too obtrusive but still prominient.

**Comment by KarenEfereyan** [comment]
This is an amazing community. I love the way issues are raised. Makes me want to contribute

**Comment by KarenEfereyan** [comment]
The design looks splendid

**Comment by tushar912** [comment]
is this issue assigned?....can i work on this

**Comment by neeraj-2** [comment]
> is this issue assigned?....can i work on this

Well,i am actually working on it already .So can u plz.work on some other issue.

**Comment by neeraj-2** [comment]
@zackkrida  and @annatuma i added donation banner,looks as shown.A little backend part is remaining ,i am working on **backend** part right now...but wrt to interface i want to know from u that the **banner** looks good or require some changes.

 



![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/56186425/92997396-ac873980-f530-11ea-8021-8b228b288738.gif)

**Comment by rochisha0** [comment]
Nice work @neeraj-2 ! You can use `margin-right-large` in the `p` tag to create spacing between `text` and `buttons`. Also try using `margin-top-normal` for making the text centered in the banner.

**Comment by neeraj-2** [comment]
> Nice work @neeraj-2 ! You can use `margin-right-large` in the `p` tag to create spacing between `text` and `buttons`. Also try using `margin-top-normal` for making the text centered in the banner.

👍Yeah sure @rochisha0 ,I will make changes and improve the code.
