### ISSUE TITLE
Create "Support Us" page

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#1201]
We'd like to create a new page on CC Search called "Support Us".

It should be linked from the top nav, on the far right.

[Page mockup](https://www.figma.com/file/y09nZth7u1a75xO9sLtjcw/Mockup---S5-(Source-and-provider)?node-id=1585%3A4340)

[Text content including link information](https://docs.google.com/document/d/1pOllcRm9PkI-ZSztdLXclXVVa5wRTVPl9XVS5fpG6UA/edit?usp=sharing).

Please note that the design is _not_ pixel perfect, but displays how the content should be laid out and spaced, and where donation buttons should be placed.

**Comment by rochisha0** [comment]
I'll like to work on this!

**Comment by KarenEfereyan** [comment]
This looks interesting  @rochisha0 well done. Are you through?
