### ISSUE TITLE
Move meta search from about to resources tab

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1203]
Move the `meta search` menu item from the `about` to the `resources` header dropdown.

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by rochisha0** [comment]
If it's available, I'll like to work on this

**Comment by neeraj-2** [comment]
Me too,but explain a little bit more about the expected behavior.

**Comment by ritiktaneja** [comment]
I would like to work on this issue.
