### ISSUE TITLE
Fix text under Search bar on homepage

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1205]
Under our Search bar, we currently say:
All our content is under Creative Commons licenses. Learn more about CC licenses.

We'd like to update this text to say:
All our content is under Creative Commons licenses or in the public domain. Learn more about CC licenses and tools.

The link should remain the same.

**Comment by annatuma** [comment]
@zackkrida I remember discussing this, but didn't see a ticket for it yet. If this is a duplicate please just close it.

**Comment by tushar912** [comment]
Can I work on this?

**Comment by kgodey** [comment]
go ahead @tushar912, no need to ask permission for issues marked "help wanted"

**Comment by KarenEfereyan** [comment]
@annatuma is this issue still available? I'd like to take it up

**Comment by annatuma** [comment]
@KarenEfereyan I believe not - there's already a merged PR for this, but it hasn't been deployed yet: https://github.com/creativecommons/cccatalog-frontend/pull/1206

@zackkrida will confirm when that's done and will close the issue out.

**Comment by zackkrida** [comment]
@KarenEfereyan Yes it's already been fixed, you can take a look on our devsite: https://ccsearch-dev.creativecommons.org/

I'll close this, thanks everyone!

**Comment by KarenEfereyan** [comment]
Okay @zackkrida ill be on the lookout for another open issue
