### ISSUE TITLE
Add `image_id` query parameter to attribution SVG urls

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1208]
As discussed [here](https://github.com/creativecommons/cccatalog-api/issues/393), we will add an `image_id` query parameter to our license SVG urls in our HTML attribution.

Example link: 
`https://search.creativecommons.org/static/img/cc-by_icon.svg?image_id=a3565050-50dc-4a57-8986-dc6bc3d8af48`

Changes will be made in [this file](https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/utils/attributionHtml.js).

**Comment by KarenEfereyan** [comment]
@zackkrida can I work on this?

**Comment by rochisha0** [comment]
Yes go ahead @KarenEfereyan

**Comment by KarenEfereyan** [comment]
Waow and i was here working 😫😫😫
