### ISSUE TITLE
'404' placeholder should be replaced with a nicer looking "image not available" picture

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#121]
The 404 placeholder shows up in situations where the image has not actually 404'd, such as when an HTTP image is blocked, or any other situation where the browser fails to render an image. It's also not very attractive from a design perspective.

**Comment by kgodey** [comment]
@aldenstpage is this still an issue?

**Comment by aldenstpage** [comment]
It's still an issue. I rewrote the title and description with some additional details.

**Comment by sgrepos** [comment]
I'd like to work on this issue

**Comment by kgodey** [comment]
Go ahead.

**Comment by sgrepos** [comment]
@kgodey Unfortunately it's been a busy week and I haven't gotten the chance to work on this. Please remove the in progress label so someone else can work on it.

**Comment by ashikmeerankutty** [comment]
![image_not_available](https://user-images.githubusercontent.com/10515204/56117400-9a911800-5f85-11e9-878b-3f998609a6c8.jpg)
 How about replacing the current image with this one ?

**Comment by kgodey** [comment]
Marking as in progress since there's an open PR.
