### ISSUE TITLE
Fix Hover Dropdown in Nav

### ISSUE THREAD

**Issue by tushar912** [creativecommons/cccatalog-frontend#1211]
## Description
The About and Resources dropdown should open only on hover but Currently on mobile-view it opens automatically on toggling hamburger menu

## Expectation
The about and resources dropdown should open only on hover like in desktop view.
![Peek 2020-09-12 14-37](https://user-images.githubusercontent.com/59223034/92992062-9e6ff380-f505-11ea-8997-958da71e7aa3.gif)

## Screenshots
![Peek 2020-09-12 14-27](https://user-images.githubusercontent.com/59223034/92992017-2acde680-f505-11ea-8a51-9e10f8764264.gif)

## Environment
It is in mobile view

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
Hi @tushar912 , we actually want the dropdowns expanded in the mobile menu automatically, so mobile users can see all of the options right away. Thanks for looking into this.
