### ISSUE TITLE
External link to API from Resources drop down in nav

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1216]
Let's put a link to our API in the Resources drop down of the CC Search header nav.

**Comment by zackkrida** [comment]
Link: https://api.creativecommons.engineering/v1/

**Comment by neeraj-2** [comment]
i would like to work on it

**Comment by neeraj-2** [comment]
@zackkrida what should be the name of the tab?

**Comment by zackkrida** [comment]
@neeraj-2 it should be "API". Thanks!

**Comment by neeraj-2** [comment]
> @neeraj-2 it should be "API". Thanks!
👍
