### ISSUE TITLE
Typo on new Support page

### ISSUE THREAD

**Issue by zackkrida** [creativecommons/cccatalog-frontend#1218]
See here: https://ccsearch-dev.creativecommons.org/support

Need to switch "THE SEARCH ENGINE FOR OPEN MOVEMENT" to "THE SEARCH ENGINE FOR THE OPEN MOVEMENT"

<img width="356" alt="Screen Shot 2020-09-21 at 5 16 45 AM" src="https://user-images.githubusercontent.com/6351754/93804307-d2bc7180-fbe1-11ea-84e6-2a7b6dce15be.png">

**Comment by rochisha0** [comment]
I'll fix this!
