### ISSUE TITLE
Remove Halloween images

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#122]

**Comment by janeatcc** [comment]
Can we bump this up in priority to be in the next release? (17 Jan)

**Comment by brenoferreira** [comment]
I think we can. Do we replace the images with new ones with any other theme? Or do we just remove them?

**Comment by janeatcc** [comment]
I think we should replace them with public domain images for the PD day launch. And then we can revisit after this sprint whether to get rid of a "top picks" section entirely.

**Comment by brenoferreira** [comment]
Sounds good.

I found these ones in our catalog licensed under CC PDM 1.0. How do you like them?

https://ccsearch.creativecommons.org/photos/2b091d94-e72f-46a8-a1b2-ab23ab9ceedf
https://ccsearch.creativecommons.org/photos/740aec57-acaa-4734-92b4-61bc967fecb9
https://ccsearch.creativecommons.org/photos/fb1b5814-e0b4-4fe4-9f57-7cd3b5096404
https://ccsearch.creativecommons.org/photos/ea89aea5-c51d-4642-825e-081ace7f6cb7
https://ccsearch.creativecommons.org/photos/be846374-26f0-4d2e-9909-f87be38f4143
https://ccsearch.creativecommons.org/photos/b80df152-fe77-4f49-a048-f0891184a1c0
https://ccsearch.creativecommons.org/photos/2cbf4a64-28ea-454a-86e2-ae52c1b93a8a

**Comment by janeatcc** [comment]
I think they are great... I guess the USA references make sense, too, given that it is PD day in the U.S. But I wonder if there are images that are more representative of the diversity in the U.S.? If not, what is here is fine.
