### ISSUE TITLE
Alignment of search icon

### ISSUE THREAD

**Issue by adrijshikhar** [creativecommons/cccatalog-frontend#1227]
## Description

Is the search icon rightly aligned?

## Reproduction

1. Open the homepage and see the icon

## Expectation

The icon should be properly aligned and utilize the whole space below it.
## Screenshots

![2020-09-25-123335_1920x1080_scrot](https://user-images.githubusercontent.com/41939219/94237072-e6424200-ff2b-11ea-914b-f7e2f72f0ea5.png)

## Environment

 - Device: Dell 7567
 - OS: Manjaro i3wm
 - Browser: Google Chrome
 - Version: 85

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
This is definitely a bug. Thanks @adrijshikhar

**Comment by neeraj-2** [comment]
I would like to work on it.Can I?

**Comment by adrijshikhar** [comment]
i am already on it
