### ISSUE TITLE
Attribution event clicks are triple counted

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#1231]
## Description
When a user clicks the "copy attribution" button, we register [an event with our analytics API](https://api.creativecommons.engineering/analytics/#operation/addDetailPageEvent) to help us figure out which works are embedded most frequently. It seems like the frontend registers this event 3 times when it ought to only be registered once.

## Reproduction

1. Open network debugging tab in your browser tools
2. Navigate to the image detail page for any image
3. Click "copy" button in the attribution panel
4. See that 3 requests to the attribution event endpoint have been made

## Expectation
The event should only be registered once (ideally clicking the copy button multiple times in the same session wouldn't trigger registration again)

## Screenshots

![Screenshot from 2020-09-29 10-43-39](https://user-images.githubusercontent.com/25728015/94574665-61b03600-0241-11eb-95e7-55bda6c29cf9.png)

![Screenshot from 2020-09-29 10-43-56](https://user-images.githubusercontent.com/25728015/94574626-5826ce00-0241-11eb-8b45-c76677e2b98b.png)

## Environment
- Browser: Firefox 78.3.0esr (I suspect all browsers are affected)

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by aldenstpage** [comment]
Additionally, it would be helpful if you could confirm that the event is always triple counted, as this will help us account for errors in our usage statistics.

**Comment by zackkrida** [comment]
@aldenstpage The event is consistently tripled. The buttons have all incorrectly have the same `id` in html, and the `copySuccess` event which triggers the request to our analytics server fires once for each copy button on the page. Which, currently and historically, has been 3.
