### ISSUE TITLE
Possible problem generating session_uuids for analytics?

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#1236]
## Description
There is a very large gap between the number of unique daily sessions counted in our analytics server versus the number of sessions and users tracked on Google Analytics. For instance, GA says there are tens of thousands of users and sessions today, while the analytics server only has ~160 unique session_uuids. Could you check the implementation of this feature?

What I'm seeing now is a very large number of searches distributed between this small number of sessions, which doesn't seem right.

## Reproduction
Does not apply

## Expectation
Every time the user opens CC Search in a new tab, the frontend should generate a `session_uuid` and preserve it throughout the session. Any action the user takes on other pages, like clicking an attribution button on a detail page, should use the same session_uuid. session_uuid generation should be handled entirely client side; no two users should have the same session_uuid. When the user closes CC Search, the session_uuid should be erased from client side storage. Next time the user opens CC Search again, a new session_uuid should be generated.

**Comment by zackkrida** [comment]
The usage analytics shares session id logic with the A/B test code, which seems ill-advised to me. The session ids are stored in a cookie for 7 days. 

There may be additional issues with the Google Analytics tracking that further complicates the issue, but diagnosis there is still pending.

**Comment by zackkrida** [comment]
@obulat 

The [`UsageDataService`](https://github.com/creativecommons/cccatalog-frontend/blob/82fbff11c3584e0198f8b0d05fbd4d1668e3e3d1/src/api/UsageDataService.js#L14) methods that accept a `sessionId` parameter currently use `state.sessionId`, a cookie that expires after *7 days*. We want to use a new cookie that expires at the end of the user session.

Similar to the logic in `abTests/lib/sessionId.js` please replace all instances of `state.sessionId` in [src/store/search-store.js](https://github.com/creativecommons/cccatalog-frontend/blob/780253ab7bd6aaa9fdae5f695f2e631480e4c62a/src/store/search-store.js#L122) with a _new_ cookie `USAGE_SESSION_ID`, that has no expiry. A cookie without an expiration will expire as soon as the user's session ends.

You can _either_ store the cookie in the vue store or just replace the `state.sessionId` calls with inline logic like this: `Cookie.get(USAGE_COOKIE_NAME) || Cookie.set(USAGE_COOKIE_NAME, uuid())`.
