### ISSUE TITLE
Creator clicks are not registered with analytics API

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#1237]
## Description
When users click the name of a creator in a search result, they are redirected to the creator's page outside of CC Search. We set up an endpoint for tracking how often this button gets used, but the data suggests that it stopped being used sometime this year.

## Reproduction

1. Click the creator name with the browser network debugger enabled.
2. Observe that no CREATOR_CLICKED event is registered

## Resolution

- [ ] I would be interested in resolving this bug.

**Comment by zackkrida** [comment]
@obulat 

<img width="1904" alt="Screen Shot 2020-10-02 at 1 06 08 PM" src="https://user-images.githubusercontent.com/6351754/95129299-8c453780-06f6-11eb-866d-9ac4ed050451.png">

Please add an `@click` event to these links that dispatches a `SEND_DETAIL_PAGE_EVENT` where the eventType is `DETAIL_PAGE_EVENTS.CREATOR_CLICKED`.

This is a great example of what you need to do, here you can see a `DETAIL_PAGE_EVENTS.SOURCE_CLICKED` event: https://github.com/creativecommons/cccatalog-frontend/blob/6157a7a64cd17becec3fe878c20e8ed39b0b1e97/src/components/ImageDetails/PhotoDetails.vue#L132-L133
