### ISSUE TITLE
Lists get deleted on the API layer but are not removed from LocalStorage, causing the non-existent list to get stuck in the user's List page.

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#124]

**Comment by brenoferreira** [comment]
Hi @aldenstpage 

I couldn't reproduce this. Do you still experience this issue? If so, could you provide a step-by-step of how to reproduce this bug?

Thank you

**Comment by aldenstpage** [comment]
I tried to reproduce the issue again and didn't succeed. I'm going to close this for now, I'll let you know if I figure out what conditions lead to this. Thanks!
