### ISSUE TITLE
Update Nappy outbound link structure on Meta Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#1249]
The Meta Search feature for images on CC Search includes the stock photo site Nappy.

In the past, searching for cars would look like this nappy.co/?s=car

Now, they look like this nappy.co/search/car 

Therefore, we need to change the search path to /search/search-term for this to continue working.

Currently, the old URL structure just takes users to the Nappy homepage.

**Comment by annatuma** [comment]
I realize this project is in maintenance mode and we're not planning any additional deploys, but flagging this broken experience for @zackkrida so we can discuss next week if/how to tackle.

**Comment by zackkrida** [comment]
@annatuma For Nappy's own sake, I'd recommend they set up a 301 redirect on their WordPress site to rewrite urls from their old style to the new. It will fix _this_ issue, but also any SEO issues they may have from other sites/platforms/backlinks out in the wild.

`nappy.co/?s=car => nappy.co/search/car`

Happy to advise them on how best to do this! I believe their site is on WordPress, and there's a number of ways to do this with varying degrees of technical knowledge required.

**Comment by zackkrida** [comment]
Nappy has informed us that they will be implementing 301 redirects in the coming days. 
Closing: regardless of the outcome, our involvement is complete.
