### ISSUE TITLE
CC search does not work on old version of Chrome

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#125]
Not sure if we care about browser versions this old, but CC search beta does not work on 

Google Chrome | 49.0.2623.112

**Comment by kgodey** [comment]
@janeatcc can you provide more details about what doesn't work?

**Comment by janeatcc** [comment]
I think it doesn't even load on the user's browser. However, I told the user it was a very old version of Chrome and that they should try another browser (they also can't update Chrome due to their OS). So we can close this if it's too old of a browser version for us to worry about.

**Comment by kgodey** [comment]
our list of supported browsers includes Chrome 22 and up (list is on https://creativecommons.github.io/contributing-code/) so this seems relevant. whoever works on it needs to investigate and document the issues before they fix it.

**Comment by akandeBolaji** [comment]
Can i work on this?

**Comment by akmadian** [comment]
@akandeBolaji Sure! Please remember to investigate and document the issues here before working on fixes :)

**Comment by akandeBolaji** [comment]
@akmadian I just tested CC search on Chrome Version 49.0.2623.112 (64-bit) and it works well, attached are screenshots taken.

**Comment by brenoferreira** [comment]
I don't see any screenshots, did you upload them @akandeBolaji ?

**Comment by akandeBolaji** [comment]
![bandicam 2020-02-26 18-11-58-996](https://user-images.githubusercontent.com/35887799/75370121-ebbba900-58c4-11ea-854b-5566248f56f2.jpg)
![bandicam 2020-02-26 18-12-02-138](https://user-images.githubusercontent.com/35887799/75370128-ee1e0300-58c4-11ea-90d3-970268ab1d95.jpg)
![bandicam 2020-02-26 18-12-14-059](https://user-images.githubusercontent.com/35887799/75370134-ef4f3000-58c4-11ea-83aa-6b9c2fb58c0e.jpg)

**Comment by akmadian** [comment]
Have you tried verifying that other functionality works? Things like filtering, copying attribution, image details displaying properly, social sharing, etc. Be thorough!

**Comment by akandeBolaji** [comment]
Just did that, I'm able to filter, copy, display details and share on chrome version 49. 
I suggest this issue be closed as fixed since all main functionality works on the chrome version reported.
Any other issue would likely be multiplatform

**Comment by brenoferreira** [comment]
Thanks for checking this 👍. I'll close the issue
