### ISSUE TITLE
surface somehow that "copy" attribution has happened

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#138]
> "I also felt that the UI feedback when hovering and clicking on the button could have been clearer - I missed the slight size-increase transition the first time, and thought that nothing had happened, so clicked again. As copying something to the clipboard is an otherwise 'invisible' action, I would have found it useful to get clearer feedback from the interface that it had indeed happened."

I agree with this. I feel like previously there was some kind of hover tag that surfaced that the attribution had been copied? Can we explore getting something like that back, or another visual indicator?

**Comment by brenoferreira** [comment]
This has been fixed in #129 and will be featured in the next release

**Comment by brenoferreira** [comment]
@janeatcc can I close this?

**Comment by janeatcc** [comment]
yep! closing
