### ISSUE TITLE
404 images appearing on search results page and image page

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#140]
e.g. https://ccsearch.creativecommons.org/search?q=mountain&provider=&li=cc0,pdm&lt=

**Comment by aldenstpage** [comment]
It's a data issue, some of these links are insecure HTTP, which we cannot display. The MET image servers support HTTPS, so my suggestion is that the MET data should be updated upstream to use HTTPS. @sclachar, what do you think?

If this isn't an attractive option for whatever reason, we can plan time next sprint for me to implement an HTTPS image proxy.

**Comment by janeatcc** [comment]
This is still happening, fyi. 

https://ccsearch.creativecommons.org/search?q=horse&provider=met,clevelandmuseum&li=&lt=

the image in question: https://ccsearch.creativecommons.org/photos/00c4d25a-dc4f-4097-90a5-9748388e3105

**Comment by chicocvenancio** [comment]
I'm not sure this is a protocol issue. https://ccsearch.creativecommons.org/photos/cf58cccf-2aed-46a6-92e2-18591a1cf2cd is pointing to (404) https://images.metmuseum.org/crdimages/ap/web-large/246958.jpg while https://www.metmuseum.org/art/collection/search/10411 points to (200) https://images.metmuseum.org/CRDImages/ad/original/246958.jpg

**Comment by janeatcc** [comment]
This may have to do with the duplicates we checked and removed. @sclachar what do you think?

**Comment by aldenstpage** [comment]
Fixed in API v0.23.0

**Comment by kgodey** [comment]
@aldenstpage @janeatcc is there a separate issue to track the issue from @chicocvenancio's comment above?

**Comment by aldenstpage** [comment]
@kgodey That result is broken due to an edge case. It looks like @chicocvenancio's image originally worked, and was cached as a valid image link. The cache has a TTL of 30 days to minimize repeated validation of images; this works well in most cases but will result in 404'd image sneaking through if it was deleted less than 30 days ago since it was last validated.

**Comment by kgodey** [comment]
It might be good to have a way for users to manually report 404'd images so that we could automatically re-check the link and remove from the cache as needed. @janeatcc what do you think?

**Comment by janeatcc** [comment]
I think this is a good idea. Was also talking to Sarah about having a way for people to log issues from front page of cc search that is specific to search and not info@, but also not a generic blue feedback form tab. I think we should implement one thing that is a way to log issues specific to cc search for this kind of thing and other errors. Kriti, let's add this to our 1:1 and figure out best way to implement

**Comment by aldenstpage** [comment]
I stand corrected; @chicocvenancio's image is erroneously included in the search results because the MET servers return the wrong status code for the image.

```
$ curl -i http://images.metmuseum.org/crdimages/ap/web-large/246958.jpg
HTTP/1.1 200 OK
...
```

That should return a `404 Not Found` or `301 Moved Permanently`, not `200 OK`. The server can't delete the image preemptively when an incorrect status code is returned from the provider.

**Comment by aldenstpage** [comment]
I opened creativecommons/cccatalog-api#197 to address this

**Comment by kgodey** [comment]
Since the problem here wouldn't be solved by un-caching, we can revisit the cache TTL if/when broken links become an issue. I like Jane's idea of an easy way to report bugs or issues and hopefully we'll get reports of broken links through that if they become a problem.
