### ISSUE TITLE
Menus disappear too quickly

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cccatalog-frontend#141]
![cc-search-menus](https://user-images.githubusercontent.com/7093838/51194782-c5ea6500-18b9-11e9-9269-82fcf187b47b.gif)

This may be a preference rather than a UX issue, but if you scroll down to the end of the "Select source" menu, the menu disappears, which makes it hard to click on.

**Comment by janeatcc** [comment]
Seems like a bug. Having @brenoferreira take a look when he can!

**Comment by kgodey** [comment]
@janeatcc should we add this to the current sprint?

**Comment by janeatcc** [comment]
Only if Breno has time. This isn't as urgent and can be after this next sprint. I just tested it and it works, just disappears too quickly

**Comment by kgodey** [comment]
Let's leave it out for now.

**Comment by HAMZABoxer98** [comment]
@little-wow, I think the interface has been changed and this bug is doesn't exist anymore.
if it still exist, can you give me that link because I couldn't find this page?

**Comment by kgodey** [comment]
@HAMZABoxer98 you're right, this is no longer relevant.
