### ISSUE TITLE
hard code names of providers not currently listed at /about

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#144]
see http://api.creativecommons.engineering/statistics/image and https://ccsearch.creativecommons.org/about

We need this in time for CMA's 23 jan launch, so we should release this thur.

**Comment by janeatcc** [comment]
CMA should be listed as Cleveland Museum of Art (full name at http://www.clevelandart.org).

**Comment by brenoferreira** [comment]
Fixed in #146
