### ISSUE TITLE
no creator listed for CMA images

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#152]
e.g. https://ccsearch-dev.creativecommons.org/photos/354e92de-9cdc-4c89-9cfa-614f654a2538

Is this because they didn't list any in metadata, or somehow structured it differently in API?

**Comment by aldenstpage** [comment]
It's because we don't have the Creator in our database for these works. Take a look at the raw data here http://api.creativecommons.engineering/image/354e92de-9cdc-4c89-9cfa-614f654a2538

**Comment by sclachar** [comment]
Some images do not specify a creator. Here is an example of an image with that info: https://ccsearch-dev.creativecommons.org/photos/fcaae643-fbe2-407f-ae9a-53acb020cb88

**Comment by sclachar** [comment]
@janeatcc and @brenoferreira should we display a generic placeholder text for images without a creator listed?

**Comment by kgodey** [comment]
I think we could skip showing the "Creator" label if there is no creator listed.

**Comment by brenoferreira** [comment]
Maybe show a "Not Available" instead of just hiding it?
