### ISSUE TITLE
French accent in title doesn't show up on image pages

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#154]
see https://ccsearch-dev.creativecommons.org/photos/9ee73b56-ca58-4069-99ea-c9f90889dade

https://ccsearch-dev.creativecommons.org/photos/36880021-df93-4654-8954-4a053427ed96

**Comment by brenoferreira** [comment]
@aldenstpage This seems to be an issue on the response encoding, as seen in the response here: https://api.creativecommons.engineering/image/9ee73b56-ca58-4069-99ea-c9f90889dade.

**Comment by aldenstpage** [comment]
@sclachar Can you check that the Cleveland Museum of Art has been encoded in utf-8 correctly? It's correct on the [source page](http://clevelandart.org/art/1954.732), but escaped in our database.

**Comment by janeatcc** [comment]
this is still a bug, fyi: https://ccsearch.creativecommons.org/photos/08a3475d-eb78-4fc6-ac46-33d3ac63d608
