### ISSUE TITLE
Add metatags for social integration

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cccatalog-frontend#165]
Social sharing is sad right now because the metatags haven't been added: https://twitter.com/creativecommons/status/1088090712497967104

This impacts SEO as well: https://www.wordstream.com/meta-tags

**Comment by pratikmishra356** [comment]
Hi, I am working on this issue.

**Comment by viditvarshney** [comment]
close this issue if this is done

**Comment by kgodey** [comment]
@brenoferreira I saw something about this not working on Slack, could you update the issue with those details or close?

**Comment by janeatcc** [comment]
need to deploy on dev first before we merge

**Comment by kgodey** [comment]
This is still an open issue, latest PR plus discussion is here: https://github.com/creativecommons/cccatalog-frontend/pull/214. Please post here if you want to work on it since @sgrepos is busy.

**Comment by pratikmishra356** [comment]
Yes, I will  resolve this issue

**Comment by kgodey** [comment]
@pratikmishra356 okay, I've marked as "in progress". Let me know if you have any questions about my comments on https://github.com/creativecommons/cccatalog-frontend/pull/214.

**Comment by janeatcc** [comment]
Let's remember to make this live only in the dev branch and not push to prod yet. Sarah and I still need to review and test. Thanks!

**Comment by janeatcc** [comment]
Here's a test tweet: https://twitter.com/testaccountcc21/status/1113820480916480006. 

Questions:
- Are the social metatags in there? If so, how can I see what they are? 
- Can we add attribution into the social metatags, or are the metatags purely to display the link and image in Twitter? 
- Is this true of FB and Pinterest as well?

**Comment by janeatcc** [comment]
Additional question: When a user clicks on a social sharing button, are we simply sending them to the social media site to login with suggested language and social metatags? Or is there anything else that happens in the interim, e.g. logging into our platform in anyway or us hosting any data?

**Comment by little-wow** [comment]
On the test tweet: this is showing the Flickr website, which has baked in Metadata already.
Do you want to send users to the CC Search site or to the original image?

I'm not sure if the social sharing buttons issues //open graph metadata tags for rich snippets are conflating two separate issues?

**Comment by janeatcc** [comment]
We want to send them to the Flickr website. 

I don't know -- but I'll let @brenoferreira and others read the question first before moving it to another issue (there is no issue around buttons, only an approved PR right now)

**Comment by kgodey** [comment]
Removing "in progress" tag since there has been no update for 7+ days.

**Comment by janeatcc** [comment]
Reminder to keep this feature flagged for now.

**Comment by kgodey** [comment]
I'm closing this issue since we have metatags and the remaining issues are captured in #269 and #270.
