### ISSUE TITLE
Add the ability to scroll to the top of the page, when infinite scroll is enabled

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#169]
Issue copied from checklist in #32.

**Comment by SingularReza** [comment]
I am working on this issue

**Comment by pratikmishra356** [comment]
I had solved this issue and will soon raise a PR

**Comment by manyaagarwal** [comment]
Is this issue still open? If so, can I work on it?

**Comment by SomtochiAma** [comment]
I want to work on this issue. Is it still valid since the infinite scroll is about to be removed completely?

**Comment by kgodey** [comment]
I think this is still useful even with the "load more" button.
