### ISSUE TITLE
Fix remaining Image Detail page issue

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#172]
I don’t know what that little pop-up navigator thing is, but it’s confusing. I’d remove it.
Issue: No download link to get the image, or clear link to go to the source site. Have to intuit to click on the right link in the detail information.

---

Issue was copied from #50.

**Comment by catherinehoang** [comment]
Hi, I'd like to work on this

**Comment by kgodey** [comment]
I'm closing this issue since we have a download link now.
