### ISSUE TITLE
Improve project setup experience

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#173]
- [x] Provide Docker option for running locally.
- [x] Make sure README is fully up-to-date.
- [x] Describe how to run the project locally and verify that the steps work.
- [x] Describe how to run the tests.
- [x] Include sample data for local development.

**Comment by brenoferreira** [comment]
@kgodey what did you intend to be added with `sample data for local development`?

**Comment by kgodey** [comment]
@brenoferreira if we want people developing locally not to connect to our development or production API server (or if our API is not accessible for some reason), we may want to provide a JSON file with sample data or maybe a mock API that they can use to have some data to display locally.

If you don't think we need that, just add instructions on what API URL should be used for local development if it doesn't already exist.

**Comment by kgodey** [comment]
We don't need sample data since we just point to the API URL, closing this.
