### ISSUE TITLE
Replace Puex as state management library

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#179]
The state management library we use https://github.com/egoist/puex is deprecated and no longer maintained. We should move to something else, like [Vuex](https://github.com/vuejs/vuex)

**Comment by amazzoccone** [comment]
How complex is this refactor? It would be cool to contribute on this 👍.

**Comment by kgodey** [comment]
@amazzoccone it seems fairly straightforward since the APIs are compatible, are you working on this?

**Comment by amazzoccone** [comment]
@kgodey actually not, but i could make a PR with a reference to this issue, it's ok?

**Comment by kgodey** [comment]
Sure, go ahead!
