### ISSUE TITLE
clicking back to search results takes user back to top of list vs place they left off

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#184]
"I've been finding that when I search in CC Search and then go "back to results" it takes me back seemingly to the top of the whole list and I have to find where I was before, which is a bit tedious" --@evarogers

**Comment by VatsalSin** [comment]
Working on it.

**Comment by HAMZABoxer98** [comment]
I am going to work on this.

**Comment by kgodey** [comment]
Removing "help wanted" since we moved this into the active sprint.
