### ISSUE TITLE
Top nav search box returns nothing 

### ISSUE THREAD

**Issue by mmoreshead** [creativecommons/cccatalog-frontend#188]
Steps to reproduce:

Go to CC Search
Go to Lists or About
Use the search in the top right hand side to search for something
It goes to the search results page but there's nothing there
Not even a "this search returned 0 results message"
The thing I originally typed in the search is lot populated in the top search either.

So I fully quit my browser (firefox) and opened a new session.
Same results as above.

**Comment by pratikmishra356** [comment]
Hi I want to work on this issue can anyone please guide me in which file or section I should look for this.

**Comment by SingularReza** [comment]
I solved this bug, can I submit a PR?

**Comment by brenoferreira** [comment]
@SingularReza absolutely!

**Comment by SingularReza** [comment]
@brenoferreira the test is failing and I couldn't get a solution for it. I think it has something to do with the action being in a mounted hook. Please check my PR

**Comment by brenoferreira** [comment]
Fixed in #234
