### ISSUE TITLE
Add Google Form link on lists page asking people whether they care if we remove it

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#193]

**Comment by janeatcc** [comment]
Assigning this to myself first

**Comment by janeatcc** [comment]
Please update /lists page with the text and link to Google form, all finalized. Thank you!

https://docs.google.com/document/d/1PHUiDotr-SPtlaIRPVxnewAzW8nV6UlXXwsQL1kWKY4/edit#
