### ISSUE TITLE
CC0 text on image page 

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#194]
CC0 reads "CC CC0 1.0" on image pages, e.g. https://ccsearch.creativecommons.org/photos/6a93f964-786d-4dbd-8925-df30ef611656

Should read "CC0 1.0"

**Comment by kgodey** [comment]
Moving this to the active sprint since @brenoferreira fixed it.

**Comment by janeatcc** [comment]
This is still happening: https://ccsearch.creativecommons.org/photos/ac1d6d17-1803-4c0c-9a5c-086f2b4a4c7f

**Comment by janeatcc** [comment]
Here, too: https://ccsearch.creativecommons.org/photos/f8fd15c0-3545-4482-b75d-46950bcd8fa4
