### ISSUE TITLE
Clicking on image tags not working as expected

### ISSUE THREAD

**Issue by VatsalSin** [creativecommons/cccatalog-frontend#203]
-> Expected Behavior :- When we click on image tag, we must get search results for the respective tag.

-> Current status:- When we click on the image tag the URL in the URL bar changes accordingly but the search results are not updated.

-> For instance when I click on tag "nature" from some image of "city" we get following:-  

![screenshot 55](https://user-images.githubusercontent.com/33460761/53691907-10ae3680-3dad-11e9-938f-cbaa60d55941.png)

**Comment by VatsalSin** [comment]
I have figured out the problem can I submit the pull request for the same

**Comment by dhruvkb** [comment]
@VatsalSin are you still working on this problem? If not, can I take it up?

**Comment by VatsalSin** [comment]
I am working on this. Sorry for late reply. I was busy due to exams.
