### ISSUE TITLE
Add link to download watermark with attribution

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#207]
Add a link in the photo details page that lets users download the image inside a frame containing the proper author attribution and license.

Link to the API issue https://github.com/creativecommons/cccatalog-api/issues/209 and PR https://github.com/creativecommons/cccatalog-api/pull/214

**Comment by janeatcc** [comment]
Separate out into two checkboxes like on thttps://ccccatalog.herokuapp.com/photos/a5fdc359-4196-4446-9ee9-1b1d2fae0625

Placeholder text for (?) pop-ups for each option is as follows:

“Include attribution in frame” (?) --> pop-up: "This option frames the image in white with a plain text attribution beneath."
“Embed attribution metadata” (?) --> pop-up: "This option embeds CC license metadata in the image file using [XMP](https://wiki.creativecommons.org/wiki/XMP)." 

cc: @aldenstpage to review the metadata explanation -- even though it's just a placeholder!

**Comment by janeatcc** [comment]
Did the new placeholder text get deployed?
