### ISSUE TITLE
"undefined undefined" and no photo shows for a period of time

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#210]
resolves after ten seconds or so https://ccsearch.creativecommons.org/photos/4f0345b0-5f0e-42f5-860c-698d9621fe88 looked like below before it did

![undefined bug](https://user-images.githubusercontent.com/6394777/54060538-e9db7000-41b1-11e9-8b80-aba325f0bc8d.png)

**Comment by aldenstpage** [comment]
It was a temporary issue while some database maintenance related to the
release was in progress

**Comment by janeatcc** [comment]
k
