### ISSUE TITLE
Add feature flag to CC Search to hide in-development features

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#215]

**Comment by aldenstpage** [comment]
So I think the way to go about this is to introduce a configuration file in the Vue code, like `src/features.json` or wherever you think it's most appropriate, with something like...
```
{
    watermark_enabled = False,
    foo_enabled = True,
    bar_enabled = False,
   . . .
}
```

In the deployment code, I'll overwrite this file with deployment-time settings from environment variables. Once @breno figures out the right place and format for the configuration I'll set update the deployment scripts to accommodate
