### ISSUE TITLE
In mobile view (S - 320px) the title "<number> <photo-name-searched> Photos" is partially hidden when searched for a picture.

### ISSUE THREAD

**Issue by alishamohanty** [creativecommons/cccatalog-frontend#224]
**Describe the bug**
When the screen size is changed to Mobile (S - 320px ) the page showing the searched results of photos having the title "<some-number> <searched-name- of-photo> Photos" gets partially viewed.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Home Page'
2. Search for a picture For example ''Galium"
3. The page saying the little "xx Galium Photos" is partially visible.

**Expected behavior**
Clear view of the title for example "xx Galium Photos"

**Screenshots**
![Screenshot from 2019-03-14 22-15-52](https://user-images.githubusercontent.com/36623306/54375298-caa77b80-46a6-11e9-8fe1-098110b75afc.png)

**Comment by alishamohanty** [comment]
Can you assign the task to me @brenoferreira?

**Comment by kgodey** [comment]
Go ahead and work on it @alishamohanty.

**Comment by ayushshivani** [comment]
@kgodey can I work on this issue?

**Comment by alishamohanty** [comment]
@brenoferreira now you can close the issue :)
