### ISSUE TITLE
Add new tab for feedback

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#231]

**Comment by kgodey** [comment]
@janeatcc please edit the issue with details.

**Comment by janeatcc** [comment]
@brenoferreira can you create a Feedback tab with the details at the doc I emailed you, titled "user feedback tab for cc search"?

Some elements may depend on these issues:
https://github.com/creativecommons/tech-support/issues/80
https://github.com/creativecommons/tech-support/issues/66

I'd like to see it up on staging (or dev) before we push to production. Thanks!

**Comment by janeatcc** [comment]
This should happen this week @brenoferreira

**Comment by brenoferreira** [comment]
Fixed in #278
