### ISSUE TITLE
Missing Favicon

### ISSUE THREAD

**Issue by geekayush** [creativecommons/cccatalog-frontend#235]
Favicon is missing from the CC Search.

**Describe the solution you'd like**
Add the missing CC icon ( cccatalog-frontend/src/assets/cc_icon.svg ) in index.html ( cccatalog-frontend/index.html )

@brenoferreira Can I work on this issue?

**Comment by dhruvkb** [comment]
@geekayush since the homepage of Creative Commons has a [favicon](https://creativecommons.org/favicon.ico), CC Search should have one too. I think you should send a PR solving this issue.

**Comment by geekayush** [comment]
@dhruvkb Okay!

**Comment by geekayush** [comment]
@dhruvkb @kgodey 
[https://creativecommons.org](https://creativecommons.org/) uses these favicons as well as an apple touch icon. I believe it might be better to add these to CC Search. What do you people say?
![Screenshot from 2019-04-06 02-31-13](https://user-images.githubusercontent.com/22499864/55656371-4c0cac80-5814-11e9-850e-29788f48bfa1.png)

**Comment by kgodey** [comment]
I'll defer to @brenoferreira

**Comment by brenoferreira** [comment]
You're welcome to open a PR :)
