### ISSUE TITLE
About table overflows in mobile devices

### ISSUE THREAD

**Issue by geekayush** [creativecommons/cccatalog-frontend#236]
**Describe the bug**
The 'Providers' table in the 'About CC Search' section overflows the page.

**To Reproduce**
1. Go to 'https://ccsearch.creativecommons.org/about'
2. Change to the mobile view
3. Scroll down to 'Providers table'

**Expected behavior**
The table should not overflow the page after getting populated.

**Screenshots**
![localhost_8443_about(Galaxy S5) (1)](https://user-images.githubusercontent.com/22499864/54476041-c2724c00-481e-11e9-917b-1b30adc4facd.png)

---

![localhost_8443_about(Galaxy S5)](https://user-images.githubusercontent.com/22499864/54476043-c2724c00-481e-11e9-97ea-8390b8386a39.png)

**Smartphone (please complete the following information):**
 - Device: Galaxy S5
 - Browser: Chrome

@brenoferreira I would like to work on this issue.

**Comment by kgodey** [comment]
@geekayush do you still want to work on this?

**Comment by geekayush** [comment]
@kgodey Yes. I will submit a PR soon.
