### ISSUE TITLE
Embed Bug Report form in Feedback tab on CC Search

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#244]
**Feature Description**
We'd like to make an update to our Feedback page on CC Search. The page is split into two sections: Feedback and Report a Bug. The Feedback section has an embedded Google Form. We'd like to add a second embedded form to the Report a Bug section.

Link to form to embed: https://docs.google.com/forms/d/e/1FAIpQLSeSN1AIG8LrdgIdKpBj4IlPDhu6T5ndZ7z_QcISBu-ITCU0Yw/viewform

Let's also remove this content from the Report a Bug section:
"If you would like to report a bug you are encountering when using the tool, please email support-search@creativecommons.org or log the issue directly at Github."

We've included these instructions in the intro text for the form, and so they are now redundant.

**Comment by kgodey** [comment]
The email address this should go to has been updated from ccsearch@ to support-search@.

**Comment by janeatcc** [comment]
This should happen this week @brenoferreira

**Comment by kgodey** [comment]
@annatuma do we still want to do this?

**Comment by annatuma** [comment]
I think it makes sense to make it easier for folks to submit bug reports. I've created a form and will update the description above. I'm less concerned with this going straight to Fresh Desk, which seems like a setting we can implement later.

**Comment by annatuma** [comment]
Un-assigning @brenoferreira for the time being. This is a good task for an outside contributor.

**Comment by skidi3** [comment]
Hey! Can I work on this?

**Comment by kgodey** [comment]
@skidi3 go ahead

**Comment by akmadian** [comment]
It's been 13 days since we've last heard from @skidi3, so I'm going to free up this issue for someone else to work on.

**Comment by Tanuj22** [comment]
Can I work on this?

**Comment by cognitive137** [comment]
Hello, can I work on this?

**Comment by akmadian** [comment]
@Tanuj22 indicated their interest first, so I'm going to assign it to them. Here's a reminder to check the discussion in 588 to get a clearer definition of the work to be done.

**Comment by cognitive137** [comment]
Hi @akmadian , I left a request to work on this issue in #588 discussion, before @Tanuj22 . Please check it out and let me know.

**Comment by akmadian** [comment]
Ah, you're right! My apologies. I think I'll leave this assigned to @Tanuj22, unless they would like to turn it over to you.

In general, issues are best for indicating interest because they track discussion about the issue generally, instead of PRs which generally track discussion about a specific set of changes.

**Comment by rajchandak** [comment]
Hey @akmadian, is this issue being actively worked on? I would like to work on it.

**Comment by Tanuj22** [comment]
@rajchandak I have already sent a PR that closes this and it is `Ready for Final Review`. Please find another issue to work on. :)
