### ISSUE TITLE
The top categories section on the homepage does not scale with width

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-frontend#245]
The 'Top Categories' section on the homepage contains 4 hardcoded categories. When surfing on an ultrawide monitor, the section ends up looking like this:
![image](https://user-images.githubusercontent.com/16580576/54859122-80ba3780-4d2f-11e9-8390-8b33ea5e3a64.png)

This issue affects all computer browsers, does not affect smartphones.

One solution could be adding some more categories and displaying them when the screen is too wide. Another could be putting these images inside a container with a max-width and allowing content to be padded with whitespace on both sides. Another could be using some high-resolution images and scaling them up as width increases.

If I could get some direction as to which solution is preferred, if at all a solution to this is even considerable, I would not take too long to submit a PR for the same.

**Comment by kgodey** [comment]
We removed that section from the homepage so closing this issue.
