### ISSUE TITLE
Images in 'Top Picks' are poorly cropped

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-frontend#246]
The section 'Top Picks' consists of a mosiac of images that are hardcoded. On a regular display the page looks like so:
![image](https://user-images.githubusercontent.com/16580576/54859247-ff63a480-4d30-11e9-8d77-a0fd710dd7da.png)

First and foremost, I would love to see these images change with time. CC contains a huge collection of wonderful images and we have chosen to display a select 7 of them.

Something like a masonry layout (#225, #103) allowing every image to be shown in glorious entirety would do the page wonders. Currently Monocerotis (image no. 1), the bald eagle (image no. 4) and the NYC skyline (image no. 5) are all cropped in a way that the content is missing from view. 

If the masonry layout is too much, at the very least we need to find dimension appropriate images for these `div`s. Also the vertical margin between the images is too much.

If we could decide on a direction in which to proceed, I would be more than happy to submit a PR patching this.

**Comment by kgodey** [comment]
We're working on a redesign of the homepage which removes that section entirely so I'm going to close this ticket. Once the homepage redesign has shipped, feel free to open a new ticket if you have suggested improvements.
