### ISSUE TITLE
Image download button animation not right

### ISSUE THREAD

**Issue by dhruvkb** [creativecommons/cccatalog-frontend#250]
**Describe the bug**
This is a design issue. The animation on hovering over the download button is a bit uncanny. There is a color shift towards a lighter green and the white text turns black. This gives a weird look to the entire process:
![image](https://user-images.githubusercontent.com/16580576/54917453-db1aea00-4f21-11e9-8305-20693e0e90ae.gif)

**Expected behavior**
Regular buttons animate in a more subtle way, clearly showing all different states (idle, hover, clicked). For example:
![image](https://user-images.githubusercontent.com/16580576/54917657-4795e900-4f22-11e9-9375-c5340ebbd366.gif)

Occurs on every desktop browser.

**Comment by geekayush** [comment]
@brenoferreira @kgodey 

How about:
- Giving it rounded corners as that of the above buttons
- Keeping the text color white
- Giving a slightly darker green color on hover
![Screenshot from 2019-04-06 02-01-51](https://user-images.githubusercontent.com/22499864/55655060-bae80680-5810-11e9-9b0b-219abfde1928.png)

**Comment by kgodey** [comment]
Closing this issue since it was fixed in #323.
