### ISSUE TITLE
Allow CC Search to be added to web browsers as a search engine

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#254]
**Is your feature request related to a problem? Please describe.**
This is a feature request originally made in https://github.com/creativecommons/creativecommons.org/issues/674 for old Search, moving it here since we're deprecating old Search.

**Describe the solution you'd like**
You should be able to add CC Search as an in-browser search engine in Chrome, Firefox, and other browsers that support the feature.

**Comment by dhruvkb** [comment]
I would very much like to work on this issue.

**Comment by kgodey** [comment]
Go ahead!

**Comment by HAMZABoxer98** [comment]
@kgodey , the only way to achieve this is by requesting visitors to download a software that will change their default search engine the same as Bing and other search engines do. 
Do you think people will download and execute your software  ?
I searched for the solution but not able to provide such software, I am just discussing.

**Comment by dhruvkb** [comment]
@HAMZABoxer98 the intention is not to change the default search engine to CC Search, the intention is to enable CC Search to be added as _one of the installed_ search engines. This is achieved using semantic input field and search button `name` and `value` attributes as well as an Open Search XML specification.

References:
- [StackOverflow](https://stackoverflow.com/questions/14082568/how-to-let-google-detect-a-site-search-engine)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/OpenSearch)

**Comment by oksmelnik** [comment]
I'd like to work on this issue (outreachy applicant)

**Comment by kgodey** [comment]
go ahead

**Comment by brenoferreira** [comment]
Reopening this because #525 doesn't add the build step to copy the `opensearch.xml` file to the distribution assets directory

**Comment by Spring-dot** [comment]
I would like to work on this issue (outreachy applicant).

**Comment by brenoferreira** [comment]
This is already done. Please feel free to look at our other issues to find something that interests you

**Comment by Spring-dot** [comment]
ok!
