### ISSUE TITLE
Pixelated search results

### ISSUE THREAD

**Issue by little-wow** [creativecommons/cccatalog-frontend#263]
<img width="1350" alt="Screen Shot 2019-04-01 at 10 24 37 AM" src="https://user-images.githubusercontent.com/7093838/55335107-80751700-5468-11e9-9f7e-dccaa36c241b.png">

**Comment by dhruvkb** [comment]
Hello @little-wow, this is the result of a tradeoff between a filled masonry layout grid and a grey-area padded one. These thumbnails must have been very small in dimension, particularly width, and were therefore stretched out to fill the width of the column. If the results appear pixelated, try checking the option at the top right corner:
- [x] Prevent overscaling

This should return them to their actual, smaller size and get rid of pixelation.

**Comment by little-wow** [comment]
Okay, thanks, that worked, but I don't think that's intuitive as a design function for a few reasons:
1. As an average user, I'm not sure what overscaling means without a few seconds of thought
2. It's all the way to the right and not within my field of vision. I'd suggest maybe moving it up closer to the search results.

**Comment by dhruvkb** [comment]
@little-wow now that you've experienced the option, what according to you would be a better label for the checkbox? That could be a start. 

If the checkbox itself is confusing for the average user, I'd love to work on the issue but with concrete ideas from a UX designer as I have zero experience in the field.

**Comment by little-wow** [comment]
Maybe try "scale images to box" and move the checkbox closer to the # of search results. @brenoferreira what do you think?

**Comment by KhalidRmb** [comment]
HI! I'm new to CC and would like to work on this. @little-wow May I?

**Comment by kgodey** [comment]
Go ahead!

**Comment by pitu367** [comment]
Hi

**Comment by kgodey** [comment]
Removing in progress label since there has been no update for a month.

**Comment by 5hel2l2y** [comment]
I'll take a stab at this for Hacktoberfest!

**Comment by Dhruvi16** [comment]
Can I take this up?
Thank you. 
Dhruvi.

**Comment by Blackcipher101** [comment]
@dhruvkb Can I take this up

**Comment by Atanda1** [comment]
Hi, can I work on this?

**Comment by brenoferreira** [comment]
We don't have that checkbox anymore, so I think this is no longer relevant.

Thanks for your interest in contributing. Feel free to look at other open issues and picking something that interests you
