### ISSUE TITLE
Social sharing for Pinterest does not yield image in preview

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#269]
See attached screenshot in test Pinterest post. 

![pinterest test](https://user-images.githubusercontent.com/6394777/55581903-eb298b00-56d2-11e9-87b8-843d8ffdd32b.png)

**Comment by kgodey** [comment]
@janeatcc this is a known issue tracked in https://github.com/creativecommons/cccatalog-frontend/issues/165

**Comment by janeatcc** [comment]
Ok I didn't see any references to Pinterest image preview in that issue, which is why I created a new one. We can keep track of all of it in that issue if preferred.

**Comment by kgodey** [comment]
That makes sense. Let's keep this issue open and we can close it if it gets fixed by the other issue.
