### ISSUE TITLE
Social sharing for FB does not yield image preview

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#270]
See test post screenshots, also link to public test post here: https://www.facebook.com/creata.holmes.5/posts/109861736865359 

![Fb test 1](https://user-images.githubusercontent.com/6394777/55581951-12805800-56d3-11e9-9eec-c7023e5811df.png)

![FB test 2](https://user-images.githubusercontent.com/6394777/55581963-1b712980-56d3-11e9-87c4-eb8cd9978e4f.png)

**Comment by kgodey** [comment]
This is a known issue tracked in https://github.com/creativecommons/cccatalog-frontend/issues/165

**Comment by janeatcc** [comment]
Same comment re FB image preview -- no mention in that other issue.

**Comment by kgodey** [comment]
It's mentioned in the pull request: https://github.com/creativecommons/cccatalog-frontend/pull/214

**Comment by janeatcc** [comment]
Thought that was just for Twitter. It works for Twitter but not FB or Pinterest

**Comment by kgodey** [comment]
I thought I had mentioned it, I did test it locally. Let's keep the issue open and we can close it if it gets fixed by the other issue.
