### ISSUE TITLE
Improve image loading time when searching

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#28]

**Comment by dhruvkb** [comment]
Hello @sebworks I would like to work on this issue if you could help me a little bit. 

Can you give me some pointers into what aspects of the image delivery we would like to optimise? I have many divergent ideas and would gladly appreciate if you could help focus my efforts on some bottlenecks of the process by pointing them out.

**Comment by kgodey** [comment]
tagging @brenoferreira in case he has something to add

**Comment by kgodey** [comment]
@dhruvkb we don't have any defined criteria for what we want to improve so we've closed the issue. If you have any ideas you want to implement, please open a new GitHub issue with the details and we'll discuss.
