### ISSUE TITLE
remove Clarifai logos from tags for flip

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#289]

**Comment by dhruvkb** [comment]
@janeatcc is this the expected result? 
![image](https://user-images.githubusercontent.com/16580576/56405578-7b96cc80-628a-11e9-834d-7ea445ae5789.png)

Also, what's "flip"?

**Comment by janeatcc** [comment]
hi @dhruvkb this is going to go into the next sprint. we're flipping cc search beta to be the default at search.cc.org on 30 April. 

above but with the "tag by Clarifai" removed.

we'll note whether this one is open for community contribution during our sprint planning meeting in the next hour! :)

**Comment by kgodey** [comment]
@dhruvkb marking this as in progress since you seem to be working on it.
