### ISSUE TITLE
update /about page

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#290]
including removing Clarifai logo and blurb. Jane will provide updated text here before reassigning to Breno

**Comment by janeatcc** [comment]
please update with final text in [google doc](please update with final text in [google doc](https://docs.google.com/document/d/1R7FcGjiwE9y_nz0hQy8k7yisdgh9V23rva3enoqJd6c/edit#) sent in email -- not open to public.) sent in email -- not open to public.

**Comment by janeatcc** [comment]
fix typo -- add space "strategy and roadmap for CC Search hereand" so it reads "strategy and roadmap for CC Search here and" while retaining link

**Comment by janeatcc** [comment]
also need a space here "For more details, read theCC Terms of Use." between the and terms of use

**Comment by elharony** [comment]
It's easier to do it myself, and let @brenoferreira focus on other stubborn issues! 😄
