### ISSUE TITLE
update default language about CC Search that pops up on third party sites

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#291]
eg. https://www.facebook.com/creata.holmes.5/posts/109861736865359 
“The public beta of a new Creative Commons search tool, meant for testing and feedback. For the legacy search tool, please visit …”

Update to:

"A new Creative Commons search tool for creators seeking to discover and reuse free resources with greater ease and confidence."

**Comment by kgodey** [comment]
This is done already.

**Comment by janeatcc** [comment]
Can we actually update it to ""A new Creative Commons search tool for creators seeking to discover and reuse free resources with greater ease." deleting the 'and confidence' part? thanks.

**Comment by janeatcc** [comment]
@brenoferreira confirming that we deleted the "and confidence" part tho? :)

**Comment by janeatcc** [comment]
never mind!
