### ISSUE TITLE
change license types filter

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#295]
Change to "I want something that I can..."
- use for commercial purposes
- modify or adapt

- "use for commercial purposes" includes all PD content + non-NC licenses
- "modify or adapt" includes all PD content + non-ND licenses

**Comment by janeatcc** [comment]
But we should also have it be where a user can click both options, in that case the following results should show --

content that is under PD + non-NC + non-ND licenses, so only content under:

CC0
PDM
CC BY
CC BY-SA

re-opening until we can confirm this is the case

**Comment by elharony** [comment]
Hi @janeatcc ,

I believe @brenoferreira fixed it. Didn't he?

**Comment by janeatcc** [comment]
Yes! Thank you.
