### ISSUE TITLE
change order of filters

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#296]
So it's 
I want something that I can... (change according to issue https://github.com/creativecommons/cccatalog-frontend/issues/295)
All Licenses
All Providers
Search by Creator

**Comment by elharony** [comment]
Hi @janeatcc ,

So, you need to re-order the filter, and the new order should be (Left to right):
- All Licences
- All License Types
- All Providers
- Search by Creator

Is that correct? I noticed that you didn't mention the `All Licenses Types` so I just put it after the `All Licenses`.

**Comment by kgodey** [comment]
@elharony the "All License Types" should be replaced by "I want something I can..." as described in https://github.com/creativecommons/cccatalog-frontend/issues/295

**Comment by janeatcc** [comment]
Hi @elharony it should be what @kgodey said and this is the order from left to right:

"I want something that I can..." (change according to issue #295)
All Licenses
All Providers
Search by Creator

**Comment by elharony** [comment]
Thanks, @kgodey & @janeatcc ! 
Now I understand it, will fix both issues today.
