### ISSUE TITLE
Two providers are missing in the Providers table on the About page

### ISSUE THREAD

**Issue by ahmedkrmn** [creativecommons/cccatalog-frontend#318]
The `/statistics/image` endpoint of the of the CC Catalog API returns 11 different providers. The providers list on the CC Search About page only shows 9 them.

![Screenshot (120)](https://user-images.githubusercontent.com/20889958/56533716-85edea80-6558-11e9-8c1b-3c4e2ce4de34.png)
Both "500px" and "Museums Victoria" are missing

The issue seems to be caused because these two providers aren't listed in the [`PROVIDER_NAME_LOOKUP`](https://github.com/creativecommons/cccatalog-frontend/blob/master/src/api/ImageProviderService.js) object.

Is there any reason why these two providers were excluded?

**UPDATE**: "Museums Victoria" is in the `PROVIDER_NAME_LOOKUP` object, but the `provider_name` of "Museums Victoria" is set to "museumvictoria" instead of "museumsvictoria" (there's a missing s) in the [`this.$store.state.imageStats`](https://github.com/creativecommons/cccatalog-frontend/blob/master/src/pages/AboutPage.vue) array so it isn't showing up. "500px" was removed in commit 19ecb79aaaf6193ca4300bcfe879fbdcea4f4768.

![Screenshot (121)_LI](https://user-images.githubusercontent.com/20889958/56537705-758e3d80-6561-11e9-84b6-920e4da6c90d.jpg)

**Comment by kgodey** [comment]
500px was removed on purpose, see https://github.com/creativecommons/cccatalog-frontend/issues/293. We will be hiding those images from the API as well, it just hasn't deployed yet.

I'm not sure about Museums Victoria, @janeatcc would know.

**Comment by janeatcc** [comment]
Museums Victoria should not be missing AFAIK. @sclachar can you confirm?

**Comment by brenoferreira** [comment]
@ahmedkrmn you seem to be running on `localhost` which talks to the DEV api. That API has a dataset that's for testing purposes and might not contain data from all the providers available in the production API. Am I correct @aldenstpage ?

The Museum Victoria [is listed](https://github.com/creativecommons/cccatalog-frontend/blob/master/src/api/ImageProviderService.js#L73) on the `PROVIDER_NAME_LOOKUP` object

**Comment by ahmedkrmn** [comment]
@brenoferreira Changed to config file to use the main API, everything is now listed as expected. The bug has to do with the DEV API then.
Shall I close this issue?

**Comment by kgodey** [comment]
Thanks @ahmedkrmn. I'll close it.
