### ISSUE TITLE
Feedback from user testing

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#32]
- [x] The header background image is cool, but I feel it's a little too visually intricate and is hiding the search box.
- [x] Load times are very long on individual images and not all of the grids are populating at roughly the same speed – v slow.
- [x] I'm not sure why "Top Categories" would be useful to a user unless they can filter or know the source on it? The images in the categories feel pretty random
- [x] The disclaimer on the bottom – is there a way to spruce up that text a bit?
- [x] "Website by CC" in the footer – the link is Affinity Bridge
- [x]  I can't open the images in new tabs unless I click the title, in which case it just gives me the image (slowly loading) with no metadata
- [x] this seems to work for me on safari on the iphone, but search just hangs on all browsers i’m using on my laptop. any thoughts as to why ( OS: macos mojave 10.14 beta )?
- [ ] Strip whitespace from the queries
- [x] Add a fixed header on scroll
- [ ] Add the ability to scroll to the top of the page, when infinite scroll is enabled
- [x] Add Clarafai badge when displaying tags generated by Clarafai
---

**Comment by kgodey** [comment]
I made #169 and #170 for the remaining issues here and I'm closing this issue.
