### ISSUE TITLE
add image reuse survey to image page w attribution options

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#326]
Jane will assign to breno once this is final w/streamlined options

**Comment by janeatcc** [comment]
Please see email :)

**Comment by janeatcc** [comment]
hey @brenoferreira you're still working on adding this, right?

**Comment by janeatcc** [comment]
I realized there's no way to tell which image the responded surveys are for. is there a way to address this, e.g. add a referral link for the image reuse survey form? or am I missing something obvious?

**Comment by elharony** [comment]
Hi @janeatcc ,

I would like to help here. Can you please write more details about the follow-up issue after @brenoferreira ' Merged #341?

**Comment by janeatcc** [comment]
The issue is that we get responses from users who opt to fill out the image reuse survey, but the responses are not connected to the specific image or image page that the user is reusing or coming from. The data is more useful if we know which image they are telling us they reused. Is there a way to automate so we know which image they are filling out the form for, by either adding some kind of referral to the form link, or prefilling the form with the image page info?
