### ISSUE TITLE
add donate button

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#329]
in some form, post flip and post discussion

**Comment by kgodey** [comment]
Assigned to me to discuss with Jami.

**Comment by annatuma** [comment]
Taking this one off your hands @kgodey per upcoming initiative re web-based donations. It can remain in the backlog.

**Comment by annatuma** [comment]
Closing this per discussion, we'll have a whole separate push for improving web-based donations, starting with research, then UX design, prior to implementation. We'll start fresh with new tickets at that time, with full details of what we plan to do.
