### ISSUE TITLE
Display issues on small screens

### ISSUE THREAD

**Issue by ahmedkrmn** [creativecommons/cccatalog-frontend#333]
- On screens with width <= 401 pixels, the **About** and **Feedback** page buttons are shifted down the navigation bar. They are still clickable.

**_Home page:_**

![home](https://user-images.githubusercontent.com/20889958/56733109-7f7d8f80-675f-11e9-9d26-8f24c93ab6ea.gif)

---

**_Feedback page:_**

![feedback](https://user-images.githubusercontent.com/20889958/56732880-e0f12e80-675e-11e9-8955-ee5bf7fdfedd.gif)

---

**_About page:_**

![Screenshot (129)](https://user-images.githubusercontent.com/20889958/56732635-4f81bc80-675e-11e9-8502-de8526872ddc.png)

---

**Having a drop down menu with the two links that shown up on smaller screens would be a viable solution.**

---

- The old CC Search Portal link also overlaps with the CC logo on smaller screens.

![Screenshot (131)](https://user-images.githubusercontent.com/20889958/56733278-f87ce700-675f-11e9-9c1d-5b3006831b5b.png)

**Comment by brenoferreira** [comment]
Thanks for pointing this out. I fixed some of these issues on #323
