### ISSUE TITLE
Hide Mcccord on front end for now if issue isn't resolved in time

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#335]
See https://github.com/creativecommons/cccatalog-api/issues/274

if that isn't resolved in time for flip, please hide on front end:

/about
in search results
in provider drop-down

**Comment by kgodey** [comment]
@janeatcc Alden and I discussed and we can't resolve the McCord issue in time for the flip because reindexing the data would take too long.

**Comment by janeatcc** [comment]
ok then let's hide
