### ISSUE TITLE
svg icons collecting same data as buttons?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#337]
@aldenstpage can you confirm this is the case? eg. see new html embed in dev: https://ccsearch-dev.creativecommons.org/photos/222394df-46ae-4c3e-9a06-dfa02afecdcf

**Comment by janeatcc** [comment]
Are we collecting analytics on https://ccsearch-dev.creativecommons.org/static/img/cc-by_icon.svg ?

**Comment by aldenstpage** [comment]
It needs to be embedded somehwere for me to test it - let's see
![cc-by](https://ccsearch-dev.creativecommons.org/static/img/cc-by_icon.svg)

**Comment by aldenstpage** [comment]
Yes, we can see where the images are embedded
