### ISSUE TITLE
"verify at source - Flickr" change on dev

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#339]
Change to "Verify at the source: Flickr"

And can only the source, e.g. Flickr, be hyperlinked? 

The dash "-" makes it seem like an afterthought.

**Comment by elharony** [comment]
Did @brenoferreira fix it? If not, please let me know, and I will fix it today.

**Comment by elharony** [comment]
Hi @janeatcc ,
Did @brenoferreira fix it? If not, please let me know, and I will fix it today.
