### ISSUE TITLE
Overlapping images after "Prevent Overscaling" is unchecked 

### ISSUE THREAD

**Issue by ahmedkrmn** [creativecommons/cccatalog-frontend#343]
After checking the "Prevent overscaling" option and unchecking it again, the search results overlaps. Here's a gif that shows the bug.

![prevent overscalling2](https://user-images.githubusercontent.com/20889958/56808644-42ce9880-6832-11e9-82b4-f27e157c7915.gif)

Tested on: Chrome & Edge

**Comment by janeatcc** [comment]
This is a duplicate of https://github.com/creativecommons/cccatalog-frontend/issues/264 so closing but referencing there bc it's a great gif :)
