### ISSUE TITLE
wrong url for CC0

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#345]
see https://ccsearch-dev.creativecommons.org/photos/75abec02-d1db-4d5f-90ee-cece6c2491ba

wrong url for cc0 in linked text, should be https://creativecommons.org/publicdomain/zero/1.0/?ref=ccsearch

**Comment by elharony** [comment]
Hi @janeatcc ,

I reviewed this bug, and I've found the root of this issue & submitted a PR to solve it.
Looking forward to @brenoferreira 's review! 📝

**Comment by brenoferreira** [comment]
@aldenstpage fixed it on https://github.com/creativecommons/cccatalog-api/issues/289
