### ISSUE TITLE
GA referral links are the same but should be different?

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#346]
GA referral links should be different for rich text attribution vs html attribution in order for us to track which was used, right @aldenstpage ?

see https://ccsearch-dev.creativecommons.org/photos/75abec02-d1db-4d5f-90ee-cece6c2491ba for example

both attributions use "?ref=ccsearch" but should be something like:

Rich text: https://creativecommons.org/licenses/by/4.0/?ref=ccsearch&atype=rich 
Html: https://creativecommons.org/licenses/by/4.0/?ref=ccsearch&atype=html

**Comment by aldenstpage** [comment]
That's right, if you want to track different attribution types the referer query string will have to be different

**Comment by janeatcc** [comment]
ok @brenoferreira please change Monday :)
