### ISSUE TITLE
redirect https://ccsearch.creativecommons.org/ to search.cc.org

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#359]
currently doesn't direct to anything

**Comment by kgodey** [comment]
@janeatcc I set this domain redirection up last night and `https://ccsearch.creativecommons.org/` is redirecting to `https://search.creativecommons.org/` for me. could you try a hard refresh and see if that works?

**Comment by janeatcc** [comment]
yes, working now!
