### ISSUE TITLE
Make the dropbox options more obvious, perhaps with a checkbox

### ISSUE THREAD

**Issue by mattl** [creativecommons/cccatalog-frontend#361]
![image](https://user-images.githubusercontent.com/33296/56978617-e925e100-6b45-11e9-97be-cdbdb0670282.png)

It's really not clear that these are multiple choice options.

**Comment by hankolsen** [comment]
Drop downs should generally not be used when there are only two option. Go for checkboxes instead.

"In General, Avoid Drop-Downs When There Are More Than 10 or Fewer Than 5 Options"
Source: https://baymard.com/blog/drop-down-usability

**Comment by akowtko** [comment]
Have you thought about using Vuetify components? They have a `v-select` component ([here](https://vuetifyjs.com/en/components/selects) that allows for multi-select and has checkboxes inside the dropdown to make it clear that it is multi-select. The downside is the component follows material guidelines and therefore wouldn't match as well with the rest of your components.
<img width="366" alt="Screen Shot 2019-10-07 at 8 29 29 AM" src="https://user-images.githubusercontent.com/9166875/66325723-99a9c500-e8dc-11e9-8bdc-fbd4b10db247.png">

**Comment by annatuma** [comment]
Thanks everyone for the discussion and suggestions! @brenoferreira has implemented collapsible filter sections, using check boxes, in an upcoming design and functionality change. This is currently being tested in our [dev environment,](https://ccsearch-dev.creativecommons.org/search?q=dog&li=&lt=&categories=&extension=&aspect_ratio=&size=&provider=&searchBy=) and will be live soon.

![checkbox filtering](https://user-images.githubusercontent.com/3051816/69987474-323b7a80-1505-11ea-99da-617960b92f10.png)

Closing this ticket now.
