### ISSUE TITLE
Not enough space between search box and title

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#362]
See screenshot.
![CC Search](https://user-images.githubusercontent.com/287034/56991090-dc64b580-6b64-11e9-95b0-02ac0c1859e6.png)

**Comment by nishantsethi** [comment]
Working on this.

**Comment by elharony** [comment]
I suggest to keep it on the right side of the `navbar` & decrease the `Search` input's `width`... Until we reach the small screens, at that point; Keep it below the links. (With the `navbar` background)
