### ISSUE TITLE
no data result for CAPL even though it says image are available

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#368]
https://search.creativecommons.org/search?q=flower&provider=CAPL&li=&lt=&searchBy

![image](https://user-images.githubusercontent.com/6394777/57041573-7422dc00-6c17-11e9-9ede-20fc875743c5.png)

might be same as https://github.com/creativecommons/cccatalog-api/issues/280 but not sure

**Comment by aldenstpage** [comment]
That's weird. They show up in the API, see here - http://api.creativecommons.engineering/image/search?q=flowers&provider=CAPL.

It's not the same as #280 IMO
