### ISSUE TITLE
License filter order and presentation

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#37]
The order in the license filter dropdown seems random. Any reason why this is so and not in order of most liberal to most restrictive?

Also, the filter is all lower case initials, e.g. "by-nc-nd" without any explanation. Maybe better to experiment to see what resonates with users... do users understand the initials? Would it be better if it read "CC BY-NC-ND" for example? or alternatively, "Attribution-Noncommercial-NoDerivatives"?

**Comment by sebworks** [comment]
@janeatcc, the licenses are now listed in alphabetical order. Please let me know if that works. If you have more precise ideas about the language then please let me know.
