### ISSUE TITLE
footer is too big on iPad

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#370]
asking for version and a screenshot from user

**Comment by janeatcc** [comment]
![image1](https://user-images.githubusercontent.com/6394777/57051053-6b8cce80-6c34-11e9-89ec-f7338cac1530.png)

**Comment by brenoferreira** [comment]
Do we know what specific iPad this is? iPad mini? iPad Pro?

**Comment by janeatcc** [comment]
It’s an iPad Air 2

**Comment by elharony** [comment]
After fixing the footer' responsiveness, I am sure this problem has been fixed, as the footer stretched out.
Is that still exist, @brenoferreira , @janeatcc ? If so, please let me know & I will work on it (Sadly, don't have an iPad to test it myself, but it works perfectly fine via the Dev Tools).

**Comment by janeatcc** [comment]
@kgodey I assigned you the fresh desk ticket to follow up with after @brenoferreira figures it out. thanks!

**Comment by elharony** [comment]
Hi @janeatcc ,

Is that issue still exists?

**Comment by brenoferreira** [comment]
Tested on an iPad Air 2 and it's working ok. This is fixed in the latest release
