### ISSUE TITLE
Fix logo appearance on the footer

### ISSUE THREAD

**Issue by elharony** [creativecommons/cccatalog-frontend#372]
There's a responsive issue with the `logo` at different screen resolutions, it gets minimized/compressed/gets narrower (don't know the exact word to describe it). But I believe the screenshots will explain it:

640px - 790px
![640-790--before](https://user-images.githubusercontent.com/16986422/57048444-47e97880-6c74-11e9-8320-1141fcff4b47.png)

830px - 1150px
![830-1150--before](https://user-images.githubusercontent.com/16986422/57048447-4ae46900-6c74-11e9-9d0f-46f2db4a5417.png)

**Comment by janeatcc** [comment]
Is this issue related to this one? https://github.com/creativecommons/cccatalog-frontend/issues/370

**Comment by elharony** [comment]
Somehow, it is.

But I am not 100% sure that it will fix #370 , so maybe we can re-test the website after merging #371 to double-check that it works fine.
