### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by amazzoccone** [creativecommons/cccatalog-frontend#373]
It improves and increases the usability of the platform having it in multiple languages, apart from encapsulate texts in jsons.

We could implement https://github.com/kazupon/vue-i18n , migrating the hardcoded texts in phases to i18n. Once we have the whole site using it, we are able to add languages.
I think it's a long job, but easy and without risk of mistakes and the prize is that people from many countries could start using the website.

**Comment by janeatcc** [comment]
I would like to ask for feedback on this at the global summit during State of CC Search as well! https://sched.co/MhKv

**Comment by amazzoccone** [comment]
Sure @janeatcc . I'd like to hear about that feedback after the summit 🙌

**Comment by amazzoccone** [comment]
Any news on this @janeatcc ?

**Comment by janeatcc** [comment]
Just back this week from vacation and I'm collecting and synthesizing feedback soon. Will keep you posted!

**Comment by janeatcc** [comment]
So I think right now the plan is to depend on the translation infrastructure for cc.org, which is being revamped.

**Comment by AyanChoudhary** [comment]
Is this issue workable? if so I would like to start working on this.

**Comment by AyanChoudhary** [comment]
@janeatcc @kgodey @annatuma @amazzoccone ^

**Comment by kgodey** [comment]
We plan to do this as part of a GSoC/Outreachy project, so we aren't planning on working on it until the official internship period.

**Comment by akmadian** [comment]
Linking #488 because we're going to work on this in the internship period

**Comment by brenoferreira** [comment]
This is better described in #487
