### ISSUE TITLE
Educate users better on how to get more accurate results for search.

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#376]
Ideas:
- if people search two or three times rapidly, show a "Can't find what you're looking for? Here's some tips." type message that links to an explanation on how to use search features like AND and NOT and double quotes.

**Comment by elharony** [comment]
Great idea!

I would like to implement such a feature, but I wonder; How can I determine a `similar` search term? It has to be done via the Database (i.e. `LIKE`). Maybe we can add it to the API in case it returns nothing, and displays those `similar` terms on the Front end?

**Comment by kgodey** [comment]
@elharony that is a good idea but I think that's best done in a separate ticket. This ticket is just to explain the search options we already have. [Here's the API pull request](https://github.com/creativecommons/cccatalog-api/pull/211) which added Lucene style syntax and [here's documentation of the syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).

Feel free to make the new ticket for similar search terms!
