### ISSUE TITLE
Untitled media files could be presented better

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-frontend#383]
Some media have no title. This is now shown as "" by <X>, etc.

This might be presented differently e.g. call them untitled.

example:

https://search.creativecommons.org/photos/bf5e2ee6-6c9e-4689-956d-3a6ab5ea0c0d

**Comment by Dharmesh-Poddar** [comment]
@mzeinstra can I work on it..

**Comment by kgodey** [comment]
@Dharmesh-Poddar sure go ahead
