### ISSUE TITLE
Lower opacity on license icons in the HTML code of image attribution and also no space between image name and "by" in rendered attribution.

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#400]
**Describe the bug**
The HTML code for image attribution that the user can copy has a permanent `opacity:.7` in license icons style.
Also, there is no space between "image title" and the rest of the attribution sentence in the HTML code.
Please check the screenshots below. 

**To Reproduce**
1. Go to https://search.creativecommons.org/photos/6063b102-9445-47e5-b3a3-007d930dd4cd
2. Copy attribution HTML code.
3. Check on any online HTML editor.

**Expected behavior**
Aesthetically full opacity would look better. 

**Screenshots**

![imageedit_1_8376553434](https://user-images.githubusercontent.com/34679965/59407582-4c569480-8dcf-11e9-9b19-8d1afef640b1.gif)

_rendered HTML_
![Screenshot from 2019-06-13 11-18-14](https://user-images.githubusercontent.com/34679965/59407598-5a0c1a00-8dcf-11e9-8e77-497b63f372ec.png)

**Desktop (please complete the following information):**
 - Browser: chrome

**Comment by krysal** [comment]
Hello! I'm an Outreachy applicant, can I start contributing with this issue? :)
