### ISSUE TITLE
CC0 image attribution could be improved 

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-frontend#410]
example CC0 image provides a rich text that is not common practice in current set up. It states licensed under CC CC0 1.0 where CC0 1.0 would suffice.

e.g. https://search.creativecommons.org/photos/8a49e425-752a-4c20-afa1-0e10a1ae11e6

provides rich text attribution: 
`"Tractor Marks in a Field of Grass" by Image Catalog is licensed under CC CC0 1.0`

I would suggest removing the first CC and changing the template to just CC0:

`"Tractor Marks in a Field of Grass" by Image Catalog is licensed under CC0 1.0`

**Comment by brenoferreira** [comment]
This is fixed in #447 and is already in production
