### ISSUE TITLE
Link to CC.org should open in a new tab

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#412]
Link in "Learn more about CC licenses here." on the homepage should open in a new tab/window so that the user doesn't have to navigate back to CC Search after learning about the licenses.

**Comment by realJema** [comment]
Hello
Am a Newcomer and I will like to work on this issue

**Comment by kgodey** [comment]
@realJema go ahead!

**Comment by geekayush** [comment]
@kgodey @realJema Still open? I would like to contribute.

**Comment by kgodey** [comment]
@geekayush go ahead!
