### ISSUE TITLE
Allow users to report problematic content

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#425]
See https://github.com/creativecommons/cccatalog-frontend/issues/848

Look at **Frontend Functionality - Reporting UI**

The frontend functionality should use components from Vocabulary. The [wireframe](https://app.moqups.com/OD23yiSWK9/edit/page/a3da463b6) shows content and layout, not style.

**Comment by SomtochiAma** [comment]
How can I get started on this?

**Comment by kgodey** [comment]
@SomtochiAma This requires a design discussion. @annatuma – would you be okay with starting with a proposed design or would you like to do some product/ticket work on this first?

**Comment by annatuma** [comment]
We are starting with legal research and feature design beforehand. We'll post an update in the ticket when we're closer to having something to implement.

**Comment by annatuma** [comment]
Ticket description has been updated. This is now ready for work.

**Comment by annatuma** [comment]
Blocked until we transfer the wireframe from Moqups to Figma: https://github.com/creativecommons/cccatalog-frontend/issues/851

**Comment by panchovm** [comment]
The mockup has been updated. [Here is the link](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A335&viewport=45%2C154%2C0.06598864495754242) to see the flow. The ticket #851 is done
