### ISSUE TITLE
Build filter for image ratio

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#432]
We want to add a filter to CC Search, to allow users to filter by image ratio. The ratios we'd like to allow people to filter by are:
- Tall
- Wide
- Square
- Other

Users should be able to select one or more of these filters. When no ratio filter is selected (i.e. no option is checked), all ratio types should be shown.

This ticket will be preceded by [Create Left Hand Side Bar for Filters #529] (https://github.com/creativecommons/cccatalog-frontend/issues/529) and will be structured as indicated in [this wire frame] (https://app.moqups.com/OD23yiSWK9/view).

**Comment by aldenstpage** [comment]
What would an example of an 'other' ratio that doesn't fit into tall, wide, or square?

**Comment by brenoferreira** [comment]
Fixed in #533
