### ISSUE TITLE
Build filter for file type

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#433]
We want to add a filter to CC Search, to allow users to filter by file type, regardless of the content type. The types of file types we'd like users to be able to filter by at this stage are all image file types, as that is the only content type we currently have ingested. However, we'll need to build this filter in such a way that is dynamically updates, if possible, as new file types are added to the catalog.

Initial file types are:
- png
- jpeg

Users should be able to select one or more of these file type filters. When no file type filter is selected (i.e. no option is checked), all file types should be shown.

This ticket will be preceded by [Create Left Hand Side Bar for Filters #529] (https://github.com/creativecommons/cccatalog-frontend/issues/529) and will be structured as indicated in [this wire frame] (https://app.moqups.com/OD23yiSWK9/view).

**Comment by brenoferreira** [comment]
Fixed in #533
