### ISSUE TITLE
Build filter for filtering by type of image (illustration/vector/photo)

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#436]
We want to add a filter to CC Search, to allow users to filter by type of image. The types of images we'd like users to be able to filter by are:
- illustration
- vector
- photo
- digitized artwork

Users should be able to select one or more of these filters. When no image type filter is selected (i.e. no option is checked), all image types should be shown. If a user selects more than one filter, it is "or", i.e. we show them results for images that match any of the filters selected.

This ticket will be preceded by [Create Left Hand Side Bar for Filters #529] (https://github.com/creativecommons/cccatalog-frontend/issues/529) and will be structured as indicated in [this wire frame] (https://app.moqups.com/OD23yiSWK9/view).

**Comment by annatuma** [comment]
Moved from Sprint 2 to Sprint 3, tackling left hand side bar switch first.

**Comment by brenoferreira** [comment]
Fixed in #533
