### ISSUE TITLE
Allow users to report copyright content for removal

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#440]
e.g. CC-licensed images that contain corporate logos

**Comment by annatuma** [comment]
This is a feature/functionality related to:
https://github.com/creativecommons/cccatalog-frontend/issues/425

**Comment by DantrazTrev** [comment]
Hey @kgodey I would like to work on this

**Comment by kgodey** [comment]
This is not yet ready for work.

**Comment by annatuma** [comment]
The UI for copyright reporting and problematic content reporting are one and the same, and work will be tracked here: https://github.com/creativecommons/cccatalog-frontend/issues/425
