### ISSUE TITLE
Add a "recently added content" section to the site

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#442]

**Comment by mercyikpe** [comment]
Hello, is this task still available?
I'm interested in the task.

**Comment by kgodey** [comment]
@mercyikpe sorry, this is not available. We need to spec this out further before we can open it back up for contribution.

**Comment by annatuma** [comment]
We're not going to move forward with this feature in the immediate future, and perhaps not ever. Closing this out for now. If we do this at some point we'll start fresh with an outline of what we're thinking and the value it'll provide to users.
