### ISSUE TITLE
Feature "Contribute on GitHub" link or text in a more prominent place

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#443]

**Comment by krysal** [comment]
Hi Kriti, I don't see any "Contribute on GitHub" link in the [CC Search page](https://ccsearch.creativecommons.org/) should be added in the footer?

**Comment by kgodey** [comment]
@krysal Please feel free to submit a PR adding it to the footer, add a screenshot to the PR so that we can add any design feedback to the PR review.

**Comment by krysal** [comment]
Ok! I'll work on this.

**Comment by krysal** [comment]
@kgodey I made a proposal in a draft PR, please check if it's okay this way.
