### ISSUE TITLE
Provide explanation of why CC Search does not include same images as other sites like Google Images

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#466]
Potentially talk about what CC licenses are, explain that the images we show are from our partners/collaborators.

**Comment by annatuma** [comment]
I'd say that the About page addresses this to some extent:
https://search.creativecommons.org/about

That said, the About page is in need of a more substantial update, during which we can improve our explanation of what we index, and how it differs from other search engines. We shouldn't explain CC licenses on that page, but rather link to a page where they are explained. I'll create a separate ticket for this.

cc @sarahpearson
