### ISSUE TITLE
Make attribution requirement for using images clearer

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#467]
CC Search assumes a familiarity with the attribution requirement.

One example solution, something like what Font Awesome does, which happens once you click "Download".

![FA attribution](https://user-images.githubusercontent.com/287034/63287599-bd5f7000-c288-11e9-856f-e85628adf04c.png)

**Comment by annatuma** [comment]
The user experience for this is being tackled in Design Sprint 3 (tracked in Asana), and when it comes time to integrate that it'll involve other changes to the single result page. Closing this ticket.
