### ISSUE TITLE
Explain commercial use / allow modifications filters more thoroughly

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#468]
When people select buttons around commercial/modifications, we should make sure they understand what it means.

**Comment by annatuma** [comment]
In Design Sprint 3 we're adding tooltips to each license type, with better explanation, as well as adding explanations to single result pages. The integration of those designs will be tracked in standalone GitHub tickets. Likely happening early Q2 2020. Closing this ticket out.
