### ISSUE TITLE
Improve social metatags for images

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#472]
Right now, the image title and description do not show on social media, there is just a generic title and description for all images e.g. https://twitter.com/cc_opensource/status/1159905115647688704.

**Comment by edent** [comment]
I'm looking at this issue. What's the difference between `/index-server.html` and `/index.html`.

Looks like the metatags need updating in both, but I wanted to make sure I wasn't missing something.

**Comment by brenoferreira** [comment]
`/index-server.html` is used for server side rendering, which is used in our production environment

**Comment by brenoferreira** [comment]
This is done in #497
