### ISSUE TITLE
CC Search: HTML code doesn't show the image

### ISSUE THREAD

**Issue by claudioruiz** [creativecommons/cccatalog-frontend#476]
**Describe the bug**
Pasting the HTML code out of an image found in Search, the resulting code does not show the picture.

**To Reproduce**
I want to use this photo: https://ccsearch.creativecommons.org/photos/49a24211-cded-418f-a167-0e6a3fd04ebf

And using the HTML this is the result: https://publicdomain.community/
Metadata is shown, the picture is not. 

This is the HTML code:

`<p style="font-size: 0.9rem;font-style: italic;"><a href="https://www.flickr.com/photos/129816626@N04/21301240309">"Indians of North America - Pictorial Works"</a><span>by <a href="https://www.flickr.com/photos/129816626@N04">ElusiveMu.se</a></span> is licensed under <a href="https://creativecommons.org/licenses/PDM/1.0/?ref=ccsearch&atype=html" style="margin-right: 5px;">CC PDM 1.0</a><a href="https://creativecommons.org/licenses/PDM/1.0/?ref=ccsearch&atype=html" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;opacity: .7;margin-top: 2px;margin-left: 3px;height: 22px !important;"><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc_icon.svg" /><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc-pdm_icon.svg" /></a></p>
`
I've checked on OSX in all my known browsers.

**Comment by kgodey** [comment]
Putting this in the next sprint because it seems like a major bug.

**Comment by brenoferreira** [comment]
This is not a bug. This is how it works. The HTML contains only the attribution, not the image itself.

Can we turn this into a feature request?

**Comment by Mavi05** [comment]
Can I work on this issue?

**Comment by kgodey** [comment]
@Mavi05 This is not labelled "help wanted" and is not suitable for outside contribution.

**Comment by Mavi05** [comment]
@kgodey ok, so are there any issues on which I can work? I'm new to this project.

**Comment by kgodey** [comment]
@Mavi05 look at issues tagged "help wanted": https://github.com/creativecommons/cccatalog-frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22 that are also not tagged "in progress"

Please read the contributing guidelines here: https://github.com/creativecommons/cccatalog-frontend/blob/develop/CONTRIBUTING.md

**Comment by annatuma** [comment]
This was done during Q4 2019 through another ticket. The HTML Code now includes the image as well, see for example:

https://search.creativecommons.org/photos/3474484f-f75c-45bd-85f7-0efa8678bc1a

<p style="font-size: 0.9rem;font-style: italic;"><img style="display: block;" src="https://farm1.staticflickr.com/3/3042355_c700071469.jpg" alt="Big Dog, Little Dog"><a href="https://www.flickr.com/photos/48889073020@N01/3042355">"Big Dog, Little Dog"</a><span> by <a href="https://www.flickr.com/photos/48889073020@N01">Onion</a></span> is licensed under <a href="https://creativecommons.org/licenses/by-nc-nd/2.0/?ref=ccsearch&atype=html" style="margin-right: 5px;">CC BY-NC-ND 2.0</a><a href="https://creativecommons.org/licenses/by-nc-nd/2.0/?ref=ccsearch&atype=html" target="_blank" rel="noopener noreferrer" style="display: inline-block;white-space: none;margin-top: 2px;margin-left: 3px;height: 22px !important;"><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc_icon.svg" /><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc-by_icon.svg" /><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc-nc_icon.svg" /><img style="height: inherit;margin-right: 3px;display: inline-block;" src="https://search.creativecommons.org/static/img/cc-nd_icon.svg" /></a></p>
