### ISSUE TITLE
Evaluate Github Actions CI

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#484]
Set up [Github Actions](https://github.com/features/actions) for our CI use and try it for CD as well.

For CI, it's probably simple as we need only automate:

* build
* tests
* linting

`npm install`, `npm run build`, `npm run test` and `npm run lint` are the commands you would need for that.

If possible, during build of PRs it would be interesting to see if the GH Actions supports moving the associated issue to the `In Progress` column of the [Active Sprint project](https://github.com/orgs/creativecommons/projects/7).

**Comment by coderbabu10** [comment]
can i take this up? @brenoferreira

**Comment by kgodey** [comment]
This ticket needs further definition before it can be opened for community contribution.

**Comment by brenoferreira** [comment]
@aldenstpage do you think it would be possible to automate the deployment of the frontend on this repo, or would it the ccsearch-infrastructure repo be more suitable for deployment automation with GH Actions there instead of here?
Assuming we do want to move away from Atlantis for deployment automation for the frontend

**Comment by aldenstpage** [comment]
When you say "automate the deployment", do you mean to production or dev? Or both? For production, as you know, we use Atlantis, but for dev, there's script (sort of a dirty hack) that continuously deploys the `dev` branch to ccsearch-dev.

It looks like Hashicorp has written a [GitHub Actions integration for Terraform](https://github.com/hashicorp/terraform-github-actions), so that looks like a desirable replacement for the dirty hack script for deploying to dev.

I want to avoid automatic deploys to production because that's going to inevitably blow things up once in a while.

**Comment by SaurabhAgarwala** [comment]
@brenoferreira @aldenstpage I can work on the CI part of this using GitHub Actions while the deployment part is discussed and finalized by you all. Later I can maybe work on that as well.

**Comment by brenoferreira** [comment]
@SaurabhAgarwala sure 👍

**Comment by brenoferreira** [comment]
@aldenstpage I didn't mean auto deploys to production (on a merge to master for example). But just triggering an automated deployment when I (or someone else) pushes a new release tag, so we don't have to manually trigger it with Atlantis. Sorry that I wasn't clear

**Comment by SaurabhAgarwala** [comment]
> Set up [Github Actions](https://github.com/features/actions) for our CI use and try it for CD as well.
> 
> For CI, it's probably simple as we need only automate:
> 
> * build
> * linting
> 
> `npm install`, `npm run build` and `npm run lint` are the commands you would need for that.
> 
> If possible, during build of PRs it would be interesting to see if the GH Actions supports moving the associated issue to the `In Progress` column of the [Active Sprint project](https://github.com/orgs/creativecommons/projects/7).

@brenoferreira I have added a workflow for CI which automates `build` and `lint` as specified. But won't we have to automate even `unit tests` in the CI?

Also, I explored the possibility of moving associated issues of a new PR to a specified column in a project as suggested by you. But following [this](https://github.community/t5/How-to-use-Git-and-GitHub/Github-projects-issues-and-pull-requests/m-p/30968#M8518) discussion, I found out that currently there is no direct way to achieve this. 

However, I find that there already exists a [project automation workflow](https://github.com/creativecommons/cccatalog-frontend/blob/develop/.github/workflows/project-automation.yml) for this repo, which adds any new issue to `Pending Review` column of Backlog project, and any new PR to `In Progress` column of Active Sprint project. The issue cards will be displaying the linked PRs in the card itself, but unfortunately, the PR cards don't display the associated issue with them.

**Comment by brenoferreira** [comment]
@SaurabhAgarwala yes. tests and linting should run on CI. Sorry that I forgot to add that to the issue description

**Comment by SaurabhAgarwala** [comment]
@brenoferreira No problem, I will update the PR now

**Comment by brenoferreira** [comment]
#882 doesn't seem to have worked properly https://github.com/creativecommons/cccatalog-frontend/actions

I still need to see why it isn't working.

@SaurabhAgarwala feel free to take another try

**Comment by SaurabhAgarwala** [comment]
@brenoferreira The workflow didn't work because it's configured to work for push and PRs only in the `master` branch. But I see that by default, all PRs are merged into the `develop` branch. I will make the required changes. I just want to know, are direct `push` also done to develop branch itself?

**Comment by brenoferreira** [comment]
Yes, CI needs to build PRs merged to `develop`, and commits on the `develop` and `master` branches themselves

**Comment by SaurabhAgarwala** [comment]
Okay, I will make the necessary changes soon.
