### ISSUE TITLE
Evaluate Typescript adoption

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#486]

**Comment by zackkrida** [comment]
Closing for now: 

## Notes: 

One of the main incentives for using Vue.js over React in the search project is that the developer experience of Vue favors developers coming from backgrounds in design, html, and css, whereas React fully embraces an everything-in-JavaScript paradigm better suited to full-time JavaScript engineers. The React paradigm is quite powerful, especially paired with TypeScript, but requires developers to be JavaScript specialists. It is very easy to cause performance issues or violate best practices in a React project, especially with the new-ish hooks apis.

This is all to say that, like React, TypeScript adds complexity that may be at odds with the contributor community of the project. This extra difficulty is worthwhile when the adoption of TypeScript prevents significant runtime bugs. Currently, we do have some TypeErrors in the production Sentry logs that may have been caught by TypeScript adoption. These issues do not appear to be critical to the uptime or stability of the application.

Interestingly, Vue 3 is set to release in Q3 of this year. They are adopting some new APIs that are more React-like in terms of the coding style and mental model, and aim to have improved TypeScript compatibility from the current Vue 2.x. 


## Primary reasons against:

TypeScript is complicated. Current tech choices and community suggest that we should avoid complexity.
We do not face significant technical problems that TypeScript would solve.
Many of the benefits of TypeScript to developer experience are already provided by IDEs like Visual Studio Code, WebStorm, etc.
