### ISSUE TITLE
Browse page issues

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#49]
- [x] Add a header (see main page issue)
- [ ] The roll-up script should show the correct attribution (see above) and use the CC icons if possible as well
- [x] Tooltip should appear when mousing over circle+ to say “add to list”
- [x]  Letterbox image format often crops the images so much that you can’t select one without clicking into it. That adds lots of clicks to the user to find the image they want. Ideally they should be able to see the whole image, or the significant majority of it.
- [x]  Results equally favour tags and author names. Eg., in the “nature” list, the sixth image is by someone named “nerdy by nature”. Can we favour tag results first, exclude author names from search, or make “search by author name” an advanced feature?
- [x]  Once you start scrolling down through results, the header quickly disappears, then immediately fades back in, but is no longer the full width of the page (Chrome desktop). 1) Not sure it needs to disappear/reappear, and 2) it should be the same width as the header bar
Issue: it’s unclear that the word for the search is editable in the top left after selecting a result, so when you click the search icon and nothing appears to happen, it’s confusing - UI needs to be clearer here

**Filters**
- [x] “Providers” should be “Collection” or “Archive” or something else -- the “provider” is the author, so it’s a bit confusing
- [x] “Museum of the Netherlands” should be “Rijksmuseum” or “Rijksmuseum NL”
- [x] No ability to select multiple repos
- [x] Licenses should be all-caps, and formatted as users usually see them:
CC BY, CC BY-SA, CC BY-NC-ND, PD, CC0, etc.
- [x] Is there a difference between the blank checkbox and “all”? If not, remove “all”
- [x] Add the “-” symbol or “no filter” in place of the blank space
- [x] Change “commercial” to “Commercial use permitted”
- [x] Change “modification” to “Modification permitted”
- [x] Change “all-cc” to “CC-licensed works only (no PD)”

Lists
- [x] When you add an item, the list pop-up appears, with no information on what it is.
- [x] You can’t click on the item in the list window to go to the detail page for it
- [x] When you close a list, it’s gone.

**Comment by sebworks** [comment]
> The roll-up script should show the correct attribution (see above) and use the CC icons if possible as well

I don't think we have the space to display the full attribution on the rollover.  I think we can add the icons to the image detail page, though.

> Results equally favour tags and author names. Eg., in the “nature” list, the sixth image is by someone named “nerdy by nature”. Can we favour tag results first, exclude author names from search, or make “search by author name” an advanced feature?

I think Alden adjusted the script as requested, I'll add a `author names` text box to the filters.

> Tooltip should appear when mousing over circle+ to say “add to list”

This is a good idea for desktop, but it won't work on mobile. I'll add it for the desktop.

> Letterbox image format often crops the images so much that you can’t select one without clicking into it. That adds lots of clicks to the user to find the image they want. Ideally they should be able to see the whole image, or the significant majority of it.

Yeah, some images are being cropped to maintain their aspect ratio and grid uniformity. I'll come up with a better solution.

**Comment by sebworks** [comment]
> Letterbox image format often crops the images so much that you can’t select one without clicking into it. That adds lots of clicks to the user to find the image they want. Ideally they should be able to see the whole image, or the significant majority of it.

I've added the ability view the total image in the grid. This gives the user the option to control their experience.

**Comment by kgodey** [comment]
I made #171 to track the remaining todo on this issue, closing this one.
