### ISSUE TITLE
Image Detail page issues

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#50]
- [x] License format should be CC BY, not CC by, also the photo attribution, and the output HTML, and the one click attribution 
- [x] Use the CC icons on the detail page to show license type as well
- [x] When I click zoom on the image, I get a different image:
- [ ] I don’t know what that little pop-up navigator thing is, but it’s confusing. I’d remove it.
Issue: No download link to get the image, or clear link to go to the source site. Have to intuit to click on the right link in the detail information.

**Comment by sebworks** [comment]
>> Use the CC icons on the detail page to show license type as well

I think it would make sense to use the icons on the image detail page, but not so much on the rollover. We can discuss it though.


>> I don’t know what that little pop-up navigator thing is, but it’s confusing. I’d remove it.
Issue: No download link to get the image, or clear link to go to the source site. Have to intuit to click on the right link in the detail information.

This is a good point, and we probably need to provide some user help in the form tooltips or the like.

**Comment by janeatcc** [comment]
Noting that we receive feedback from an additional user that right click to download was not intuitive, especially on Macs. So additional emphasis to adding a download button to download image.

**Comment by kgodey** [comment]
Made #172 to track remaining item, closing this.
