### ISSUE TITLE
Provide HTML code to allow CC Search to be embedded in other websites

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#505]
A user reached out and asked for an embed code similar to the [OASIS OER](https://oasis.geneseo.edu/about.php) search tool to embed CC Search into their own website.

**Comment by HAMZABoxer98** [comment]
can I work on this @kgodey  ?

**Comment by madewithkode** [comment]
Hi, @kgodey, I would love to work on this but i need better understanding of exactly how you'd love the project to be tackled. For instance, where do I add the HTML code? Do I make a separate new file for it? I await your response.

**Comment by kgodey** [comment]
Hi @madewithkode, this needs more definition before it's ready to be worked on. I suggest looking at one of the issues tagged "help wanted" instead: https://github.com/creativecommons/cccatalog-frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22

**Comment by madewithkode** [comment]
Alright!

**Comment by annatuma** [comment]
@panchovm noting that in Q2 (or possibly Q3, if other priorities arise) we'll need to work on what this sort of embed should look like, before it can actually be built.

**Comment by panchovm** [comment]
Perfect. It sounds an interesting feature.

**Comment by zackkrida** [comment]
I'm inclined to think this would be it's own project that uses the search api. I'm not sure it would ultimately live in this repository but the issue can stay here for now.
