### ISSUE TITLE
Support State Memory for Filter Collapsing

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#506]
During Q4, we are introducing additional filters to CC Search. We know we will be adding even more filters in the future, both for images and other content types. We are also changing how filters are presented, to be listed in a left hand side bar. [See issue 529] (https://github.com/creativecommons/cccatalog-frontend/issues/529).

At present, we are building the left hand side bar in such a way that filters are shown (i.e. the section is expanded) when the page is loaded. This is to ensure that users are aware of filters. However, as we expand to more filters being included in the side bar, we anticipate this becoming a frustrating user experience, especially for power users, who have filtered and collapsed/minimized the filter section on the results page.

## Proposed Implementation
We'd like to support session-based state memory for filter expansion/collapsing, meaning we'd remember when a user has chosen to expand or collapse the left hand filter side bar. When users reload or go back to the results page, the filter side bar will be in the state that they left them. The default for new sessions will remain expanded for now.

**Comment by annatuma** [comment]
Removing from Q4 Sprint 2, putting in general Q4 backlog. How we implement this is going to be impacted by the functionality we introduce with the left hand side bar for filters (https://github.com/creativecommons/cccatalog-frontend/issues/529).

**Comment by coderbabu10** [comment]
is this issue now available to work on?
@annatuma

**Comment by annatuma** [comment]
Apologies I missed your comment at the time, @Amankumar29 - in general I recommend looking for issues marked "help wanted".

As for this issue, we're going to be changing it. For individual filter sections within the filter side bar, we're going to test full (permanent) expansion and addition of scrolling: https://github.com/creativecommons/cccatalog-frontend/issues/909

For this issue, it should only focus on state memory for the filter side bar itself, i.e. if a user expands it, we should remember it is expanded, and vice versa.
