### ISSUE TITLE
Collect Search Rating Usage Data

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#518]
## Background
Earlier this year we rolled out Usage Data collection. [See ticket 426] (https://github.com/creativecommons/cccatalog-frontend/issues/426) for the full spec and catalog work, and [see ticket 428] (https://github.com/creativecommons/cccatalog-frontend/issues/428) for the front-end implementation.

When we rolled this out, we were missing "search rating usage data". Initially this was intended to be collected as a rating of 1-5, but upon further discussion we've opted to make this a yes/no option, where users can indicate if they found the search results to be relevant or not.

## Suggested Implementation
We'd like to implement this as a question at the bottom of the first load of search results, i.e. directly above "Load More" we want to ask users "Are these search results relevant to you?"

This ticket needs to be preceded by changes to the API, [see ticket 375] (https://github.com/creativecommons/cccatalog-api/issues/375) for full details.

**Comment by annatuma** [comment]
@brenoferreira @kgodey @sarahpearson please look at the "Suggested Implementation" above and chime in with your thoughts. I know we've discussed this pretty extensively but I don't believe we reached a conclusion on exact language and location.

We'll also review during the upcoming sprint planning call, if we don't get to this beforehand.

**Comment by annatuma** [comment]
We are going to wait on Francisco for feedback on how to design this into the frontend.

**Comment by annatuma** [comment]
We'll try to add this into Design Sprint 1. If we don't make it in time, it'll get pushed to Q2. Otherwise, last sprint of Q1.

**Comment by annatuma** [comment]
This is in Design Sprint 1, as a question to the right of the search bar. We'll close this ticket when the assets for search results page from Design Sprint 1 have been integrated.

**Comment by brenoferreira** [comment]
Fixed in #820
