### ISSUE TITLE
Bug: Facebook Social Sharing Text Doesn't Properly Populate.

### ISSUE THREAD

**Issue by akowtko** [creativecommons/cccatalog-frontend#519]
**Describe the bug**
When sharing an image on Facebook, the sharer text doesn't properly populate, defaulting to the `<meta name="og:description">` tag text because the Facebook sharer.php no longer accepts inputs. Facebook now generates images, titles, and descriptions for social sharing based on the meta tags. 

**To Reproduce**
1. Go to [https://search.creativecommons.org](https://search.creativecommons.org).
2. Enter something into the search bar and press enter.
3. Click on an image in the search results.
4. Click the `share` button below the image.
5. Click the Facebook avatar to share to Facebook.
6. A new tab will open but the description for the shared image is `Empowering the world...` instead of the correct wording listed above.

**Expected behavior**
When clicking the Facebook sharing link, the description for the shared image should be in the following format:

> "I found an image through CC Search @creativecommons: https://www.flickr.com/photos/biodivlibrary/9240505252" 

**Screenshots**
<img width="538" alt="Screen Shot 2019-10-18 at 5 00 35 PM" src="https://user-images.githubusercontent.com/9166875/67134831-09675c00-f1c9-11e9-8f72-91742d3420ce.png">

**Desktop:**
 - OS: MacOS 10.15
 - Browser: Chrome
 - Version: 77.0.3865.120 (64-bit)

**Additional context**
First brought up by @janeatcc in Issue https://github.com/creativecommons/cccatalog-frontend/issues/271

**Comment by DantrazTrev** [comment]
Is this issue still workable?

**Comment by kgodey** [comment]
Yes, this is still open.

**Comment by Alucard17** [comment]
@kgodey Can I work on this issue

**Comment by Alucard17** [comment]
@kgodey  Hi facebook social share fetches description from sites og:description meta tag of the webpage

**Comment by kgodey** [comment]
@Alucard17 go ahead and work on it.

**Comment by DantrazTrev** [comment]
Hey @Alucard17 are you still working on it?

**Comment by DantrazTrev** [comment]
Hey @kgodey can i take this up 
?

**Comment by coderbabu10** [comment]
can i take this up?

**Comment by DantrazTrev** [comment]
Hey @coderbabu10 I'm on this .
