### ISSUE TITLE
Create Left Hand Side Bar for Filters

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#529]
## Background
Currently, search filters on the CC Search results page are placed directly below the search bar, arranged horizontally, across the top of the page. The search bar is also the width of the page.

## Implementation
We'd like to change the overall layout of the CC Search results page as follows:
- Move all current filters to a left hand side bar
- Within left hand side bar, allow users to expand and collapse filter types
- Allow users to expand or slide out the left hand side bar
- Make Search Bar more clearly defined as a search bar, positioned to the right of the left hand side bar, i.e. no longer the full width of the screen
- Introduce a drop down filter within the Search Bar, to filter by content type. Examples of content type include Image, Text, Audio, Video, etc. While we currently only have images stored in the catalog, we'll support more content types in the future.

We want to maintain the "Refresh on selection" functionality that currently exists within filters, i.e. when a user selects or deselects a filter option, the search results automatically update.

The basic layout should resemble [these wire frames] (https://app.moqups.com/OD23yiSWK9/view), which are not pixel perfect.

As indicated in the wire frames, we need to anticipate future filtering being displayed in the left hand sidebar.

**Comment by annatuma** [comment]
Ticket is good to go, and has been discussed. Moving to Sprint 3 for @brenoferreira to tackle.

**Comment by Pep-DEV101** [comment]
Did #533 has solved this issue or i should give it a try

**Comment by brenoferreira** [comment]
@Pep-DEV101 #533 is currently in progress to fix this issue
