### ISSUE TITLE
Dismiss keyboard after search form submit on mobile

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#532]
On iOS, when the user types a search query and hits the search button on the home page, once the results page loads, the iOS keyboard is still visible, taking a lot of screen space and making the actual images not visible. We should dismiss the keyboard on the form submit event.

**To Reproduce**
1. Go to CC Search home page
2. Type in a search query term
3. Hit the search button or hit "Enter" on the keyboard
4. The results page should be visible along with the iOS keyboard

**Expected behavior**
The keyboard should be dismissed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS 13
 - Browser Safari

**Additional context**
Not sure if the same thing reproduces on Android and Chrome.

**Comment by krysal** [comment]
Hello, I confirm that the same occurs on Android and made a PR that fix it. I don't know if this solves the problem for IOS but I think it will fix it too.
