### ISSUE TITLE
Fix image count when result set is over 10K images

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#540]
There's been a change to the CC Catalog API in which a search query result set over 10.000 images will have a capped `result_count` of `10000`, when in reality there's more than 10.000 images in the catalog.  For example: https://api.creativecommons.engineering/image/search?q=cat

![Screen Shot 2019-12-04 at 10 44 24](https://user-images.githubusercontent.com/707019/70147711-98e6a280-1683-11ea-9dc4-83fc007aae3d.png)

We need to change the display of the image count in the UI, which now tells users that there are exactly 10.000 images, to something like `Over 10.000 images` or `More than 10.000 images` or `10.000+ images`.

**Comment by brenoferreira** [comment]
@annatuma which one do you think is best?

_Over 10.000 images_

_More than 10.000 images_

_10.000+ images_

Something else?

**Comment by kgodey** [comment]
Assigned to @annatuma to respond.

**Comment by madewithkode** [comment]
Hi there, I'd love to work on this issue.

**Comment by brenoferreira** [comment]
@madewithkode we're still deciding on the correct language here. Once we decide and we remove the `Question` label, you're welcome to work on this.

**Comment by annatuma** [comment]
This is more complex than it looks because the thousands separator varies by country and region. (See [examples](https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use). This is an opportunity to fix our previous styling with the thousands separator.

I suggest we go with the SI style, and refer to "results" rather than "images":
Suggested language: Over 10 000 results

We are only showing the first 10 000 results in these cases, correct?

@kgodey @brenoferreira let me know what you think of the suggested language.

**Comment by kgodey** [comment]
sounds good to me.

**Comment by kgodey** [comment]
Actually, since we're not localized yet and we use American English, maybe we should stick to the English separators since the rest of the UI is in English? Once we localize, we can support other separators based on the language of the UI. That seems most consistent to me.

**Comment by madewithkode** [comment]
> @madewithkode we're still deciding on the correct language here. Once we decide and we remove the `Question` label, you're welcome to work on this.

@brenoferreira Alright. Looking forward to the final decision.

**Comment by brenoferreira** [comment]
Yeah, since nothing is localised in CC Search, it's all American English, including numbers, I would say that it's not worth worrying about that at the moment. If we use `,` to separate decimals, let's continue using that and keep this ticket focused on the text for the result set over 10K images.

PS: There's already a ticket about localization, which should include localized numbers in CC Search: #487

**Comment by annatuma** [comment]
All valid points. Decimal separator it is, in keeping with American English conventions.

"Over 10,000 results" will be the new text then!

@madewithkode I believe this is ready to be worked on now.

**Comment by kgodey** [comment]
@madewithkode marked as "in progress" assuming you're still interested in working on it.

**Comment by madewithkode** [comment]
on it!

**Comment by madewithkode** [comment]
Was away for a while, currently on it.

**Comment by madewithkode** [comment]
Hey there, just so I'm cleared, I hope we all know that results below 10k currently appear as "<resultcount> images" where <resultcount> equals the number of fetched images. 
So if we're going to change the phrase for results over 10K to "Over 10,000 results" don't you think in pursuit of homogeneity, it's either "images" is entirely replaced with "results" or the latter replaces the former for results below 10K too. 
Looking forward to your feedbacks before I proceed.

**Comment by brenoferreira** [comment]
Good catch. I think we should keep it as `Over 10,000 images` for now
