### ISSUE TITLE
Implement homepage middle section search form redesigns

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#543]
Design: https://scene.zeplin.io/project/5dc5a56e81baec82fe6f7851/screen/5dcea00e442e0144a204e251

**Comment by AyanChoudhary** [comment]
can I take this issue?

**Comment by kgodey** [comment]
This issue is not marked "help wanted" and is not suitable for community contribution (and the description is a little out of date as well, we no longer use Zeplin).

**Comment by kgodey** [comment]
This is done.
