### ISSUE TITLE
Implement image search grid redesigns

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#544]
Designs: https://scene.zeplin.io/project/5dc5a56e81baec82fe6f7851 (Under `Results Page`)

**Comment by annatuma** [comment]
@brenoferreira additional minor language change here, from "All licenses" and "All sources" to just "Licenses" and "Sources", in the left hand filter. Screenshot attached of what I mean. Apologies this didn't get included in the designs.

**Comment by annatuma** [comment]
![Licenses and Sources](https://user-images.githubusercontent.com/3051816/71127069-eb5dae00-21af-11ea-97c2-4f2a3fffce26.jpg)

**Comment by coderbabu10** [comment]
the elements in sources are not being displayed in the main search grid. @brenoferreira

**Comment by Dhruvi16** [comment]
Hey! Can I take this up?
Thank you.

**Comment by akmadian** [comment]
@Dhruvi16 I would assume that since Breno is assigned to this issue, he is actively working on it. However, the assignment does seem to be pretty old. 

Pending approval from @annatuma, you may work on it, but please wait for Anna's approval before starting.

**Comment by Dhruvi16** [comment]
Sure I will wait for @annatuma's approval. Up till then, I will take up something else.
Thank you!

**Comment by annatuma** [comment]
After discussing, we're going to keep this to staff only, because there are some complexities around this ticket tied to our work on Vocabulary, which is still under active development. It'll remain assigned to @brenoferreira 

Thanks for your interest @Dhruvi16 - please continue to look at other tickets that are open to contribution.

**Comment by kgodey** [comment]
I added the label to all the other related issues too.
