### ISSUE TITLE
Implement image details page redesigns

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#545]
Designs: https://scene.zeplin.io/project/5dc5a56e81baec82fe6f7851 (Under `Single Results`)

**Comment by datbossg310** [comment]
> Designs: https://scene.zeplin.io/project/5dc5a56e81baec82fe6f7851 (Under `Single Results`)

![Results-collapsed](https://user-images.githubusercontent.com/55473434/71829066-a0b9ae00-3058-11ea-8e90-9f336a1d4222.png)

**Comment by datbossg310** [comment]
![Browsebycollection](https://user-images.githubusercontent.com/55473434/71829102-afa06080-3058-11ea-8ab0-29a571abea5b.png)

**Comment by datbossg310** [comment]
![SingleResult-attri-hover](https://user-images.githubusercontent.com/55473434/71829232-04dc7200-3059-11ea-86bd-19c9f8bc1623.png)

**Comment by datbossg310** [comment]
![Home-hover](https://user-images.githubusercontent.com/55473434/71829325-39e8c480-3059-11ea-8e69-29c9dfb3f676.png)

**Comment by coderbabu10** [comment]
sir,I would like to work on the Home Page,can you please assign me this issue?

**Comment by brenoferreira** [comment]
@coderbabu10 I think this isn't quite ready for development yet and will require a more unfinished work in other CC repositories, such as https://github.com/creativecommons/vocabulary.

But thanks for the initiative and feel free to browse through our Issues to see if there's anything else you feel like doing

**Comment by coderbabu10** [comment]
okay @brenoferreira

**Comment by DantrazTrev** [comment]
Hi @brenoferreira I would like to work on this

**Comment by kgodey** [comment]
This is not open to the community. See @annatuma's comment on https://github.com/creativecommons/cccatalog-frontend/issues/544
