### ISSUE TITLE
Migrate to Webpack 4

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#548]
While testing the changes in #531, I detected that the current Webpack 3 configuration uses many APIs that were deprecated in Webpack 4.

Instead of trying to fix these problems, it might be better and easier to just rewrite the webpack configurations from scratch, using Webpack 4 and its newer APIs and capabilities.

Remember that the build process must support app and vendor bundle splitting, Vue SSR, compiling SCSS to CSS, copying assets in the `assets/` dir, compiling source maps.

This article can be useful: https://medium.com/js-dojo/how-to-configure-webpack-4-with-vuejs-a-complete-guide-209e943c4772

This is related to #485 and both this issue and that one should probably be fixed together in one branch.

**Comment by AyanChoudhary** [comment]
Is this issue open to be worked on? if so I want to work on it. @brenoferreira @kgodey

**Comment by kgodey** [comment]
This was being worked on as part of https://github.com/creativecommons/cccatalog-frontend/issues/485. @Dhruvi16, I see your PR is closed, are you still working on this?

**Comment by Dhruvi16** [comment]
Hey! Apologies for the delay. But I closed this PR due to I had a lot of conflicts. Next, I am working on it but I am stuck with errors so I am trying to figure out how to solve them but that might take a little time. Is that alright? Or do I need to drop the issue? 
Thanks
Dhruvi

**Comment by kgodey** [comment]
@Dhruvi16 please work only on one issue at at time, if this is the one you're working on, feel free to go ahead. if not, I suggest dropping either this one or some of the others. It's up to you which one.

**Comment by Dhruvi16** [comment]
I will drop it then and work on the other issue.
Thank you.

**Comment by AyanChoudhary** [comment]
@kgodey If this is free, then I would like to work on this.

**Comment by kgodey** [comment]
@AyanChoudhary go ahead.

**Comment by kgodey** [comment]
@AyanChoudhary do you also want to work on https://github.com/creativecommons/cccatalog-frontend/issues/485 as part of this?

**Comment by AyanChoudhary** [comment]
yes sure

**Comment by kgodey** [comment]
okay, you'll need to comment on it before I can assign it to you.
