### ISSUE TITLE
OpenSearch.xml no longer working

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#553]
## Describe the bug
The following was reported by a user via FreshDesk:

I noticed that opensearch.xml has gone missing, making it more difficult to
install CC search as an engine in browsers that support this useful tech.
It is pointed to in the normal HTML, and it is present on GitHub:

https://github.com/creativecommons/cccatalog-frontend/blob/07f38b1e7c433b51f1b11ef0bb3a49b1329b1e67/static/opensearch.xml

But in production it gives an error:

https://ccsearch.creativecommons.org/static/opensearch.xml

**Comment by annatuma** [comment]
@brenoferreira @kgodey I'm not familiar enough with OpenSearch.xml to know what the background is here, or the expected behavior. Feel free to comment, update, etc. I'm putting this in the Current Sprint for now, with ticket work required, as we figure this out. If you deem it non-urgent we can place it in the Backlog too.

**Comment by datbossg310** [comment]
1 You need a UTF-16. For line 1

**Comment by datbossg310** [comment]
Fixed it

**Comment by Jaxom99** [comment]
I also have seen this, it's sad because I don't want to install the CC add-on, but still keep the tool at hand in my browser's search options.
Thanks for your work !

**Comment by hjhimanshu01** [comment]
Hello, I am interested in contributing to creative commons, found out that `opensearch.xml` is there in the repository but not accessible through the link provided in `index.html` file, the `static/img` path is defined for `src/assets` folder, so a suggestion would be to place the opensearch file in the src folder which can be made accessible.

**Comment by brenoferreira** [comment]
Feel free to open a pull request with a fix if any of you feel inclined to doing so :)

**Comment by annatuma** [comment]
Requires tests in production. Assigning to @brenoferreira

**Comment by brenoferreira** [comment]
This is fixed in #571
