### ISSUE TITLE
There is no script for dev-insecure

### ISSUE THREAD

**Issue by aryamanpuri** [creativecommons/cccatalog-frontend#560]
Whenever a person is running  ` npm run dev-insecure` on the terminal to run the project , , it gives an error of missing script .
There is no script for insecure building of the project.

**Comment by aryamanpuri** [comment]
@brenoferreira

**Comment by brenoferreira** [comment]
We can remove it from the docs.

**Comment by aryamanpuri** [comment]
@brenoferreira should I make pr for this

**Comment by kgodey** [comment]
go ahead @aryamanpuri

**Comment by DantrazTrev** [comment]
Hey @aryamanpuri are you working on this?

**Comment by aryamanpuri** [comment]
@DantrazTrev Yes I will do it today .

**Comment by DantrazTrev** [comment]
Is this issue still open ?

**Comment by kgodey** [comment]
This is done.

@coderbabu10 please put "Fixes #<issue-number>" in future PR descriptions so that linked issues will automatically close.
