### ISSUE TITLE
Rework CC Search "About" and "Feedback" pages

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#562]
We need to:

1) Improve the overall design of these pages
2) Provide a better explanation on the About page of the distinction between e.g. Google Image Search and CC Search, and why CC Search doesn't have every image on the internet in it
3) Add to the Feedback page more information on how to get involved
4) Update links to forthcoming blog article about CC Search

**Comment by coderbabu10** [comment]
I would like to work on this issue please assign me.

**Comment by annatuma** [comment]
As discussed in Slack, this needs more details and work from us before it's ready to be worked on. I recommend looking at "help wanted" issues instead:
https://github.com/search?q=org%3Acreativecommons+is%3Aopen+label%3A%22help+wanted%22

**Comment by Vineet-Sharma29** [comment]
Is this issue workable now? Would like to work on it

**Comment by akmadian** [comment]
@Vineet-Sharma29 Only issues marked as help wanted are open for people to work on. Please take a look at [issues marked as `help wanted`](https://github.com/search?q=org%3Acreativecommons+is%3Aopen+label%3A%22help+wanted%22)
