### ISSUE TITLE
Bottom To Top Button

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#565]
We can add a bottom to top button in feedback at right side in the end,as it will be easy for the user to directly go up.

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by AmanR28** [comment]
Can I work on it?

**Comment by coderbabu10** [comment]
@AmanR28 As it is under observation you can check out other issues with label as help wanted

**Comment by brenoferreira** [comment]
Thanks for the suggestion, but after evaluating, we decided that the feedback page doesn't need this button, as the user won't need to scroll up that much.
