### ISSUE TITLE
search bar error 

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#566]
the search bar is getting out of the navbar while resizing.

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by aashimgarg** [comment]
i want to solve this issue @coderbabu10

**Comment by brenoferreira** [comment]
@coderbabu10 Can you post a GIF or screenshot showing this problem? It's hard to know what exactly is wrong with the description provided here

**Comment by AyanChoudhary** [comment]
@coderbabu10 @brenoferreira if this is not yet assigned can I take this?

**Comment by coderbabu10** [comment]
this issue is closed as pr #567  is merged
