### ISSUE TITLE
adding hover in Footer

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#572]
**We can add a hover effect for contact,privacy,policies and terms in footer as it will look more attractive and add change the border bottom color to white for "we'd love to hear from you" line .** 

![Screenshot from 2020-01-31 00-31-04](https://user-images.githubusercontent.com/54955755/73481059-0af81100-43c1-11ea-8a69-5630dec1937b.png)

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by soumyajit1729** [comment]
May I wok on this issue?

**Comment by coderbabu10** [comment]
as pr#573 sent for the same you can try other issues @soumyajit1729 
Thank you

**Comment by coderbabu10** [comment]
@brenoferreira please look for this issue sir.

**Comment by brenoferreira** [comment]
The footer is getting a small redesign and we're not making any changes to it at the moment.
