### ISSUE TITLE
Masonry layout width overflow issue on "Load More"

### ISSUE THREAD

**Issue by nilshah98** [creativecommons/cccatalog-frontend#574]
## Describe the bug
- Initially when searching for something on `ccsearch` the masonry layout displays them perfectly.
- Even when removing and adding the filter sidebar doesn't break the layout
- But if I remove the sidebar, then click `Load More` option, it loads new images in the extra width as well
- And when I activate the filter sidebar after `Load More`, I get an overflow in x direction

## To Reproduce
1. Go to 'https://ccsearch.creativecommons.org/'
2. Search for anything in the search bar. Ex: `happy`
3. Remove the filter sidebar, by clicking the `filter` icon beside `search` icon
4. Scroll to the bottom of the page, and click `Load more`
5. Scroll to the top and click the `filter` icon again

## Expected behavior
- I think there should be no overflow in the x-direction, since there is already scrolling in y-direction as well, which makes it inconvenient

## Screenshots
**Initially with sidebar on**
![image](https://user-images.githubusercontent.com/22821480/73633844-b0430b80-4685-11ea-9c37-2722ae589436.png)

**Initially with sidebar off**
![image](https://user-images.githubusercontent.com/22821480/73633855-b802b000-4685-11ea-8788-00c5c7597ebf.png)

**Scroll to bottom and click `Load More`**
![image](https://user-images.githubusercontent.com/22821480/73633872-c8b32600-4685-11ea-9288-2f0cfeef003a.png)

**Activate sidebar after `Load More`**
![image](https://user-images.githubusercontent.com/22821480/73633934-f0a28980-4685-11ea-984d-6d71bd111f18.png)

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Google Chrome
 - Version: 78.0.3904.108

## Smartphone (please complete the following information)
*Haven't tested*
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
If this really is a bug, I would like to take this up.
Also, if any additional information like where the files for the masonry layout can be found, it would be really helpful

**Comment by nilshah98** [comment]
I would like to take this up @brenoferreira.

**Comment by kgodey** [comment]
Go ahead @nilshah98

**Comment by nilshah98** [comment]
In the new masonry layout this issue is resolved.
It actually looks pretty good and slick with the new `Vocabulary` components, great work!

**Addendum:**
- Worked on this issue before the new `Vocabulary` components were added.
- Realised that [`vue-masonry`](https://github.com/shershen08/vue-masonry) was bound to it's parent container width, and even if that container width changed, the masonry-grid width wouldn't change.
- On further introspection realised that the `resize` event or update event isn't being called in DOM, since we are using `display:none` and not actually making changes to the size of the components.

Alternative solution could have been to slide the sidebar out, and actually cause a layout change to trigger the event.

**Comment by kgodey** [comment]
Thanks @nilshah98! Should we close this?

**Comment by nilshah98** [comment]
Yep, we can close this.
