### ISSUE TITLE
Fix sidebar location on scroll

### ISSUE THREAD

**Issue by nilshah98** [creativecommons/cccatalog-frontend#575]
## Problem Description

- When scrolling through search results, there is a `go-to-top` button which will take you to top to change your query or anything.
- I suppose the major reason for implementing this, against implementing search bar top fixed is to create more space for the images to fit in
- But while scrolling down, the space to the left occupied by the sidebar still exists and it is completely blank, so why not occupy it?

## Solution Description

- I propose to keep the sidebar location fixed, so that the `filters` are actually visible even after scrolling, and not just white-space there

## Alternatives

- None

## Screenshots
**Initially**
![image](https://user-images.githubusercontent.com/22821480/73636914-04052300-468d-11ea-9f7f-bad5fa1617ae.png)

**After Scrolling**
![image](https://user-images.githubusercontent.com/22821480/73636927-0c5d5e00-468d-11ea-9551-4bdce3069587.png)

The sidebar is completely white and empty, rather have filters over there.

## Additional context

- I would like to take up this feature (issue), if it is accepted.
- Additionally, I really feel a `search` bar fixed to the top after scrolling a bit will be helpful. Atleast in larger screens it will be helpful and more intuitive as opposed to the current `go-to-top` button. Let me know about this.

**Comment by annatuma** [comment]
@nilshah98 feel free to take this up. We've discussed with @brenoferreira and @panchovm and it makes sense to have the fixed search bar at the top, and fixed filters on the left. We will be making some changes to the styles of those in future sprints, but making them fixed will remain part of the design.

**Comment by nilshah98** [comment]
Will put in a PR for this in the coming week.
Thanks @annatuma

**Comment by nilshah98** [comment]
Hey, fixed siderbar and searchbar has been implemented and referenced in PR #596 

This might be out of line, but I have a few suggestions-
- To omit a fixed searchbar up top, as we already a `back-to-top` button.
- Also, the fixed search bar at the top just uses a lot of space, which can be rather used to display more of the images.
- Whereas an alternative is to remove the `back-to-top` button since there's little use for it left.
