### ISSUE TITLE
Search input not visible in the search bar

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#581]
## Describe the bug
When I type anything in the search bar present on the navigation header, it is not visible. Refer to the GIF below.

## To Reproduce
1. Go to https://search.creativecommons.org/about
2. Type something in the search bar
3. See error

## Gif
![ezgif com-crop (1)](https://user-images.githubusercontent.com/34679965/74150781-a9416d80-4c30-11ea-8b85-6efc469581e3.gif)

## Desktop (please complete the following information)
 - OS: Ubuntu 19.10
 - Browser: chrome Version 79.0.3945.130

## Additional context
I have also noticed that the search bar is present in the navigation header on all the pages except https://search.creativecommons.org/collections

**Comment by coderbabu10** [comment]
can i take this up?
@makkoncept

**Comment by makkoncept** [comment]
@coderbabu10 you can ask @kgodey or @brenoferreira

**Comment by coderbabu10** [comment]
can i take this up @brenoferreira

**Comment by brenoferreira** [comment]
Thanks for spotting this, but this problem is already fixed in #589
