### ISSUE TITLE
spell error: "source" -> "license" in syntax guide

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#582]
## Screenshot

![drawisland](https://user-images.githubusercontent.com/34679965/74152084-8bc1d300-4c33-11ea-8b8d-ad1d8473b9be.png)

## To Reproduce
1. Go to https://search.creativecommons.org/search-help
2. See error

**Comment by coderbabu10** [comment]
can i take this up?

**Comment by coderbabu10** [comment]
#583

**Comment by brenoferreira** [comment]
This was fixed in #584
