### ISSUE TITLE
Share on Pinterest is broken

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#590]
## Describe the bug
"Sorry, this image is broken. Please pick a different image" is the message shown when trying to share an image on Pinterest from CC Search.

## To Reproduce
1. Go to https://search.creativecommons.org/photos/7e5b0a9e-47c9-4a0e-829e-915542010c19
2. Under the share tab, click on the pinterest icon.

## Screenshots
![Screenshot from 2020-02-12 23-10-36](https://user-images.githubusercontent.com/34679965/74361862-a2ac2500-4ded-11ea-852c-9e7920496ef4.png)
![Screenshot from 2020-02-12 23-10-40 (1)](https://user-images.githubusercontent.com/34679965/74361867-a3dd5200-4ded-11ea-80ad-80696aa8425f.png)

## Desktop (please complete the following information)
- OS: Ubuntu 19.10
- Browser: chrome Version 79.0.3945.130

**Comment by coderbabu10** [comment]
can i work on this? @brenoferreira

**Comment by kgodey** [comment]
go ahead @coderbabu10

**Comment by coderbabu10** [comment]
okay @kgodey

**Comment by DantrazTrev** [comment]
Can I take this issue @makkoncept ?

**Comment by coderbabu10** [comment]
@DantrazTrev i am working on this issue you can find other issues which are open 
Thank you

**Comment by Shobhan99** [comment]
Hey can I work on this issue?

**Comment by coderbabu10** [comment]
hey @Shobhan99 right now i am working on this issue you can find other issue which ar open and having tag with help wanted

**Comment by DantrazTrev** [comment]
Hey @coderbabu10 are facing any issue solving this?

**Comment by Officialkome** [comment]
Hello, has this issue been resolved? I am from Outreachy, I would like to work on this if its not resolved yet

**Comment by Kirti2502** [comment]
Hi, I am an Outreachy applicant. Can I take up this issue @makkoncept ?

**Comment by Shobhan99** [comment]
@coderbabu10 has been assigned this issue since a week now and hasn't solved it. He isn't letting others take the issue.

**Comment by coderbabu10** [comment]
hey @Shobhan99, me and @akmadian were discussing about the same for last few days and right now i am working on the suggestion given by him. :)
Thank you.

**Comment by Abhishek856** [comment]
can i work on this issue

**Comment by akmadian** [comment]
Yep, @coderbabu10 and I have been discussing how to proceed with this issue privately and publicly for a little while now. He is still actively working on it so this issue will stay assigned to him. Thanks for all of the interest, though :)

cc: @Officialkome, @Kirti2502, @Shobhan99, @Abhishek856
