### ISSUE TITLE
v-if and v-for on the same node

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#591]
In `FilterChecklist.vue` component the `v-if` and `v-for` are present on the same node, whenever the code runs it checks the condition for every iteration of the loop which can become a performance issue later on.

### Screenshots
![v-if-for](https://user-images.githubusercontent.com/43946715/74459735-d2bcfc00-4eb1-11ea-9d8a-3d59acabae45.png)

**Comment by hemanth-hk** [comment]
Enclosing the `v-for` div with a `template` tag and evaluating the `v-if` there will do...

Please assign this to me and I will do the above solution

**Comment by kgodey** [comment]
@hemanth-hk go ahead and work on it

**Comment by hemanth-hk** [comment]
pull-request #593 is sent
