### ISSUE TITLE
Update providers to sources

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#597]
Rename the property names related to `provider` in the `/v1/sources` response handling and in any component code that references these stored values, according to the specified changes in https://github.com/creativecommons/cccatalog-api/issues/421.

To keep consistency across the codebase, we'll rename all references to `providers` to `sources`

**Comment by coderbabu10** [comment]
can i take this up? @brenoferreira

**Comment by scheleon** [comment]
is someone working on this issue or may I start working @brenoferreira?

**Comment by kgodey** [comment]
@coderbabu10 go ahead.

@scheleon I'm assigning this to @coderbabu10 since they commented on it first.

**Comment by kgodey** [comment]
actually, never mind, https://github.com/creativecommons/cccatalog-api/issues/421 needs to be done before this can be done. marking as blocked and unassigned.

**Comment by DantrazTrev** [comment]
Hi @kgodey I've solved creativecommons/cccatalog-api#421 . I think now this issue is workable can I start working  ?

**Comment by kgodey** [comment]
@DantrazTrev I think the API needs to be deployed to production first. @aldenstpage please post here when done.

**Comment by aldenstpage** [comment]
The change is live in dev. Since this is a breaking API change, we'll need to coordinate and do the production release of the API and the frontend simultaneously.

**Comment by hemanth-hk** [comment]
Anyone who is going to work on this issue, please check the changes in #634 and #621, cause they may create merge-conflicts

If people who commented above are busy then assign this to me I'll work on this

**Comment by kgodey** [comment]
Since this wasn't officially assigned, I think it's okay for you to work on it @hemanth-hk.
