### ISSUE TITLE
Using pa11y to make accessibility changes

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#599]
### Tool
Recently I found this tool https://pa11y.org/ which checks the accessibility of a site and works in the localhost too. This would be very useful in making the site more accessible

### Idea
I'm currently working on a small script which will go through the routes and generate individual txt files for the errors in them which we can refer later

### Screenshots
![pa11y-example](https://user-images.githubusercontent.com/43946715/74743532-8d6c4600-5286-11ea-93fb-28df3dfccdef.png)

I'm working on the script and as soon as it's done I'll take this issue

**Comment by akmadian** [comment]
I think using pa11y is a good idea, it seems like it could be integrated with some CI workflow(s) and will help catch little (and big) things that would otherwise be missed.

**Comment by hemanth-hk** [comment]
I generated the data
https://docs.google.com/spreadsheets/d/10Z89p1-0-x0RXVJX5XMJikEiGW8abJ33Tmqbk0OicBU/edit?usp=sharing

**Comment by hemanth-hk** [comment]
Okay after some more googling
1) https://www.npmjs.com/package/eslint-plugin-vue-a11y (this can be integrated and used)
2) https://vue-a11y.com/ (not yet ready)

**Comment by Dhruvi16** [comment]
Hey! I was researching about the improvements we can do in our existing Continuous Integration that is circleci. So, I found this - https://circleci.com/docs/2.0/orb-intro/. CircleCI orbs are shareable packages of configuration elements, including jobs, commands, and executors. CircleCI provides certified orbs, along with 3rd-party orbs authored by CircleCI partners.

And for I found pa11y orb too - https://circleci.com/orbs/registry/orb/nebulab/pa11yci.
Lemme know what you all feel about this.
Thank you.

**Comment by hemanth-hk** [comment]
I feel integrating `pa11y` with continuous workflow may not be a good idea. Cause there may be cases where getting up in running is given more priority than accessibility. So I think that integrating as a `dev-dependency` like `es-lint` would be good which will warn us for accessibility but the warning can be taken down by a specific method.

Let's see what others think about it :)

**Comment by akmadian** [comment]
@hemanth-hk Yep, by CI integration I meant that it could be used as a linter for accessibility related things, similar to, like you said, eslint :)

**Comment by Dhruvi16** [comment]
Oh makes sense! Adding it as a `dev-dependency` is a lot better idea rather than adding it in CI.

**Comment by akmadian** [comment]
Well I meant that it _would_ be used in the CI process, similar to running eslint. Just as you might have `npm run lint` in a CI pipeline, you could also have `npm run lint:accessibility` (or something like this).

**Comment by akmadian** [comment]
I'm gonna link this issue to #488 so it's documented, then close it. Please include this idea (and any others you may have) in your proposal!

**Comment by hemanth-hk** [comment]
Yup, Surely I'll add it to my proposal
