### ISSUE TITLE
Error when I try to run server.js on local machine

### ISSUE THREAD

**Issue by MagicShow1999** [creativecommons/cccatalog-frontend#602]
## Erro message: 
[ERR_REQUIRE_ESM]: Must use import to load ES Module
## To Reproduce
1. Go to project directory
2. Run npm run server
3. See error

## Screenshots
<img width="510" alt="Screen Shot 2020-02-18 at 10 41 49 AM" src="https://user-images.githubusercontent.com/40450775/74751453-473dc500-523b-11ea-9ded-530e8e429614.png">

## Desktop (please complete the following information)
 - OS: MacOS

## Additional context
I googled it and someone says it's a specific bug of node 12.11.0 and so I just upgrade node to 12.16.0 but the err still exists.

**Comment by MagicShow1999** [comment]
Since I want to work on issue #590, I want to fix this A.S.A.P.

**Comment by brenoferreira** [comment]
Did you run `npm run build` before `npm run server`?

**Comment by MagicShow1999** [comment]
> Did you run `npm run build` before `npm run server`?

Yeah and it still raises that error...

**Comment by brenoferreira** [comment]
Can you try using NVM https://github.com/nvm-sh/nvm?

I'm running `v12.4.0` of node here and it works fine. Let me know if installing that version of node with nvm works for you

**Comment by MagicShow1999** [comment]
> Can you try using NVM https://github.com/nvm-sh/nvm?
> 
> I'm running `v12.4.0` of node here and it works fine. Let me know if installing that version of node with nvm works for you

Thanks! I used nvm and set node version to 12.4.0 and it worked!
