### ISSUE TITLE
improvement of spacing

### ISSUE THREAD

**Issue by Amankumar29** [creativecommons/cccatalog-frontend#609]
### improper spacing of the text "over 10,000 images" in the search page.

![Screenshot from 2020-02-21 18-40-54](https://user-images.githubusercontent.com/54955755/75037428-28a92980-54da-11ea-8271-b4a03cceb326.png)

## Additional context
i would like to take this issue.

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by brenoferreira** [comment]
Go ahead

**Comment by coderbabu10** [comment]
its been solved in the pr #611

**Comment by abhisheknaiidu** [comment]
@brenoferreira @akmadian I think this also be closed now, it's already being fixed!

**Comment by zackkrida** [comment]
Thanks for opening this @Amankumar29, this issue has been resolved.
