### ISSUE TITLE
Two scrollbars on feedback page

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#610]
## Problem Description
The iframe in the feedback page comes with scrollbar and the web-page normally has a scrollbar which is a little inconvenient for scrolling as the smaller one stops scrolling for a while  

## Solution Description
Add an overflow: hidden to iframe or say "scrolling": "no"

## ScreenShots
![scrollbar](https://user-images.githubusercontent.com/43946715/75044237-4cbf3780-54e7-11ea-8949-a6b723e51fca.png)

## Additional context
I would like to work on this

**Comment by akmadian** [comment]
@brenoferreira think we should wait to start on this until #588 is merged?

@hemanth-hk, `overflow: hidden` and `scrolling=no` would both cut off part of the form and make it impossible to access the cut off content AFAIK. I think `overflow: visible` would be much better.

**Comment by hemanth-hk** [comment]
This is the preview after I put scrolling = "no" and I don't think there is something cut off here

![preview-after-no](https://user-images.githubusercontent.com/43946715/75060696-4fc92080-5505-11ea-84b6-aadc780ac5ad.png)

**Comment by brenoferreira** [comment]
@akmadian I think that makes sense. This page could change with the work being done there

**Comment by AyanChoudhary** [comment]
We can just make the scrollbar hidden by using 
::-webkit-scrollbar {
  display: none;
}

**Comment by AyanChoudhary** [comment]
Should I do this?

**Comment by akmadian** [comment]
@AyanChoudhary hiding the scroll bar without eliminating the scroll behavior would likely be confusing for the user. I'll let @hemanth-hk take it once it's ready to be done since they opened the issue and indicated that they would like to work on it.

**Comment by hemanth-hk** [comment]
@AyanChoudhary just finish the layout issue cause changing scrollbars may not be a big deal, once that pr is merged we can use this issue to change the scrollbars if there is any necessity :)

**Comment by hemanth-hk** [comment]
Can I take the `feedback issue` cause it was closed due to inactivity?

**Comment by akmadian** [comment]
@hemanth-hk we just closed the PR for inactivity, the issue itself is still being worked on (see #244).

This issue is still not ready for work, and we've already re-assigned 244

**Comment by hemanth-hk** [comment]
Ya, I have to wait till #244 is done...

**Comment by zackkrida** [comment]
Hi @hemanth-hk, if you still have an interest in working on this it should be ready for you to work on!

**Comment by zackkrida** [comment]
Fixed by #1182
