### ISSUE TITLE
Image below the source is not displayed

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#614]
## Describe the bug
The image below the `SOURCE` is not displayed

## To Reproduce
1. Go to 'cc search or build it locally'
2. Search for anything ex: "cats"
3. Click on any images and then click on the `info` tab
4. Below the source, you can see that the cursor turns to `pointer` in white space

## Expected behavior
An image of the source should be present

## Screenshots
![no-source-img](https://user-images.githubusercontent.com/43946715/75097192-d47f7180-55cd-11ea-9e0a-45c8f38fa169.png)

## Desktop (please complete the following information)
 - OS: Ubuntu 19.10
 - Browser : Chrome (Version 80.0.3987.116)

## Additional context
I saw that the images of the `collections` are present in  the `assets` folder so their images can be fetched but if the source is not in `collections` then we can have a default image or just turn the `source` into a link removing the `IMG tag`

I would like to work on this

**Comment by AyanChoudhary** [comment]
One of my PRs is waiting for review. So meanwhile can I take this up?

**Comment by hemanth-hk** [comment]
@AyanChoudhary I wanted to work on this, just waiting for the mentor's review.

**Comment by akmadian** [comment]
@hemanth-hk go ahead and work on this :)

**Comment by hemanth-hk** [comment]
Yup, Done

**Comment by hemanth-hk** [comment]
@brenoferreira This issue is still present...Can I submit a new `PR`

**Comment by hemanth-hk** [comment]
Now it's done :)
