### ISSUE TITLE
Image search from image description won't work with return key

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#616]
## Describe the bug
When we search and open an image details , and use the top search widget to search pressing the return key to search only places the text in search bar and returns to the search section

## To Reproduce
1. Go to 'https://search.creativecommons.org/search?license=&license_type=&categories=&extension=&aspect_ratio=&size=&source=&q=avril&searchBy='
2. Click on any image 
3. Use the search widget type the query and press return
4. It will redirect to previous search results but with the new query on searchbox

## Expected behavior
When search is performed using the return key in the search widget it should return the actual query

## Screenshots
![image](https://user-images.githubusercontent.com/43457420/75097443-d696ff80-55d0-11ea-865c-841433c575c4.png)

### Type the query

![image](https://user-images.githubusercontent.com/43457420/75097455-f7f7eb80-55d0-11ea-9ef1-701ff81cbc9a.png)

### Hit return key

![image](https://user-images.githubusercontent.com/43457420/75097471-165de700-55d1-11ea-8cd7-5b845930d2eb.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser Chrome
 - Version  79.0.3945.130

**Comment by DantrazTrev** [comment]
@kgodey

**Comment by Dhruvi16** [comment]
It works for - 
OS: Linux - Ubuntu 16.04
Browser Chrome(79.0.3945.130) and Firefox(72.0.2)

**Comment by AyanChoudhary** [comment]
This issue exists and I am willing to work on this. Can I take this up?

**Comment by akmadian** [comment]
I can reproduce this on
OS: Windows 10 Pro 1903
Browser: Chrome 79

@DantrazTrev go ahead and work on this

**Comment by abhisheknaiidu** [comment]
@akmadian I have made certain changes and it worked fine for me, could you please once review it ?
