### ISSUE TITLE
Adding of the Searchbar

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#619]
### Screenshots:
**the browse by collection page**

![Screenshot from 2020-02-24 10-49-31](https://user-images.githubusercontent.com/54955755/75130276-7187fa80-56f3-11ea-85da-21ee7b0417db.png)

**the about page**

![Screenshot from 2020-02-24 10-49-46](https://user-images.githubusercontent.com/54955755/75130290-8a90ab80-56f3-11ea-92e0-fab235299301.png)

**if someone who don't want to filter his search by collections can directly go to search page**

### Additional text:
if really its an issue,i would like to take this up

**Comment by coderbabu10** [comment]
what are your views? @brenoferreira @kgodey @akmadian @annatuma

**Comment by annatuma** [comment]
@coderbabu10 we agree that there should be a search bar there, and this is an oversight. However, we're about to integrate redesigns on CC Search pages, including the navigation element, and we plan to include a search bar in the CC Search navigation on all pages except the homepage and the results page, so the Collections page will include a search bar when that work is done. It is in the current sprint.
