### ISSUE TITLE
Adding section to remove filters.

### ISSUE THREAD

**Issue by ankurshr01** [creativecommons/cccatalog-frontend#620]
## Problem Description

When we apply filter, while searching, it should show, the filters which are applied on the top.
Because if we have to remove them we have to go through all the list of filters!

![Screenshot (169)](https://user-images.githubusercontent.com/43695296/75133884-6f796800-5702-11ea-9058-4f973728a304.png)
## Solution Description

We could show the filters which are applied with the cross icon, to remove that particular filter, so that users can easily remove them, rather than going through the list of the filters and removing them. We can add a section on the right side of the text "Filter" 

## Additional context

I would like to work on this!

**Comment by akmadian** [comment]
I like this idea, but I think it will need approval from @panchovm and @annatuma. Pending their approval, you can go ahead and work on this.

**Comment by ankurshr01** [comment]
@akmadian any updates on this?

**Comment by akmadian** [comment]
No updates on my end, I’m sure Anna and Francisco will get around to it soon :)

**Comment by annatuma** [comment]
In Design Library we have a "tag" Button (https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=1%3A28), and a "small/cross" Icon (https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=263%3A46)

What we need to do is:
1) Combine this into a standalone component for these navigational pills and add to the Design Library (@panchovm will do this)
2) Create a ticket in the Vocabulary repo to add this component to Vocabulary, and then do the work (this can be done by @ankurshr01)
3) Finally, once those two prerequisites are complete, we do agree this would be a better navigational experience for users, and would like to move forward with this suggestion, so _this_ ticket can be worked on at that time. We do ask that a screenshot be shared before attempting to implement this, to ensure final sign-off of placement etc.

This ticket will be assigned to @panchovm for next steps, and once their work is complete, they should reassign to @ankurshr01 for the next two steps.

Thanks folks, and sorry about the delay here @ankurshr01

**Comment by panchovm** [comment]
I like the solution. Although I create two changes:
1. In the search result, we will show the filters applied (one by one) with the action to eliminate them.
2. In the "no result" page, the screenshot showed above, I will add a single button to "reset" (it could be a different label) the filters applied.

Once the design is updated, I will change the assignee.

**Comment by panchovm** [comment]
Done. The change is visible in [this Figma's page](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A54&viewport=-209%2C146%2C0.18035496771335602). I will change the assignee

**Comment by ankurshr01** [comment]
@panchovm @akmadian the above link seems broken, and sorry for the delay, I was having my semester exams...

**Comment by akmadian** [comment]
The link works well for me, but that's probably cause I've got access to CC's figmas.
@ankurshr01 Here's a screenshot of the filter section with the clear filters button design.

![clear-filter](https://user-images.githubusercontent.com/28791774/76708620-7c5ffa80-66b5-11ea-8ce3-72e8a8a651f3.PNG)

**Comment by ankurshr01** [comment]
@akmadian thanks :)

**Comment by abhisheknaiidu** [comment]
This is the duplication of issue #797, so I think this can be closed now @kgodey @brenoferreira
