### ISSUE TITLE
Bug in the filter section.

### ISSUE THREAD

**Issue by ankurshr01** [creativecommons/cccatalog-frontend#622]
## To Reproduce
when you click on the down arrow to expand the filter option under the filter section, The arrow should change its direction upward, but it doesn't. 

## Expected behavior

After clicking on the arrow, the arrow should change to the upward direction, to show that particular filter option is extended.

## Screenshots

![Screenshot (171)](https://user-images.githubusercontent.com/43695296/75134251-bd42a000-5703-11ea-9e59-1a356e167b4c.png)

![Screenshot (172)](https://user-images.githubusercontent.com/43695296/75134238-b74cbf00-5703-11ea-9fc2-c6b04853214c.png)

## Desktop (please complete the following information)
 - OS: Windows
 - Browser : chrome
 - Version : 79.0.3945.130

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
 
I would like to work on this!

**Comment by hemanth-hk** [comment]
It is not inverting because it's an image

**Comment by ankurshr01** [comment]
We can change it to add that feature .

**Comment by akmadian** [comment]
Since this is very standard functionality for collapsibles, I'll think of this as a bug instead of a proposal for a design change. Go ahead and work on this @ankurshr01!

**Comment by DantrazTrev** [comment]
Hey @ankurshr01 are you working on this issue?

**Comment by ankurshr01** [comment]
Yes! @DantrazTrev

**Comment by DantrazTrev** [comment]
Need any help @ankurshr01 ?

**Comment by akmadian** [comment]
This issue is being addressed in #645.

@ankurshr01 Please remember to link your PRs to the issue they're addressing :)

**Comment by zackkrida** [comment]
This was implemented. Closing. Thanks for the feedback @ankurshr01 and steering this in the right direction 😸
