### ISSUE TITLE
Images on the results-page lack source image

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#624]
## Describe the bug
The source image on the image in search results is not displayed 

## To Reproduce

1. Go to 'cc search or build it locally'
2. Search for anything ex: "icecream"
3. Hover on the image and you will find that the source image is not displayed

## Expected behavior
The image should be present 

## Screenshots
![no-img-on-source-search](https://user-images.githubusercontent.com/43946715/75149316-b29a0200-5727-11ea-8d83-6e872d0125b0.png)

## Desktop
OS: Ubuntu 19.10
Browser: Chrome (Version 80.0.3987.116)

## Additional context
This is the same `image` object which created the error before in #614

I would like to work on this

**Comment by akmadian** [comment]
Go ahead and work on this :) @hemanth-hk

**Comment by hemanth-hk** [comment]
I am done with the changes but since my last `PR` is not merged yet, creating a new `PR` will have merge-conflicts (cause this one will include commits from that). So once that `PR` is merged I will send this `PR`

**Comment by kgodey** [comment]
@hemanth-hk you can always create a new branch off of current master for this issue

**Comment by hemanth-hk** [comment]
Yup, Done
