### ISSUE TITLE
Info text has no padding in horizontal direction in mobile view

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#625]
## Describe the bug
In mobile view, when select info view of an image, then in mobile view it don't have padding

## To Reproduce
1. Go to 'search on results'
2. Click on 'any result'
3. Scroll down to 'to info tab'

## Expected behavior
Info text should have some padding in horizontal direction

## Screenshots
![Screenshot_2020-02-24 CC Search](https://user-images.githubusercontent.com/35156299/75153986-aff0da00-5732-11ea-84c1-6afc42cabb50.JPG)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
I would like to work on it

**Comment by annatuma** [comment]
@Vineet-Sharma29 I see you've already done work on this (https://github.com/creativecommons/cccatalog-frontend/pull/628)

As a general rule, please wait for approval by a CC team member before proceeding to work on issues.

In this case we are working on a redesign of this page on desktop, which will impact the mobile/responsive layout as well.

FYI @brenoferreira in case this causes any conflicts with single result page redesign: https://github.com/creativecommons/cccatalog-frontend/issues/545

If this doesn't cause any conflicts, then it is fine to approve this change in the PR, @akmadian

**Comment by Vineet-Sharma29** [comment]
@annatuma Will wait for cc team approval in future issues

**Comment by Vineet-Sharma29** [comment]
since this issue has been solved by #661 , I am closing this issue
