### ISSUE TITLE
Adding features in the browse by collection page

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#630]
### Screenshots:

![Screenshot from 2020-02-24 22-00-01](https://user-images.githubusercontent.com/54955755/75171431-9dd26400-5751-11ea-90ce-56b846c1a2f6.png)

### Additional context
I would like to work for this issue

**Comment by coderbabu10** [comment]
@brenoferreira

**Comment by annatuma** [comment]
We're pending the implementation of a redesign of this page, which has already been scoped out by our UX designer. We appreciate the suggestions, but will not move forward with this ticket.
