### ISSUE TITLE
Adding Content Placeholders (SVG Loading skeletons )

### ISSUE THREAD

**Issue by Mahelaa** [creativecommons/cccatalog-frontend#631]
## Problem Description
A new design trend that increases the ux flow is to add loading skeletons when content is being fetched via an api. Example down below

![image](https://user-images.githubusercontent.com/25326308/75176338-f7d72780-5759-11ea-86fa-538d1f79686f.png)

This can benefit users with slower internet as well

## Solution Description
Use SVG skeletons to display when loading state is present to visually demonstrate it. 

## Additional context
I would very much like to contribute to this an take this up. As i have implemented this on my own portfolio as well

**Comment by kgodey** [comment]
all design changes need to be approved by @panchovm or @annatuma.

**Comment by annatuma** [comment]
@Mahelaa this is a good suggestion, thank you for making it. I'm assigning the ticket to you to move this forward, and @brenoferreira or @akmadian will be on point for code review when the time comes.

**Comment by akmadian** [comment]
I'll take point on review :)

**Comment by Mahelaa** [comment]
Update: 
I have implemented the ph for this and was ready to do a pr, but decided to add a bit more features like proper scaling + animating the ph as well

**Comment by panchovm** [comment]
I talked to @Mahelaa about this and we decided one way to solve it. Thanks for raising this improvement.

**Comment by Mahelaa** [comment]
Pushed the current solution! 
TODO : Implement fragements
AutoScaling and padding

**Comment by zackkrida** [comment]
Hi @Mahelaa, we are going to hold off on implementing "skeleton ui" for now. If/when we add it to our design language I will reach out to you. Thanks!
