### ISSUE TITLE
overflow in x-direction in picture detail screen in mobile view

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#632]
## To Reproduce
1. Go to 'results'
2. Click on 'image'
3. Scroll horizontally to 'left'

## Screenshots
![Screenshot from 2020-02-24 23-46-54](https://user-images.githubusercontent.com/35156299/75179608-73d46e00-5760-11ea-83fe-6232b4c0dacd.png)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
I would like to work on this issue

**Comment by annatuma** [comment]
@Vineet-Sharma29 see my comment on #625 regarding general guidelines on approval for issues before they are worked on.

That said, this alignment issue is fine to fix, FYI @akmadian

**Comment by Vineet-Sharma29** [comment]
@annatuma Will wait for CC team approval in future issues.

**Comment by Vineet-Sharma29** [comment]
since this issue has been solved by #661 , I am closing this issue
