### ISSUE TITLE
Varying margins of components at /photos/:id path in the mobile version

### ISSUE THREAD

**Issue by ritiktaneja** [creativecommons/cccatalog-frontend#633]
## Describe the bug
The margins and padding at the /photos/:id path are non-uniform with text moving outside of page margins

## To Reproduce
1. Click on any image fetched from the search results
2. Scroll down to the photo detail section

## Screenshots
![image](https://user-images.githubusercontent.com/53127958/75185709-8fde0c80-576c-11ea-8aae-6f47f03232c0.png)

(Red border indicates page margins)

## Smartphone (please complete the following information)
 - Device: OnePlus 6
 - OS: Oxygen OS
 - Browser : Chrome
 - Version : 79.0.3945

## Additional context
I would like to work on this issue.

**Comment by annatuma** [comment]
Thank you @ritiktaneja for suggesting these improvements.

I believe this is being fixed by https://github.com/creativecommons/cccatalog-frontend/pull/628

@akmadian I'll leave it to you to verify and close this ticket if you agree.
