### ISSUE TITLE
Garbage autocomplete value in search input field can be turned off.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/cccatalog-frontend#637]
## Problem Description
When you click in search input-field a list of possible autocomplete values are shown by the browser, which may or may not be related to CC search website.
![autocomplete in cc search](https://user-images.githubusercontent.com/35863227/75220063-91d3ba00-57c4-11ea-88a0-7733add69894.png)
This is the default behaviour of the browser if the input field's **autocomplete** attribute is not set off.

## Solution Description
Autocomplete attribute in the input can be set to off to disable this behaviour.

## Alternatives
To go with the present functionality.

**Comment by akmadian** [comment]
I'm unsure as to whether or not autocomplete is desired behavior. I'll ping @brenoferreira to get his thoughts on this, and mark this issue as `not ready for work` in the meantime.

**Comment by techievivek** [comment]
@akmadian Yeah sure and the main reason for this issue was at times it also shows URL, emails and other stuff that we have previously searched on some other website and get cached by browsers.
I will add a screenshot for the same in a while.

**Comment by techievivek** [comment]
![Screenshot 2020-02-26 23:29:10](https://user-images.githubusercontent.com/35863227/75373205-d740d600-58ef-11ea-9063-7069f8bd877f.png)
@akmadian This one is what I was talking about.

**Comment by brenoferreira** [comment]
The autocomplete feature is useful, specially if you're frequently searching for the same terms. We shouldn't remove it.

**Comment by brenoferreira** [comment]
Thanks for the feedback
