### ISSUE TITLE
Footer should be improved in About Page.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#638]
## Describe the bug
The footer of the about page looks clumspy, It should be sticked to the bottom to the About page, for better User Inferface and Experience.

## To Reproduce
1. Go to About Page of Creative Commons Site
2. Scroll down.
3. See error

## Expected behavior
Footer should be sticked to the bottom of the page.

## Screenshots
![cc2](https://user-images.githubusercontent.com/55599878/75227259-d7e44a00-57d3-11ea-9af5-6f046d9f7db0.png)

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser : Firefox

## Additional context
I can work on it :)

**Comment by abhisheknaiidu** [comment]
*It (footer) should be also improved in Browser by Collection Page also

**Comment by akmadian** [comment]
This footer is temporary, and will be overwritten once the footer component is ready in vocab. I'm closing this issue because it does not affect functionality, and would be quickly overwritten in the transition to vocab.
