### ISSUE TITLE
 Disabling the linebreak-style rule in .eslintrc.js

### ISSUE THREAD

**Issue by Atanda1** [creativecommons/cccatalog-frontend#649]
## Description
On a windows machine, there's a ton of eslint errors when you run "npm run dev" about "expecting line breaks LF instead of CRLF". I've added
 *.js text eol=lf 
to my gitattributes file, according to eslint documentation (https://eslint.org/docs/rules/linebreak-style) but its not still not working.

## To Reproduce
1. Fork the repo
2. Clone it on your windows machine
3. Run 'npm install'
4. Run 'npm run dev' and you'll see the error

## Desktop (please complete the following information)
 - OS: (windows 10)
 - Browser (ex. chrome, safari)

**Comment by hemanth-hk** [comment]
I think `npm run lint -- --fix` this will fix it, but will modify many files so whenever you are doing a `git pull` do a `git stash` and then whenever you are committing for a pull request add only that particular file(s) don't do a `git add .` 

Wait for some more answers better than mine and then proceed

**Comment by JackieBinya** [comment]
Hello I'm Jacqueline Binya.
I would love to work on this issue if its still open.

**Comment by JackieBinya** [comment]
Hello I am Jacqueline Binya an Outreachy 2020 applicant.
I can disable the rule, may I work on this?
But after I disable the rule everyone pushing from a Windows machine would have to do what @hemanth-hk suggested otherwise they may risk introducing CLFR line breaks whilst the whole code-base uses LF.

**Comment by Atanda1** [comment]
The issue is already under review.

**Comment by brenoferreira** [comment]
We've make some updates recently to the webpack and `npm run dev` doesn't show lint errors anymore. I think this is no longer relevant.

Feel free to reopen if you have any further suggestions
