### ISSUE TITLE
v-for and v-if on same node in LicenseIcons.vue

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#653]
### Description
The IMG tag has both v-if and v-for on the same node so eslint is giving an error

### Screenshot
![v-for-v-if-license](https://user-images.githubusercontent.com/43946715/75367398-46193180-58e6-11ea-81c8-ec950e10439c.png)

### Solution
we can add a template tag around, for the loop and the IMG will have to check only the condition

---
I would like to work on this

**Comment by krysal** [comment]
It's perfectly fine to have both directives in the same tag, maybe you need to check your eslint config (or update?).

**Comment by akmadian** [comment]
Thanks for catching this! Go ahead and work on it :)

**Comment by hemanth-hk** [comment]
Yup, Done
