### ISSUE TITLE
CC Search input value is reset to empty and autofocus disabled once page loads completely

### ISSUE THREAD

**Issue by akandeBolaji** [creativecommons/cccatalog-frontend#659]
## Describe the bug
Once the cc search page loads completely, it resets the search input field and disables autofocus of this field which means any input to the search field before complete page load is cleared 

## To Reproduce
1. Simulate a slow 3G network on your browser to delay the load time 
2. Go to 'https://ccsearch.creativecommons.org/'
3. Immediately the search input receives autofocus, start typing into the search field
4. Now wait for page to load completely 
4. Your input is cleared and autofocus on search field is disabled

## Expected behavior
Any input entered into the search field before complete page load should be persisted after complete page load and autofocus should not be disabled.

## Screenshots
![Uploading ba
![bandicam 2020-02-27 10-23-50-990](https://user-images.githubusercontent.com/35887799/75430599-d6d62880-594b-11ea-8487-b27e2e8e3b00.jpg)
ndicam 2020-02-27 10-24-32-826.jpg…]()

## Desktop (please complete the following information)
 - OS: Windows 8.1
 - Browser Chrome
 - Version 80

## Additional context
I would like to work on this bug

**Comment by Shobhan99** [comment]
Can i work on this issue?

**Comment by akandeBolaji** [comment]
Hi @Shobhan99 , I already indicated I would love to work on the issue, just awaiting approval from any of the admin

**Comment by akmadian** [comment]
I reviewed the PR, in the future, please wait for mentor or admin approval _before_ starting work on an issue.

**Comment by akandeBolaji** [comment]
Okay, noted with thanks

**Comment by brenoferreira** [comment]
After doing some research, the autofocus seems to be an issue for accessibility:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus
https://www.brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/.

So I suggest we remove this altogether, at least until we focus on the accessibility project starts.

Thanks for spotting this 👍 

I'll close this issue and the related PR. I created #705, so feel free to work on that if you want
