### ISSUE TITLE
error on the search result page while refreshing.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#662]
## Describe the bug
when we search something and then we select an image then we get an option for "back to search result" but after refreshing it just disappears,i think it shouldn't happen as the user can face difficulties. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/54955755/75476264-51409000-59c0-11ea-9e56-49b6700341e4.gif)

## Expected behavior
The "back to search result " shouldn't disappear after refreshing.

## Additional context
I think really its a bug and i would like to take this up.

**Comment by brenoferreira** [comment]
This is the expected behaviour. When you refresh the page, the context of your previous search is lost, so we can't know what do to go back to. The `back to results` link is only visible when you navigate from the results page to the image details page.

But thanks for the feedback
