### ISSUE TITLE
Source website logo overshadows search input field on scroll.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/cccatalog-frontend#663]
## Describe the bug
When we scroll, the source website logo overshadows the search input field. Thus creating difficulty in typing.
## To Reproduce
1. Scroll such that source website in any image is on top of input field.
2. Now try clicking on the search input field.
3. It may either redirect to source website.
4. Or may present there on top of the search field.

## Expected behavior
It must have not overshadow or be on top of input field.

## Screenshots
![Screenshot_20200228-001517](https://user-images.githubusercontent.com/35863227/75476672-05421b00-59c1-11ea-8b41-8eb9ff5e1eee.jpg)

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser : Firefox

## Smartphone (please complete the following information)
 - Device: One plus 7t
 - OS: Android 10
 - Browser Chrome
 - Version (ex. 22)

## Additional context
It might be due to the fact that source logo has higher z-index.

**Comment by coderbabu10** [comment]
can i take this issue? @techievivek

**Comment by techievivek** [comment]
@coderbabu10 Let's wait for the confirmation and once approved you can work on it.

**Comment by akmadian** [comment]
Thanks for catching this @techievivek!
