### ISSUE TITLE
Image search from homepage won't update after a previous search 

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#665]
## Describe the bug
When we search from the homepage, and then return to it to perform a new search then the old results are shown .It's an extension of #616 
## To Reproduce
1. Go to 'https://search.creativecommons.org/'
2.Search something
3. Return to home page
4.Search something else
5. You'll see the previous results with new query in search box

## Expected behavior
The image results should be updated 

### Search something
![image](https://user-images.githubusercontent.com/43457420/75483871-b189fe80-59cd-11ea-9c40-9792c16d320c.png)

### Press the back button to return to homepage
![image](https://user-images.githubusercontent.com/43457420/75483974-dbdbbc00-59cd-11ea-8659-933aa5910e51.png)

### Search Something else by clicking on search or return key
![image](https://user-images.githubusercontent.com/43457420/75484010-f01fb900-59cd-11ea-96a0-e30168f6e1c9.png)

### You'll see the previous results
![image](https://user-images.githubusercontent.com/43457420/75484065-0d548780-59ce-11ea-97a8-e109dad68fcf.png)
 

## Desktop (please complete the following information)
 - OS: Windows 10
 - BrowserChrome
 - Version 79.0.3945.130

## Additional context
This extends from #616

**Comment by DantrazTrev** [comment]
@akmadian

**Comment by DantrazTrev** [comment]
@brenoferreira

**Comment by akmadian** [comment]
@DantrazTrev please do not ping mentors or admins for review unless you have not heard back for three business days. We all keep an eye on our repos, and hances are that we’ve seen your message but have not gotten around to replying yet.

**Comment by DantrazTrev** [comment]
Sorry
