### ISSUE TITLE
Add autoload on search results

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#668]
## Problem Description
When the image results are shown , when the list ends we've to click on load more. 

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/43457420/75486391-72aa7780-59d2-11ea-8b13-883b51ca8c76.gif)

## Solution Description

We can use an autoload when user reaches the end and then presses down key or force scrolled

**Comment by coderbabu10** [comment]
@DantrazTrev i don't think it is a better idea because the footer is not fixed and if we search for an image it will autoload around 10,000 images and it will be difficult for the user to go to footer
what do you think? @brenoferreira  @akmadian

**Comment by akmadian** [comment]
I agree with coderbabu, requiring the user to manually click "Load More" cuts down on unnecessary API requests and makes it possible to get down to the footer. I don't think it would auto load the full 10,000 results, though, as we could implement behavior that would only fetch the next batch once the bottom of the page is reached.

I'm interested in what @brenoferreira thinks, but this change seems unnecessary to me.

**Comment by DantrazTrev** [comment]
I was thinking a hover footer for CC maybe that can help . I'll post a design to explain it clearly

**Comment by annatuma** [comment]
We used to have infinite scroll on CC Search and have purposefully done away with it. We will not be revisiting that decision at this time, although I do appreciate the suggestion and discussion.

@DantrazTrev here is a resource on why infinite scroll is bad for accessibility, in case you are interested: http://www.webaxe.org/infinite-scrolling-and-accessibility/
