### ISSUE TITLE
autofocus is 'ON' but not working in home page.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#672]
## Describe the bug
as given that the autofocus is on but it is not working in cc search home page.
when you try to to write something and search it does not happen automatically but first you have to click on the search.

![ezgif com-video-to-gif(2)](https://user-images.githubusercontent.com/54955755/75524200-728e9400-5a33-11ea-9dd1-0a2489529071.gif)

## Additional context
I would like to take this issue.

**Comment by akandeBolaji** [comment]
I already reported and created a pull request for this issue #659 
I think you should close it as it a duplicate
