### ISSUE TITLE
improper alignment of content in "verify at the source" section

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#679]
## Describe the bug
In "verify at the source" section has unnecessary margin due to which alignment is improper

## To Reproduce
1. Go to 'results'
2. Click on 'image'
3. Scroll down to 'verify at the source' section

## Expected behavior
content of "verify at the source" section should be aligned

## Screenshots
![Screenshot_2020-02-29 CC Search(2)](https://user-images.githubusercontent.com/35156299/75582064-c8ddf000-5a90-11ea-853a-e6c4409e553f.png)

## Desktop (please complete the following information)
 - OS: Linux
 - Browser : chrome

## Additional context
If its a legit issue would like to work on it.

**Comment by annatuma** [comment]
@Vineet-Sharma29 I see this has already been done in https://github.com/creativecommons/cccatalog-frontend/pull/628

As mentioned in another ticket, please wait to fix issues until they've been approved by a CC team member. In this case we do want the text under Verify at the Source to be more noticeable, it is an important legal disclaimer.

If you'd like to mock up what it would look like with e.g. bullet points in front that's fine, regardless the indent should be maintained.

**Comment by akmadian** [comment]
@annatuma I just checked, and the only change I could see was that the indent was removed.

**Comment by pranshuls12** [comment]
Hi,Can i work on this >

**Comment by akmadian** [comment]
@pranshuls12 this issue has already been addressed by @Vineet-Sharma29 , and we're unsure right now whether or not we're going to move forward with a fix for this because we're still waiting to hear back from Vineet about their design mockups

**Comment by Vineet-Sharma29** [comment]
@annatuma, @akmadian  Will wait for CC team approval in future issues. Following design can be used for licence detail section:-
![Screenshot from 2020-02-29 04-33-26](https://user-images.githubusercontent.com/35156299/75594067-752dcf80-5aad-11ea-89f7-899c560d27e5.png)

**Comment by akmadian** [comment]
I think this looks good, and better than it is now. Pending Anna's approval, you may include this in your PR :)

**Comment by akmadian** [comment]
@Vineet-Sharma29 Anna and I decided that we like the bullet points, but the spacing is a bit much. I think that approximately half the spacing of what's in the screenshot you provided would be best.

**Comment by Vineet-Sharma29** [comment]
@akmadian reduced `margin-bottom` between `li` from `10px` to `2.5px`.
![Screenshot from 2020-03-03 11-05-07](https://user-images.githubusercontent.com/35156299/75746122-3ca52480-5d3f-11ea-947b-35c7f7c974bf.png)

**Comment by akmadian** [comment]
That amount looks much better to me :) I would prefer that you use some number of rem so it's more responsive on other breakpoints.

**Comment by Vineet-Sharma29** [comment]
@akmadian changed `margin:5px 20px` to equalivalent rem version `margin: 0.3125rem 1.25rem;`. Should I create a new PR or as earlier link these changes with #628 ?

**Comment by akmadian** [comment]
Please include the changes in #628

**Comment by Vineet-Sharma29** [comment]
@akmadian Made changes in #628

**Comment by brenoferreira** [comment]
With the new redesign this is no longer an issue. But thanks for your contribution
