### ISSUE TITLE
Add this text to lists page (or where otherwise appropriate)

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#68]
"We've migrated to public lists. Looking for a private list you created with your CC ID? Shoot us an email at info@creativecommons.org and we are happy to retrieve it for you."

http://ccccatalog.herokuapp.com/lists

cc: @pa-w

**Comment by janeatcc** [comment]
This needs to be done before release!

**Comment by sebworks** [comment]
Fixed in #70 

<img width="1405" alt="screen shot 2018-09-19 at 12 28 31 pm" src="https://user-images.githubusercontent.com/1696212/45767208-8fe8ed00-bc07-11e8-9315-17de1bede3b0.png">
