### ISSUE TITLE
Improve Search Bar's alignment in mobile Devices for better UI/UX 

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#681]
## Describe the bug
Since it's the main page of the site, the CC Search Bar should align properly, but here it's not aligned as expected (should be in middle). It can lead to bad User Experience :(

## To Reproduce
1. Go to https://search.creativecommons.org/
2. See bug

## Expected behavior
The Search Bar should be present in the middle of the Smart Phone :)

## Screenshots

![Screenshot_20200229-015444](https://user-images.githubusercontent.com/55599878/75584960-034a8b80-5a97-11ea-802e-0c50b1da0a82.jpg)

## Smartphone (please complete the following information)
 - Device: OnePlus 6
 - OS: Oxygen OS
 - Browser : Chrome

## Additional context

Would love to work on this issue.

**Comment by annatuma** [comment]
Good suggestion. This is approved for work, please proceed.

**Comment by brenoferreira** [comment]
This was fixed in #661
