### ISSUE TITLE
colliding of scrollbar with images

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#682]
## bug discription :
the related images getting collide with scrollbars in the mobile view.

## screenshots:
![Screenshot from 2020-02-29 02-18-11](https://user-images.githubusercontent.com/54955755/75586608-d13b2880-5a9a-11ea-8c42-cb67aaf8f8e5.png)

## Additional context
i would like to take this issue.

**Comment by akmadian** [comment]
This should be fixed in #628, but thanks for taking the time to spot and report it :)
