### ISSUE TITLE
Filter button issue under responsive view.

### ISSUE THREAD

**Issue by ankurshr01** [creativecommons/cccatalog-frontend#684]
(All things under-responsive views)

When we search an item, and scroll down and then click on the filter icon, which is floating on the top-right, It does nothing, being more specific, it expands the filter section, but at top=0, so it seems that nothing happens.

![Screenshot (182)](https://user-images.githubusercontent.com/43695296/75602856-083b2980-5aef-11ea-9d73-82cf2948088d.png)

So the fix should be, when we click on the filter button, it should take us to the top, where the filter section is expanded. 

OS- Windows 10
Browser - Chrome 

Will take up this issue!

**Comment by ankurshr01** [comment]
@akmadian can u approve this?

**Comment by hemanth-hk** [comment]
When I tried to replicate this problem I found that the z-index of the source image is more than the nav

---

### Screenshot
![mobile-scroll-prob](https://user-images.githubusercontent.com/43946715/75621037-b27d8480-5bb5-11ea-8614-8cbe618fdabf.png)

---

If you can see the `Be` symbol is on top
Feel free to add this to your issue else I'll create a separate issue once you are done editing

**Comment by ankurshr01** [comment]
@hemanth-hk it has been fixed 

https://github.com/creativecommons/cccatalog-frontend/pull/666

**Comment by ankurshr01** [comment]
@akmadian

**Comment by akmadian** [comment]
This behavior may be undesirable from a UX and accessibility perspective because the user probably does not expect to be scrolled back up when the filter section is toggled, and changing what's going on without the user explicitly triggering it is generally considered to be bad.

I'll defer to @panchovm here for the UX perspective, and assuming that he thinks this is a good idea, I'll assign it to @ankurshr01.
_____
Sidenote for @ankurshr01, please refrain from pinging mentors or admins unless you haven't heard back for three business days. We all keep an eye on our repos, and will be sure to get back to you ;)

**Comment by panchovm** [comment]
Thanks @akmadian 
I discussed with @annatuma about this interaction and we decided the following:
1. In the search result page, the user clicks on the filter button.
2. The filters are displayed expanded on the whole screen within a scroll. The close button (top-right) goes back to the search result page, at the bottom the action's section must remain fixed.

<img width="1100" alt="Screen Shot 2020-03-04 at 12 19 26" src="https://user-images.githubusercontent.com/895819/75894070-74c96780-5e12-11ea-97c3-312b357a2d98.png">

When there is no filter selected, the clear filters button must be in the disabled state.

The wireframe is available on [the current design mockup](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A54&viewport=-7780%2C68%2C1.2012704610824585).

**Comment by akmadian** [comment]
I love the look of that mockup :) 

I think this should be ok for @ankurshr01 to start work on this issue. @ankurshr01, please post add a comment in this thread with your plan for how you're going to add this functionality before getting started :)

**Comment by abhisheknaiidu** [comment]
@akmadian Since its been a week and no one is responding here, can i take up this issue ?

**Comment by akmadian** [comment]
@abhisheknaiidu go ahead!

**Comment by ankurshr01** [comment]
@abhisheknaiidu need any help? 
@akmadian its been 6 days, can I take up this?

**Comment by abhisheknaiidu** [comment]
@ankurshr01 I am currently working on this :)

**Comment by abhisheknaiidu** [comment]
@ankurshr01 Actually, I was busy preparing my proposal from last few days, so didn't get much time for solving issues.

**Comment by akmadian** [comment]
@abhisheknaiidu Please make some good progress on this in the next few days, or I'll have to open this issue up for others to work on

**Comment by abhisheknaiidu** [comment]
@akmadian I have fixed the issue, you can once look at it #784 :)

**Comment by abhisheknaiidu** [comment]
Sorry @akmadian I need to open another PR, because of some branch conflicts
you can take a look @ #866
