### ISSUE TITLE
Proper Indentation Required in Image Info Section.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#687]
## Describe the bug
After opening the Image Details Page, the Image info section under that, is not responsive as compared to other elements of the same page.

## To Reproduce
1. Go to https://search.creativecommons.org/
2. Search for any Image
3. Select any Image and click Image's info

## Expected behavior
The Image Info section should be responsive and should have proper Indentation like the other elements.

## Screenshots

![Screenshot_20200301-010735__01__01](https://user-images.githubusercontent.com/55599878/75614092-28083700-5b5b-11ea-8089-6f4e414eb63a.jpg)

## Smartphone (please complete the following information)
 - Device: OnePlus 6
 - OS: Oxygen OS
 - Browser: Chrome

## Additional context
Would love to work on it :) , if it's a legit issue!

**Comment by hemanth-hk** [comment]
I think the `PR` #628 does the same thing. So please wait till that merges

**Comment by akmadian** [comment]
Thanks for reporting this! As hemanth said, this issue is being addressed in #628, so I'm going to close this issue.
