### ISSUE TITLE
Ability to Scroll in Sidebar

### ISSUE THREAD

**Issue by ManishBasavalinga** [creativecommons/cccatalog-frontend#689]
## Problem Description
In the Desktop view, you cant scroll the sidebar. For example, the "All Sources" link has many options in it. To access the bottom options you should scroll the entire page. Also, the sidebar scrolls down when you scroll to the bottom of the page.

## Solution Description
Adding a separate scroll option to the sidebar solves both the issues

## Alternatives
None

## Additional context
If this issue is considered I would like to work on it

**Comment by hemanth-hk** [comment]
Can you please post the link to the problem you are talking about. I am not able to get what you mean by "All Sources"

**Comment by ManishBasavalinga** [comment]
@hemanth-hk "All Sources" refer to one of the options in the collapsible list in the sidebar. Open it and try to scroll to the bottom of the list. You currently can't do that without scrolling down the entire page.

**Comment by akmadian** [comment]
Thanks for catching this! You may go ahead and start work on it :)

**Comment by annatuma** [comment]
Thanks folks! I'm putting this in the current sprint to help keep track of progress. Great suggestion.

FYI @panchovm that this is being worked on.

**Comment by panchovm** [comment]
Thanks for raising this behavior

**Comment by satyaom** [comment]
I like to work on this enhancement

**Comment by zackkrida** [comment]
Implemented in our A/B test of expanded filters. Will go live in the next release.
