### ISSUE TITLE
No image for Smithsonian Institution

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#690]
## Describe the bug
There is no image for one of the collection namely "Smithsonian Institution"

## To Reproduce
1. Go to 'cc search or build it locally'
2. Click on 'Browse by Collection'
3. Scroll down to "Smithsonian Institution"

## Expected behavior
There should be an image for the collection

## Screenshots
![no-img-for-an-org](https://user-images.githubusercontent.com/43946715/75621544-cf1cbb00-5bbb-11ea-97c6-5fd5098e063e.png)

## Desktop
OS: Ubuntu 19.10
Browser: Chrome (Version 80.0.3987.116)

## Additional context
I saw that the in the `assets` folder there is no image for the collection

Please give me the SVG and I'll add it with a particular name which fits the API

**Comment by kgodey** [comment]
Thanks for finding this, @hemanth-hk. 

We didn't mean to enable the Smithsonian yet. We have hidden those images for now.
