### ISSUE TITLE
Source Filter is broken

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#693]
## Describe the bug
Filtering by source doesn't work. This is caused by some changes that were left unfixed #597 and #651. Some components still referenced `provider_name` values that came from the API and it's breaking the filters

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/search?license=&license_type=&categories=&extension=&aspect_ratio=&size=&source=&q=cat&searchBy=
2. Open the `All Sources` filter
3. Click on any filter checkbox
4. Nothing happens

## Expected behavior
It should filter by the selected source

**Comment by ankurshr01** [comment]
Can i take this issue?
