### ISSUE TITLE
Invalid number in the footer section

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#697]
## Describe the bug

The cell number in the footer section when dialled results to Invalid number due to the missing +

## To Reproduce

1. Go to 'https://ccsearch.creativecommons.org/'
2. Click on 'The phone number'
3. Make a call 
4. See that it is invalid

## Expected behaviour
This should make a 
call to the international number and should look like this
![image](https://user-images.githubusercontent.com/43457420/75749116-0d92b100-5d47-11ea-8133-7f3670d8d94a.png)

## Screenshots

![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/43457420/75749678-5dbe4300-5d48-11ea-84b3-9de86d4bd36a.gif)

## Smartphone
 - Device: Any device
 - OS: Any OS
 - Browser Any browser that supports 'tel' references

**Comment by abhisheknaiidu** [comment]
@DantrazTrev This footer is temporary actually, and it will be overwritten once the footer component is ready in vocab.

**Comment by DantrazTrev** [comment]
Alright @abhisheknaiidu

**Comment by DantrazTrev** [comment]
If it's still workable for temp footer only . I would like to

**Comment by akmadian** [comment]
Thanks for spotting this @DantrazTrev! I'm gonna close this because the transition to the vocab footer component is being worked on in the current sprint, so this should be fixed within the next week or so :)
