### ISSUE TITLE
Increase the font size of 'Verify at the source:'

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#699]
## Describe the bug
The Contents under the 'Verify at the source:' are so small that it has become difficult to read it properly through naked eyes. 

## To Reproduce

1. Go to https://search.creativecommons.org/photos/a9d534d7-0ffb-4b73-9f5b-82d25ef1ca50
2. See error

## Expected behavior
Font size should be increased somewhat

## Screenshots

![e2](https://user-images.githubusercontent.com/55599878/75750201-ab877b00-5d49-11ea-838a-44bc5157702d.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser: Firefox

## Additional context
If this issue is considered to be a legit issue! then I would like to work on it.

**Comment by coderbabu10** [comment]
@abhisheknaiidu i think it can be corrected in the issue #679 .

**Comment by abhisheknaiidu** [comment]
@coderbabu10 That issue is just for proper alignment! and not for visibility of content.

**Comment by akmadian** [comment]
I think that the current sizing is ok as it is, but I'd like to get @panchovm's thoughts on this. Pending his approval, you may go ahead and work on this @abhisheknaiidu :)

**Comment by panchovm** [comment]
We are currently working on updating the CC Search style with Vocabulary. In this specific case, that text style will be updated to the normal paragraph style.

**Comment by akmadian** [comment]
Since this will likely change soon, I'm going to mark this as `blocked` until vocab styling is implemented. After that, we can re-visit this :)

**Comment by annatuma** [comment]
This should actually get done as part of https://github.com/creativecommons/cccatalog-frontend/issues/545 when @brenoferreira implements the single result page redesign.

Closing this out.
