### ISSUE TITLE
Everytime someone files an issue, it gets label by default as bug and not ready to work.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#700]

**Comment by hemanth-hk** [comment]
If you haven't already, join the [slack](https://slack-signup.creativecommons.org/) where these types of issues can be discussed before making an issue in Github :)

**Comment by kgodey** [comment]
This is as expected and was added to issue templates across the entire organization in this PR: https://github.com/creativecommons/.github/pull/4. We want to evaluate and validate incoming issues before marking them as ready for work.

I'll update the contribution guidelines to reflect this new process soon.

**Comment by kgodey** [comment]
And actually, if you use the "Feature request" template, the label will not be "bug" :)
