### ISSUE TITLE
Search syntax guide missing from mobile devices 

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#701]
## Describe the bug
The search syntax guide isn't visible on the homepage on portrait mode of handheld devices

## To Reproduce

1. Go to homepage
2. Scroll down to in portrait orientation 
4. No search syntax guide

## Expected Behavior 
There should be a search syntax guide

## Screenshots

![Screenshot_20200303-123228_Chrome](https://user-images.githubusercontent.com/43457420/75751518-b1329000-5d4c-11ea-95fd-d9ea1f3b7bcb.jpg)

## Smartphone (please complete the following information)
 - Device: Galaxy M20
 - OS: Android 10
 - Browser Chrome
 - Version 80

## Additional context
I would love to work on this

**Comment by abhisheknaiidu** [comment]
@DantrazTrev It is purposely made hidden on mobile devices, so the link in the header replaces it.

**Comment by coderbabu10** [comment]
@DantrazTrev as the search guide is inside the toggle button of the navbar so it is hidden in the mobile view

**Comment by DantrazTrev** [comment]
Its visible on landscape mode though

**Comment by sharmaaditya570191** [comment]
Can I take this up @coderbabu10 sir?

**Comment by akmadian** [comment]
I noticed that some of this weird behavior is due to the inconsistent media queries being used, which is going to be addressed by #711. I'm unsure exactly what the time frame for the media query standardization is, so I'll defer to @brenoferreira here.

If the media query standardization will take a while to get to, I'll assign @DantrazTrev. If it will be addressed soon, I think we should close this issue.

**Comment by coderbabu10** [comment]
@sharmaaditya570191 i think you are not aware of cc contributing guidelines,i suggest you to please read it sir,and then ask @DantrazTrev for the same. :)
Thank you.

**Comment by akmadian** [comment]
@coderbabu10 Anyone can indicate their interest on an issue, but if the issue author has indicated that they're interested in working on it, it's very unlikely that I will assign it to someone else (other mentors may take different approaches, though)

**Comment by annatuma** [comment]
Some of this is noted in the earlier discussion, but to summarize:

1) In portrait mode, this is purposefully hidden, and it is included in the hamburger menu.

2) In landscape mode, it is both in the hamburger menu correctly) but is also visible on the bottom right of the screen, with some formatting errors.

I'm attaching screenshots.

Knowing that @brenoferreira has current priorities above #711 then I think it is fine for us to move forward with fixing the formatting on _landscape mode only_ of the link to the search syntax guide.

@DantrazTrev please indicate if you plan to tackle this.

![mobile - portrait - menu expanded](https://user-images.githubusercontent.com/3051816/76559051-69a6b500-646c-11ea-9d5a-b7f3d74d7e5c.png)
![mobile - landscape - incorrect formatting](https://user-images.githubusercontent.com/3051816/76559055-6c090f00-646c-11ea-9bf5-bf84839b641a.png)

**Comment by akmadian** [comment]
@abhisheknaiidu lets wait for @DantrazTrev to reply on whether or not they're still interested, if not, go ahead!

**Comment by DantrazTrev** [comment]
I've made the changes for the search syntax guide , And I'm thinking of the old portal's link in to be better hidden in the mobile devices

**Comment by cangreja533** [comment]
I am an outreachy aspirant, I can work on this issue.

**Comment by akmadian** [comment]
@cangreja533 There is already a PR with a fix for this issue, please check out other issues with the 'help wanted' label here: https://github.com/search?q=org%3Acreativecommons+is%3Aissue+is%3Aopen+label%3A%22help+wanted%22+-label%3A%22in+progress%22

**Comment by brenoferreira** [comment]
This is fixed in #890
