### ISSUE TITLE
not proper allignments of the elements in the browse by collection page in mobile view

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#703]
## Describe the bug
the elements in the browse by collection page are not properly aligned the are more towards right as it should be in the center.
## screenshots:
![Screenshot from 2020-03-03 16-09-29](https://user-images.githubusercontent.com/54955755/75768169-db467b00-5d69-11ea-83f4-a9f24257749d.png)

![Screenshot from 2020-03-03 16-09-39](https://user-images.githubusercontent.com/54955755/75768175-dda8d500-5d69-11ea-8611-fbd1c758e187.png)
## Additional context
i would like to take this issue.

**Comment by akmadian** [comment]
Thanks for spotting this! Pinging @annatuma because I think I remember that this page is getting a redesign. If Anna gives the go-ahead, you may start work on this issue

**Comment by coderbabu10** [comment]
okay @akmadian

**Comment by annatuma** [comment]
It is getting a redesign on desktop, and with the use of grids I expect that will also impact the mobile view here.

I'm going to close this issue, but if it persists once the new designs are integrated, then @coderbabu10 you are encouraged to reopen it and indicate this still requires fixing.

The ticket to look for completion of is in the current sprint: https://github.com/creativecommons/cccatalog-frontend/issues/536
