### ISSUE TITLE
Remove autofocus from homepage search input

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#705]
The autofocus seems to be an issue for accessibility:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#htmlattrdefautofocus
https://www.brucelawson.co.uk/2009/the-accessibility-of-html-5-autofocus/.

We should, at least for now, remove the autofocus from the home page search input, until we do some accessibility usability tests and decide if the autofocus feature is good or not

**Comment by akandeBolaji** [comment]
I would like to work on this

**Comment by DantrazTrev** [comment]
Can I work on this?

**Comment by akmadian** [comment]
@DantrazTrev I've assigned Akande because they indicated their interest first
