### ISSUE TITLE
Content Overlap on mobile view

### ISSUE THREAD

**Issue by theamanjs** [creativecommons/cccatalog-frontend#707]
## Problem Description
Problem with Image name and icon on mobile view. When we scroll down the content which is going up overlaps the header.

## Solution Description
It can be solved by setting the layer(z-index) of header/navbar more(upper)  than the overlapping name and icon of image  #division.

## Alternatives
No alternative

## Additional context
![IMG_20200304_024518](https://user-images.githubusercontent.com/38748298/75820453-60f61500-5dc2-11ea-8b4a-130e335eba4f.jpg)

**Comment by akmadian** [comment]
Thanks for reporting this! It should be addressed in #666, though. I'm going to close this issue because it's a duplicate
