### ISSUE TITLE
Create GitHub workflow for adding issues and PRs to appropriate project

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#708]
## Problem Description
Currently, we need to manually add new issues to the [CC Search backlog GitHub project](https://github.com/orgs/creativecommons/projects/10). We'd like to automate this.

## Solution Description
Set up a GitHub workflow (using GitHub Actions) to
- automatically add new issues created in this repository to the [CC Search backlog GitHub project](https://github.com/orgs/creativecommons/projects/10).
- automatically add new PRs created in this repository to the [CC Search active sprint GitHub project](https://github.com/orgs/creativecommons/projects/7).

**Bonus features** (not sure if these are possible)
- automatically move PRs created by people that are not in the `creativecommons` GitHub organization to the "In Progress (Community)" column.
- automatically move issues with linked PRs from the backlog project to the active sprint project.

## Additional context
- [GitHub Actions documentation](https://help.github.com/en/actions)

**Comment by abhisheknaiidu** [comment]
Can I work on this ?

**Comment by kgodey** [comment]
go ahead

**Comment by abhisheknaiidu** [comment]
@kgodey I just made a PR #710 , but dont know whether its working or not, could you once check it ?
