### ISSUE TITLE
Standardise media queries

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#711]
## Problem Description
The use of media queries is not standardized across the codebase. Running `git grep '@media screen'` you can see how the usage of different screen sizes doesn't follow any particular standard. This results in some weird behaviour in resizing screens and mobile layouts.

## Solution Description
Now that https://github.com/creativecommons/vocabulary uses [Bulma](https://bulma.io/) under the hood, we can use its mixins and classes for responsive layout. We should be able to replace most of media queries with the [Bulma responsive helpers](https://bulma.io/documentation/modifiers/responsive-helpers/) and its [responsive](https://github.com/jgthms/bulma/blob/master/sass/utilities/initial-variables.sass#L56) [mixins](https://github.com/jgthms/bulma/blob/master/sass/utilities/mixins.sass#L73)

**Comment by abhisheknaiidu** [comment]
Can i work on this ?

**Comment by Kirti2502** [comment]
@kgodey Can I work on this issue if nobody else is working?

**Comment by akmadian** [comment]
Hey @Kirti2502, since this issue has the "not ready for work" label, and Breno is assigned, this issue is not up for grabs. Keep looking though, I'm sure you'll find one to work on :)

**Comment by krysal** [comment]
@brenoferreira I made some proposed changes on my draf PR, kindly review it to see if I'm on a good path.
