### ISSUE TITLE
Add is-active feature to the nav-bar links

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#714]
## Problem Description
When we switch from one page to a another, for example from home to about or anything else, we are not able to get the proper interface and userability.

## Solution Description
We can add bulma's class is-active to the nav links for better userability.

![is-active](https://user-images.githubusercontent.com/55599878/75949231-963a5a00-5ecb-11ea-99b9-f5104cf73746.png)

## Additional context
I want to work on this :)

**Comment by akmadian** [comment]
Thanks for sharing your idea :) I'm gonna close this issue because the header component used currently will be replaced with vocab's header component in the current sprint, so any work you do will be quickly obsolesced.
