### ISSUE TITLE
Scroll Behaviour is not working as expected

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#715]
## Describe the bug
When we search something and goes down to the page to some position and click some random pic, and then after going to that random image page, and after if we go back then we'll be given a position of y:0 and not the position from where we had clicked that photo.

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/
2. Scroll down to some y position and click some random image.
3. Click the back image icon on browser.

## Expected behavior

It should show the same position(SavedPosition), from where the image has been clicked, and not the initial position (y:0)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Firefox

## Additional context

Would like to work on this, if its a legit issue!

**Comment by hemanth-hk** [comment]
It's working fine for me like when I click on a random image and go back I am at the same
`y position`
OS: Windows 10
Browser: Chrome

Do wait for other people who test and share their views

**Comment by akmadian** [comment]
It's also working ok for me, if you would like to post this issue in the #cc-search slack channel to see if others can reproduce this, go ahead :) If others can consistently reproduce this, I think we should move ahead with a fix. If not, then I'll close this issue. For now, I'll mark it as `ticket work required` so we can gather more information.

OS: Win 10 Pro 1809
Browser: Firefox Dev. Ed. 74.0

**Comment by annatuma** [comment]
We previously did work on introducing this functionality, of taking users back to the same place in the search results after hitting back.

After testing Safari, Chrome, and Firefox on Mac OS X, this appears to be an issue with Firefox specifically, and only intermittently so, which makes reproducing this harder.

@abhisheknaiidu we're happy for you to work on fixing this.

**Comment by akmadian** [comment]
I'm going to mark this as `in progress` under the assumption that @abhisheknaiidu is up for working on it (as said in the issue body)

**Comment by abhisheknaiidu** [comment]
@akmadian @annatuma the 'Back to search results' link works well in all the browsers, but the back navigation does work properly on firefox. so what I thought is calling onGoBackToSearchResults function, if back button was clicked.

window.onpopstate = function(event){
  onGoBackToSearchResults();
};

Is this fine ?

**Comment by akmadian** [comment]
@abhisheknaiidu yes, I believe that would be a good idea :)
