### ISSUE TITLE
Alternate design for the sources table in about section

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#716]
## Problem Description
The sources table in the About section can be redesigned to a more minimalistic form, and include more information than before and improve the readability

## Solution Description
The table can be designed with two columns one would contain the logo, name and the hyperlinked to the domain while the other will contain the # of CC-licensed works

## Alternatives
There could be alternative designs and that could be better

## Additional context
If this qualifies, I would like to work on it.

**Comment by akmadian** [comment]
Pinging @annatuma and @panchovm because this is a non-trivial design change, I think this could be a good idea if done well :)

**Comment by panchovm** [comment]
The table style is already defined in the Design Library. We should apply that design.

**Comment by akmadian** [comment]
@panchovm The way I understood your comment is that there's already a spec for tables in the vocab library, so that design should be implemented instead of the current design. Is that correct? 

If so, would it be possible for @DantrazTrev to work on it, or is it something that Breno should handle? (is it already a part of #536)

**Comment by miracle-E** [comment]
I'm an outreachy applicant. I would love to contribute to this project

**Comment by panchovm** [comment]
Yes @akmadian, we should apply the Design Library's design. In the mockup (sprint 1) there is no design for that specific page.

**Comment by DantrazTrev** [comment]
This one of the basic things I propose to avoid overflow and scrolling in handled devices
![image](https://user-images.githubusercontent.com/43457420/76217866-38926e80-6239-11ea-98f0-83ea910a7ae0.png)

**Comment by panchovm** [comment]
Oh. I got it. I am pretty sure that that problem is related to the grid instead of a table style. I am not sure how we are working on grid's implementation.

**Comment by annatuma** [comment]
Before this can be worked on, the Table Styles need to be implemented in Vocabulary:
https://github.com/creativecommons/vocabulary/issues/126

Once that is done, this can be reworked. We should not be using the full width of the screen (i.e. all 12 columns of the grid) for the table, so ensure that any updated design has a narrower table than we currently have.

@DantrazTrev we need to see a mockup of the proposed redesign before we approve moving forward. @akmadian no pull request should be approved until myself or @panchovm have an opportunity to review what the restyled page would look like.

Again, confirming this is blocked by https://github.com/creativecommons/vocabulary/issues/126 and once that is complete, work on this can move forward.

**Comment by zackkrida** [comment]
Closing because these tables _were_ updated to the latest version of the vocabulary design, but that we are also thinking about redesigning them further and will discuss that in separate issues. Thanks for your work on this everyone!
