### ISSUE TITLE
unwanted space gap while opening the about page in mobile view.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#717]
## Describe the bug
when we open the cc search about page in the mobile you will find that the space gap is there on the right side.

## Expected behavior
there should be no gap as it looks very odd

## Screenshots![Screenshot_2020-03-05-23-39-35-508_com android chrome](https://user-images.githubusercontent.com/54955755/76012069-aab63b00-5f3b-11ea-8ad6-dbeac3170fcf.jpg)
![Screenshot_2020-03-05-23-39-40-598_com android chrome](https://user-images.githubusercontent.com/54955755/76012100-b275df80-5f3b-11ea-9693-8ce90d3ad390.jpg)
![Screenshot_2020-03-05-23-39-43-147_com android chrome](https://user-images.githubusercontent.com/54955755/76012124-bd307480-5f3b-11ea-83bc-3d8c92d9bfce.jpg)

## Smartphone 
 - Device: redmi 6a
 - OS: android
 - Browser: google chrome

## Additional context
i would like to take this issue.

**Comment by coderbabu10** [comment]
![Screenshot_2020-03-05-23-39-35-508_com android chrome](https://user-images.githubusercontent.com/54955755/76012069-aab63b00-5f3b-11ea-8ad6-dbeac3170fcf.jpg)
![Screenshot_2020-03-05-23-39-40-598_com android chrome](https://user-images.githubusercontent.com/54955755/76012100-b275df80-5f3b-11ea-9693-8ce90d3ad390.jpg)
![Screenshot_2020-03-05-23-39-43-147_com android chrome](https://user-images.githubusercontent.com/54955755/76012124-bd307480-5f3b-11ea-83bc-3d8c92d9bfce.jpg)

**Comment by akmadian** [comment]
Thanks for catching this! I can replicate this with other simulated mobile resolutions. It looks like the width of the sources table is exceeding the width of the screen. Go ahead and work on it :)

**Comment by Romicodes** [comment]
@akmadian  Could you assign me a bug for Outreachy May 2020?

**Comment by akmadian** [comment]
Hey @Romicodes, welcome! Please check out [CC's guidelines for contributing code](https://opensource.creativecommons.org/contributing-code/) to figure out how to proceed :)

**Comment by coderbabu10** [comment]
@akmadian sir any suggestion what i can do for the same.

**Comment by akmadian** [comment]
@coderbabu10 nope, just follow the process for working on or reporting issues like you've been doing :)

**Comment by coderbabu10** [comment]
okay sir

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant, can i take up this bug if it is not been worked upon @coderbabu10 ?

**Comment by Kirti2502** [comment]
Hi, I am an outreachy applicant, can i take up this bug if it is not been worked upon ?

**Comment by coderbabu10** [comment]
Hello @Kirti2502 i am working on this issue you can find another issue having label help wanted or good first issue. :)
thank you
