### ISSUE TITLE
related images in photo-detail view are not centre aligned

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#718]
## Describe the bug
Bug is observed in mobile view

## To Reproduce

1. Go to 'results'
2. Click on 'image'
3. Scroll down to 'related image' section

## Expected behavior
Images should be right aligned

## Screenshots
![Screenshot_2020-03-06 CC Search](https://user-images.githubusercontent.com/35156299/76032137-38575200-5f5f-11ea-833f-41ff29d48d0c.jpg)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
Would like to work on it. Can CC team assign this to me?

**Comment by coderbabu10** [comment]
it is same as #682 because there the images were colliding with the images and can only be corrected by making the images just aligned with the heading,what are your views @akmadian ?

**Comment by Vineet-Sharma29** [comment]
After #661 colliding srollbar or overflow in x-direction has been resolved. However, due to margin errors the related images are not center aligned in the latter PR.

**Comment by akmadian** [comment]
Hey @Vineet-Sharma29, how is this different from #719? When the alignment of the section that contains tags and related images is corrected, this should be resolved. 

Was this issue meant to be only for related images, and #719 only for the tags? If so, I think you could incorporate the alignment fixes from #719 and this issue into one PR.

**Comment by Vineet-Sharma29** [comment]
@akmadian #719 and #718 are different. Alignment error are due following class:-
- `.photo_related-images,.photo_tags{margin-top:30px;}
- `.photo_related-images,.photo_tags{
/* Small only */
  @media screen and (max-width: 39.9375em) {
    margin: 15px;
  }
}`

For #719, both point needs to be fixed and for #718 only point-2 needs to fixed. I will merge these two in a single PR.

**Comment by brenoferreira** [comment]
With the new redesign this is no longer an issue. But thanks for your contribution
