### ISSUE TITLE
header in tag section in photo-detail view has alignment error

### ISSUE THREAD

**Issue by Vineet-Sharma29** [creativecommons/cccatalog-frontend#719]
## Describe the bug
Bug is observered in mobile view

## To Reproduce

1. Go to 'results'
2. Click on 'image'
3. Scroll down to 'tag' section

## Screenshots
![Screenshot_2020-03-06 CC Search](https://user-images.githubusercontent.com/35156299/76032391-d1866880-5f5f-11ea-8821-90698f97d6cd.png)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

## Additional context
Would like to work on it. Can CC team assign this to me?

**Comment by hemanth-hk** [comment]
Firstly there are 2 header tags and secondly, I wanted to know what do you mean by saying `alignment error`, like what is your expected behavior?

**Comment by Vineet-Sharma29** [comment]
By alignment I meant that the border above heading and horizontal line are not aligned.

**Comment by akmadian** [comment]
Thanks for spotting this! Go ahead and work on this :) Please remember to keep it to one PR per issue

**Comment by brenoferreira** [comment]
With the new redesign this is no longer an issue. But thanks for your contribution
