### ISSUE TITLE
Unnecessarily calling a method in created()

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#721]
## Describe the bug
Unnecessarily calling a method in created and watch. The thought behind this is we want to run the watch hook as soon as a component is initialized.

## Expected behavior
But Vue has a built-in solution for this. It’s a property of Vue watchers that we often forget.
All we have to do is restructure our watcher a little bit and declare two properties:
1)  handler (newVal, oldVal) — this is our watcher method itself.
2)  immediate: true — this makes our handler run when our instance is created.

## Screenshots

![created](https://user-images.githubusercontent.com/55599878/76061899-8b0a2b80-5faa-11ea-80fd-c5075aeddf60.png)

## Desktop (please complete the following information)
 - OS: Ubuntu

## Additional context
Want to work on this :)

**Comment by hemanth-hk** [comment]
Which component is this? cause I found 2 `CollectionBrowsePage` components and I cant see the `created` in them

**Comment by abhisheknaiidu** [comment]
@hemanth-hk It is present in CollectionBrowseMixin.js

**Comment by akmadian** [comment]
I'm gonna ping @brenoferreira to get his input as I'm unsure if this was intentional. Pending his approval, you may work on this @abhisheknaiidu :)

**Comment by akmadian** [comment]
Refreshing this @brenoferreira

**Comment by abhisheknaiidu** [comment]
@akmadian , Next time onwards, I'll take of it :)

**Comment by brenoferreira** [comment]
You can try changing it. I can't really tell how it will behave without testing it, specially because we have server side rending.

**Comment by abhisheknaiidu** [comment]
@brenoferreira I got you, and I already made some changes in PR #747
