### ISSUE TITLE
Using Multiple Root Nodes

### ISSUE THREAD

**Issue by Mahelaa** [creativecommons/cccatalog-frontend#722]
## Problem Description
Hey all, 
As you know ive been working on issue #631 and i finished most of the implementation, However i have one issue that needs to be solved. When implementing the placeholders i wanted to use Fragments like in react, however there is no build of it within vue 2, (vue 3 natively has this)

The need for this is to replicate the placeholders efficiently 

## Solution Description
Use vue fragments plugin
https://www.npmjs.com/package/vue-fragment

## Reasons
I wanted to get the feedback + permission if to use this package and to implement this, Or if not i was wondering if there is an already used solution within the codebase to handle this issue

I noticed that a couple components just replicated the divs multiple times so this would help out in that regards as well

**Comment by akmadian** [comment]
I think this could be a good idea, but I'd like to get @brenoferreira's thoughts

**Comment by brenoferreira** [comment]
I think this should wait. If this feature is coming to Vue 3 natively, then let's wait until it's released and see how we can use it to build that feature. For now, I'm a bit hesitant to add this.

**Comment by akmadian** [comment]
Sounds good, for now I'm going to remove the enhancement label and mark this as not ready for work

**Comment by zackkrida** [comment]
Hi @Mahelaa going to close this for now. We do not want to introduce the overhead of a custom `fragments` implementation. I would use `<span>` tags for these for now—thank you!
