### ISSUE TITLE
Adding Voice Search to the CC Image Search

### ISSUE THREAD

**Issue by GeekBoySupreme** [creativecommons/cccatalog-frontend#724]
## Problem Description
It is not easy to search CC for vision-impaired individuals. While updating and adding Accessibility options help, they do not allow for a full-fledged voice search without the use of Screen Readers or other similar Softwares.

## Solution Description
Build Voice Search as a primary feature in the Image Search frontend. It would essentially be a Speech-To-Text plug-in that converts the speech to text, puts it in the search bar and triggers a search. Also, a Text-To-Speech converter that reads out the result header when it first appears on the Image Search Results page.

## Alternatives
Building an Alexa Skill or Action on Google that helps Users query the CC Database without even visiting the Website, but making it more accessible & ambient by adding it to the Alexa and AoG ecosystem.

## Additional context
This is how the feature should work in both the Paradigms - 
1. Clicking on the Mic Icon beside the Homepage results in accessing the User's microphone, the speech is converted to text, the text is filled in the search bar and the search option is triggered.
2. For Alexa or AoG, opening either Assistant and saying "Talk to CC Search" opens up an interactive CC Agent that captures spoken input and searches the database, and shows the result directly inside the Alexa or AoG screen.
For purely voice-based agents like Alexa, the agent would read out the result description and if requested, send the result link to the User's device.

**Comment by abhisheknaiidu** [comment]
@GeekBoySupreme It's actually a Google Summer of Code's Project Idea. If you want to apply in creative commons, you can check it once :)

https://opensource.creativecommons.org/internships/project-ideas/all/#add-audio

**Comment by GeekBoySupreme** [comment]
@abhisheknaiidu, I guess the two are functionally different. 

While the Project Idea talks of having a Sound Dataset that can be searched through, the idea behind this issue is to add the feature of searching through voice. 
In one case, sound is the data, and in the other, sound is just a medium. 

Thanks for the heads up though. Would definitely look into this!

**Comment by akmadian** [comment]
@GeekBoySupreme is correct here, the summer of code project you linked is about adding audio files to the catalog, whereas this issue is about adding voice search functionality to search.

I'm gonna keep this marked as "not ready for work", and link the accessibility meta issue (#488). This may or may not get handled in GSoC/ Outreachy, but @GeekBoySupreme, please include this idea in your proposal!

**Comment by akmadian** [comment]
I'm gonna close this issue to reduce clutter, but it's still connected to the accessibility meta issue so it's documented. Please include this idea and any other ideas you have for accessibility in your proposal!
