### ISSUE TITLE
Searching from the image details page not working

### ISSUE THREAD

**Issue by makkoncept** [creativecommons/cccatalog-frontend#726]
## Describe the bug
Searching for any query from the top right search bar on the image details page does not fill the grid with new images. Though, the search query makes it way to the URL and the main search bar. 

Please refer to the GIF below.

## To Reproduce
1. Go to https://search.creativecommons.org/photos/9f8f92a2-363c-4754-96e7-0f0d26ee1a8c
2. Search for anything from the top right search bar.
3. See error

## Expected behavior
The new search results should fill the grid automatically. The user must not click the search icon again.

## GIF
![ezgif com-crop (2)](https://user-images.githubusercontent.com/34679965/76168159-e7c83a80-6192-11ea-840c-1afd6e80c2aa.gif)

## Desktop (please complete the following information)
 - OS: Ubuntu 19.10
 - Browser: Chrome v80.0.3987.122

**Comment by akmadian** [comment]
Thanks for reporting this :) I think we should tack this onto #667 since it's pretty much the same behavior, just a slightly different situation. @DantrazTrev, I'm going to assign this to you, please include a fix for this in #667 :)

**Comment by abhisheknaiidu** [comment]
@akmadian If no one has done yet, can I re-open my PR, because I have fixes this issue in this PR #657

**Comment by akmadian** [comment]
@abhisheknaiidu I think we're going to move ahead with the fix implemented in #667

**Comment by zackkrida** [comment]
Closing as this was fixed in March. Thanks everyone!
