### ISSUE TITLE
The image grid isn't loaded completely 

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#729]
## Describe the bug
When you search something and scroll down to the bottom there is sometimes a blank space 

## To Reproduce

1. Go to home
2. Search hjem
3. Scroll down 
4. See the missing images

## Expected behavior
The behavior needs to be consistent, in some search results it is somewhat close
![image](https://user-images.githubusercontent.com/43457420/76171659-a7c57f80-61b3-11ea-8e87-bbdab16b517f.png)

But it is far off most of the times to as low as one image

## Screenshots
![image](https://user-images.githubusercontent.com/43457420/76171646-8cf30b00-61b3-11ea-8c97-8132f93472d9.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser Chrome
 - Version 80

## Additional context
I don't know if this is still being worked on or qualifies as a bug , but I would like to work on it

**Comment by akmadian** [comment]
This is because there's a fixed number of images that get fetched from the API at a time, but the widths of the images aren't always consistent, and because of the way we render the images (not in a strict grid), there may be some empty space at the end.

Thanks :)
