### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by hrishikeshpaul** [creativecommons/cccatalog-frontend#730]
## Describe the bug
So I have cloned the repo and when I type `npm run dev`, I get an error as shown below,
```shell
❯ npm run dev

> cccatalog-frontend@1.0.0 dev /Users/hpaul/Documents/cccatalog-frontend
> webpack-dev-server --inline --progress --config build/webpack-dev-conf.js

internal/modules/cjs/loader.js:1167
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/hpaul/Documents/cccatalog-frontend/build/webpack-dev-conf.js
require() of ES modules is not supported.
require() of /Users/hpaul/Documents/cccatalog-frontend/build/webpack-dev-conf.js from /Users/hpaul/Documents/cccatalog-frontend/node_modules/webpack/bin/convert-argv.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename webpack-dev-conf.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/hpaul/Documents/cccatalog-frontend/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:13)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at requireConfig (/Users/hpaul/Documents/cccatalog-frontend/node_modules/webpack/bin/convert-argv.js:97:18)
    at /Users/hpaul/Documents/cccatalog-frontend/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/hpaul/Documents/cccatalog-frontend/node_modules/webpack/bin/convert-argv.js:102:15)
    at Object.<anonymous> (/Users/hpaul/Documents/cccatalog-frontend/node_modules/webpack-dev-server/bin/webpack-dev-server.js:223:50) {
  code: 'ERR_REQUIRE_ESM'
}

```

`npm run build` also doesn't seem to work, giving a similar error.

## To Reproduce

1. Clone repo
2. Type `npm run dev`

## Expected behavior
Server should run

## Desktop (please complete the following information)
 - OS: MacOS 10.15.2

## Additional context
Please let me know if anyone's getting a similar error. Thank you!

**Comment by coderbabu10** [comment]
it think you have to first install npm by typing `npm install`.

**Comment by hrishikeshpaul** [comment]
@coderbabu10 I have done that!

**Comment by abhisheknaiidu** [comment]
@hrishikeshpaul This is actually a question, not an issue and it can be asked in CC's Slack Channel.
If you haven't been a part of it, then you can sign up from here :)
https://slack-signup.creativecommons.org/

**Comment by DantrazTrev** [comment]
Hi @hrishikeshpaul try `npm audit fix` to package issues fix the issues

**Comment by hrishikeshpaul** [comment]
@DantrazTrev I have done so, but it doesn't resolve the error.

**Comment by akmadian** [comment]
Please try the following:
1. Delete your copy of the repo
2. Create a fresh clone of the repo
3. Run `npm run install`
4. Run `npm run dev`

You could also try clearing your npm/ node cache

**Comment by hrishikeshpaul** [comment]
@akmadian I tried this, and am getting the same error.

**Comment by brenoferreira** [comment]
Some people on Slack have reported the same problem and it seems like an issue with some specific versions of Node.
Try using [NVM](https://github.com/nvm-sh/nvm) and installing version `v12.4.0` and see if that fixes the problem.

**Comment by coderbabu10** [comment]
First uninstall the previous version of npm
then run this `npm i node@12.4.0` 
then npm run dev
it will work :)

**Comment by hrishikeshpaul** [comment]
@brenoferreira that did the job! Thank you!
