### ISSUE TITLE
Use Semantic Elements like Article Tag instead of Paragraph Tag for better Accessibilty i.e for people who use screen recorders for the same. 

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#731]
## Describe the bug
People with disabilties, mostly use screen recorder's when using the site, and these screen recorders are not well versed with detecting the paragraph tags, they usually helps to navigate a site using headings and landmarks like nav, article, footer etc

## Expected behavior
Should Follow the ARIA Specific properties for better accessibilty. Since there isn’t much difference in both of their default HTML, as both have a default display value of block.

<img width="1440" alt="ar" src="https://user-images.githubusercontent.com/55599878/76184178-e4639c00-61f0-11ea-8aa9-4f1fb6998517.png">

## Screenshots

We have used few p tags in our codebase,

![p0](https://user-images.githubusercontent.com/55599878/76184126-b2ead080-61f0-11ea-8fdd-a80bf00354d1.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Firefox

## Additional context
Want to work on it, if this is a legit issue :)

**Comment by akmadian** [comment]
Thanks for catching this! Lots of accessibility related issues from you lately :) Please include all of these in your project proposal somehow. As for now, this should be worked on in our GSoC/ Outreachy project (see #488 for the meta issue). I'm gonna apply the proper labels and close this issue to reduce clutter while still documenting that this task should be looked at.
