### ISSUE TITLE
No proper Tab Order in the main CC Search Page for users who rely on the keyboard

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#734]
## Describe the bug
Focus is one of the main pillars of accessibility, especially for users who rely on the keyboard as their primary means of navigating a page. While navigating through the page using the TAB key, i found that the tab order is not consistent, i.e " Looking for the old CC Search portal? Go here" should come first in ordering while navigating for better accessibilty. 

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/
2. Enter Tab Key
3. See error

## Expected behavior
It must be logical and " Looking for the old CC Search portal? Go here" should come first in ordering while navigating for better accessibilty.

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Firefox

## Additional context
Want to work on it, if its a legit issue!

**Comment by DantrazTrev** [comment]
I think the ordering is pretty logical
Nav bar -> Search Section -> Old portal ->Search guide
If we put the old portal first that would be spatial but that would weaken the purpose of the search section
Let's see what the design team has to say

**Comment by abhisheknaiidu** [comment]
@DantrazTrev No it has to be in this order - Nav bar -> Old Portal -> Search Section -> Search Guide, according to the sequence for proper Tab order.

**Comment by akmadian** [comment]
This will be worked on in our GSoC/ Outreachy project (see #488 for the meta issue). I'm gonna apply the proper labels and close this issue to reduce clutter while still documenting that this task should be looked at.
