### ISSUE TITLE
no hover while using tab button in the navbar.

### ISSUE THREAD

**Issue by coderbabu10** [creativecommons/cccatalog-frontend#735]
## Describe the bug
there is no hover while using the tab button.
for better accessibility.
## To Reproduce

1. Go to https://ccsearch.creativecommons.org/
2. Click on 'tab key'
3. See error

## Expected behavior
there should be hover like when you place the cursor

## Screenshots
![Screenshot from 2020-03-09 23-14-27](https://user-images.githubusercontent.com/54955755/76241924-c8491480-625b-11ea-839e-7679c1eab11c.png)

## Additional context
if really its a bug i would like to take this up.

**Comment by coderbabu10** [comment]
i think we can also add hover for the elements under collection in browse by collection page.what are your views @akmadian

**Comment by abhisheknaiidu** [comment]
@coderbabu10 We already have a focus property using Tab Key, and thats more than enough for screen readers and also the nav bar has hover property already and I guess again adding Hover inside hover is a bit confusing and not suitable for responsiveness. What are your views @akmadian 

![hov](https://user-images.githubusercontent.com/55599878/76245439-e6197800-6261-11ea-969b-1befe433cd50.png)

**Comment by coderbabu10** [comment]
i don't think it is enough having just a dotted line box, we can add same hover like while using cursor i think it will be much better for the user.

**Comment by annatuma** [comment]
@coderbabu10 see the comments we made in https://github.com/creativecommons/cccatalog-frontend/issues/737

This appears to all be one issue, browser-specific, and you're welcome to move forward with working on it, but we'll keep all of the work in https://github.com/creativecommons/cccatalog-frontend/issues/737

Closing this issue.
