### ISSUE TITLE
Nar Bar should be more responsive in terms of UI, in mobile view

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#739]
## Describe the bug
Now, the Nav bar basically shows 2 + 2 items

![mobile](https://user-images.githubusercontent.com/55599878/76252546-f08e3e80-626e-11ea-82a7-5b141e5a2506.png)

## Expected behavior
It should be in proper order / alignment for better responsiveness.

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Chrome

## Additional context
Want to work on it, if its a legit issue.

**Comment by miracle-E** [comment]
I'm an outreachy applicant, would love to work on it when it is ready for work.

**Comment by annatuma** [comment]
We will be making updates to the navigation on mobile in the near future: https://github.com/creativecommons/cccatalog-frontend/issues/675

Therefore we won't move forward with any interim changes.
