### ISSUE TITLE
Proper Documentation required for better understanding of Update,Leave and Enter functions

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#743]
## Describe the bug
Since most of the people are confused or unfamiliar with these functions, So we must provide proper Documentation/Commenting for better understanding of beforeRouteUpdate, beforeRouteLeave, beforeRouteEnter functions.

## Expected behavior
Should be properly commented for better understanding.

## Screenshots

![doc](https://user-images.githubusercontent.com/55599878/76354017-ba68c180-6337-11ea-88b7-e56324b3a3cd.png)

## Additional context
want to work on it :)

**Comment by akmadian** [comment]
I think this is a good idea, go ahead and work on it!

**Comment by brenoferreira** [comment]
So, the documentation of these functions are already provided in the [Vue Router Documentation](https://router.vuejs.org/guide/advanced/navigation-guards.html#in-component-guards). We shouldn't duplicate that here. If someone doesn't know how they work, they can refer to the docs.

But I think we should document their specific behaviour in these specific cases here. I'll write some docs and tag you in the PR so you can see if they explain well what it's supposed to happen there

**Comment by brenoferreira** [comment]
@abhisheknaiidu please take a look at #752 and see if those comments help you understand better what's going on

**Comment by abhisheknaiidu** [comment]
@brenoferreira yea I have seen it and suggested some edits 😊
