### ISSUE TITLE
Items explode when the screen is too small

### ISSUE THREAD

**Issue by poyea** [creativecommons/cccatalog-frontend#745]
## Describe the bug

For 320px width, 
![screen](https://user-images.githubusercontent.com/24757020/76494673-aefbc000-6435-11ea-89e4-3335a50f9d33.jpg)
For 375px width, the items are not fitted in the grid.

## Expected behavior

We should have balanced margins and fitted items in the grid.

## Desktop (please complete the following information)
 - OS: (ex. iOS)
 - Browser (ex. chrome, safari)
 - Version (ex. 22)

## Smartphone (please complete the following information)
 - Device: iPhoneX, some android phones
 - Brower: Any

**Comment by abhisheknaiidu** [comment]
@poyea Its the duplication of #703 , and i guess this page is getting Re-Design by CC Team.
