### ISSUE TITLE
Replace /about page text

### ISSUE THREAD

**Issue by janeatcc** [creativecommons/cccatalog-frontend#75]
Replace current text at http://ccccatalog.herokuapp.com/about with the following, and also [insert symbol] with the Clarifai symbol below.

There is no larger compendium of shared human knowledge and creativity than the Commons, including over 1.4 billion digital works available under CC tools. Despite the tremendous growth of the Commons, and the widespread use of the CC licenses and public domain marks, there is no simple way to maximize use of, and engagement with, all of that content. There is no front door — no tool designed for the general public to facilitate discovery for the purpose of reuse and remix, to simplify the license terms, make attribution easy, or support curation, and crowdsourced metadata.

Creative Commons’ “CC Search” project will develop and release an open online search and re-use tool that will allow high-quality content from the commons to surface in a more seamless and accessible way. Our beta relies on open APIs and the Common Crawl dataset and focuses on photos as its first media type. It is meant to elicit discussion and inform our development as we build out the full set of tools. “CC Search” will enable users to curate, tag, and remix that content. It will go beyond simple search to aggregate results from across the hundreds of public repositories into a single catalog, and also facilitate the use and re-use through tools like curated lists, saved searches, one- or no-click attribution, and provenance.

This release contains several new features, including AI image tags generated from our collaborator, Clarifai. Clarifai is a best in class image classification software that provides tagging support and visual recognition. Clarifai’s API was integrated in the process-flow as a means to automatically generate tags for the new and existing images. This means that CC search has machine-generated tags, user-defined tags, and platform-defined tags that were obtained from the web crawl data. Collectively, these will enhance the user’s search experience and improve the quality of the results. Currently, 10.3 million images have their respective Clarifai tags and the outstanding images will be integrated on an ongoing basis. Tags generated via Clarifai are marked with a [insert symbol] on the detail page for each image. With this addition, we’re not just cataloging the commons, we’re making it better. Thank you to Clarifai for their support.

**Comment by sebworks** [comment]
Closed in #76
