### ISSUE TITLE
The Nav bar in image detail page should be sticked for better navigation for mobile users

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#757]
## Describe the bug
For Mobile users, one of the most key feature that they aspire for is Navigation, like how can they navigate other pages with much less time. This is the reason why nav bar should be sticked to the image details page for better navigation!

## To Reproduce

1. Go to https://search.creativecommons.org/
2. Search for any image
3. Select any image
4. See error.

## Expected behavior
Nav bar should be sticked for better navigation for mobile users

## Screenshots

![Screenshot_20200314-132541](https://user-images.githubusercontent.com/55599878/76677784-59234580-65f8-11ea-97ef-016757a7df21.jpg)

![Screenshot_20200314-132549](https://user-images.githubusercontent.com/55599878/76677798-722bf680-65f8-11ea-81ee-3cfec3cd4fc7.jpg)

## Smartphone 
 - Device: OnePlus 6
 - OS: Oxygen Os
 - Browser Chrome

## Additional context
Want to work on it :)

**Comment by akmadian** [comment]
By stickied, do you mean that the header will stay visible at the top of the screen when the page's content is scrolled? If so, I think this would be a good fix, but we should also have the header be sticky on the search results page as well. Until you respond, I'll mark this as `ticket work required`

I'm also curious what @panchovm thinks about this, is there a reason for the header to not be sticky?

**Comment by abhisheknaiidu** [comment]
@akmadian Exactly, the header should stay visible at the top of the screen when the page's content is scrolled. Yea we can fix this in the search results page also I guess.

**Comment by akmadian** [comment]
Pending @panchovm's approval, I think we should move forward with this suggestion, but please wait for him to reply before getting started :)

**Comment by abhisheknaiidu** [comment]
ohkk @akmadian :)

**Comment by panchovm** [comment]
I disagree with this bug. The main nav doesn't have the action to back to results, it's to back homepage or other different pages. In this case, is not necessarily the stickied header.

**Comment by akmadian** [comment]
I just realized that if mobile users want to get back to the header, they can tap the notification bar to be scrolled back to the top of the page. 

Since there's an easy alternative, and since Francisco disagrees with this suggestion, I'm gonna close this issue.
