### ISSUE TITLE
Provider logo not able to load properly under Verify at the Source

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#758]
## Describe the bug
Provider logo not able to load under Verify at the Source

## To Reproduce

1. Go to https://ccsearch.creativecommons.org/
2. Search any image
3. Select anyone

## Expected behavior
Should be able to load provider logo properly

## Screenshots

![ss-provider](https://user-images.githubusercontent.com/55599878/76679232-c89f3200-6604-11ea-9a23-d9c5b05759ca.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Chrome

## Additional context
Want to work :)

**Comment by akmadian** [comment]
Thanks for noticing this! I'm gonna ping @panchovm cause I'm not sure what the intended design is. I tried looking through the Figmas I have access to, but I couldn't find any mockups with this section in CC's collection of search mockups.

**Comment by panchovm** [comment]
This is part of the current design, not the new proposal. I am not sure what was the intention and, now that we're working on a new version, I will skip this.

**Comment by akmadian** [comment]
I'm gonna close this since it will be made irrelevant after #723 is merged.
