### ISSUE TITLE
Unnecessarily showing both info and image about the license can lead to bad user experience.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#759]
## Problem Description
Unnecessarily showing both content and image about the license.

## Solution Description
Rather, we can just show the image only and place an alt function to it, then it can be useful for screen readers as well. And for desktop users, we can add a hover option if required, providing the type of license it is.

![cc](https://user-images.githubusercontent.com/55599878/76679536-6a278300-6607-11ea-99b5-8339efbd9f92.png)

## Additional context
Want to work on this :)

**Comment by hemanth-hk** [comment]
I feel that the way it's rendered now is correct. The hover is already present in the search results page so before any user clicks he/she knows about the license details and source. And this page is primarily used to view the image so adding hover here wouldn't be good, also the hover state is not very well used in the touch screen devices.

If I am wrong in interpreting your idea please correct me and wait for the mentor's review

**Comment by abhisheknaiidu** [comment]
@hemanth-hk The results page doesn't have hover for license details, it just has a normal hover effect, not specifying the type of license, that's the reason I opened an issue for it #698, and as far as, this issue is concerned, I just wanted to show just one among the two, as both convey the same information. And it would be better if we have just an image of licence icons and info hovering on the top of that.

**Comment by hemanth-hk** [comment]
We can't assume that every user understands the icons, So the text is provided and if he/she doesn't understand even the text then they can click and see the license clearly. Now one thing is we can put the link on the images and the user will click on it if he/she doesn't get it, but again we are used to seeing a link in the "blue text", so I think the way it's displayed now is good from all the aspects

**Comment by akmadian** [comment]
Thanks for suggesting this, but I think this is intentional. Especially since search is a CC product specifically made for finding CC licensed material, information about how the work is licensed is very important.

I'm gonna close this issue because I don't think we want to move forward with the proposed changes, but thanks for suggesting them anyways :)
