### ISSUE TITLE
Redundant scrollbar in homepage

### ISSUE THREAD

**Issue by AyanChoudhary** [creativecommons/cccatalog-frontend#761]
## Describe the bug

The scrollbar on the homepage is redundant as there is no need for any scroll on that page.

## Expected behavior

There should not be any scrollbar there.

## Screenshots

![CC Search - Google Chrome 14-03-2020 21_06_19](https://user-images.githubusercontent.com/45792768/76685234-226d1f80-6638-11ea-8d8e-14e298d006b8.png)

## Desktop (please complete the following information)
 - OS: Windows 10
 - Browser Chrome
 - Version  80.0.3987.132 (Official Build) (64-bit)

**Comment by AyanChoudhary** [comment]
Would like to work on this :)

**Comment by akmadian** [comment]
Thanks for catching this! Go ahead and submit a PR with a fix

**Comment by AyanChoudhary** [comment]
@akmadian is the webpage not updated? Because when I opened the development build on my system, I can see a few changes on the page and the issue of scrollbar is not there on that version. I am attaching the screenshots for a reference.
Currently hosted webpage
![Screenshot from 2020-03-16 15-06-12](https://user-images.githubusercontent.com/45792768/76743113-1ef0aa00-6798-11ea-8cfb-44d9a2b9cbdd.png)

Development version:
![Screenshot from 2020-03-16 15-06-08](https://user-images.githubusercontent.com/45792768/76743149-2f088980-6798-11ea-9207-3dab0fc86a4f.png)

**Comment by akmadian** [comment]
Ah yeah, there are a number of changes related to the site's design that have been made, and are being made. If you created your fork before #661, this could explain it.

Since it seems like it's working on on the development branch, I'm gonna close this issue.
