### ISSUE TITLE
Lazy load images and provide fallback templates

### ISSUE THREAD

**Issue by AyanChoudhary** [creativecommons/cccatalog-frontend#762]
## Problem Description

The image collection which is displayed often takes a large time to load(even on faster collections sometimes). This easily leads to bad user experience. Instead of trying to load all images simultaneously, it would be better if we apply lazy loading to the images, this will considerably reduce load time and would also make it possible to use component recycling as not all the grid positions are being used to display images at the same time. Also, there doesn't seem to be any fallback for missing images. Having that would be great too.

## Solution Description

We should apply lazy loading to images, as well as asynchronously load images that enable component recycling. Also, we need to provide a fallback to missing images.

## Additional context

![CC Search - Google Chrome 14-03-2020 21_20_27](https://user-images.githubusercontent.com/45792768/76685530-93153b80-663a-11ea-85cc-6efd4db4d9a0.png)
![CC Search - Google Chrome 14-03-2020 21_20_36](https://user-images.githubusercontent.com/45792768/76685533-94deff00-663a-11ea-8054-5a23cd9cbefa.png)

I would like to work on this.

**Comment by akmadian** [comment]
I believe that this is happening because the search frontend loads full res images, the network tab supports this: for the MMOA collection, the first page shows 49.03 MB transferred, not good :/

I think this should be fixed by the catalog API team's work on implementing getting image thumbnails. @aldenstpage could you confirm this for me?

If the work on thumbnails is a long ways away, or wouldn't fix this, I think we should move forward with a fix. Please wait for Alden's confirmation before starting, though :)

**Comment by aldenstpage** [comment]
We return the thumbnail for this API call. If the full resolution is being loaded, it must be because the frontend is choosing to display the `url` instead of the `thumbnail_url`. @brenoferreira?

Try `GET https://api.creativecommons.engineering/v1/images?source=met` for an example.

**Comment by akmadian** [comment]
Ah I see, @AyanChoudhary if you would like to investigate whether or not the correct url is being fetched, that would be great! If the incorrect one is being used, please open an issue for it so we can move forward with a fix for it :)

Until then, I'm gonna close this issue

**Comment by brenoferreira** [comment]
There's a potential source of bug here https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/components/SearchGridCell.vue#L101, where the image url for the image grid may not be the thumbnail url

**Comment by brenoferreira** [comment]
In the MET case, it seems like the thumbnails are coming from this endpoint:
https://api-dev.creativecommons.engineering/t/600/https://images.metmuseum.org/CRDImages/dp/web-large/DP801140.jpg
And the image loaded ins 1MB+ each
