### ISSUE TITLE
Lazy load the Routes to reduce load time

### ISSUE THREAD

**Issue by Albaalah** [creativecommons/cccatalog-frontend#765]
## Problem Description
Frontend loading time requires optimization as the initial load time is high. Currently, we are loading the routes with regular imports.

## Solution Description
Introduce VueRouter Lazy Loading. The lazy loading of the routes will load the components only when needed and thus allow for quicker load time and improve performance

## Additional context
I would love to work on this. Please assign it to me. Thanks!

**Comment by akmadian** [comment]
I'm not sure if this would help much, routing seems to be pretty quick to me, but that doesn't mean that it's _always_ quick.

I'll ping @brenoferreira to see what he thinks about this

**Comment by Albaalah** [comment]
I agree that the routing isn't too slow but lazy loading is an excellent feature provided by the _vue-router_ library that we are using. Using its lazy loading and dynamic imports will remove the unnecessary bulk loading and instead load _chunks_ on a when or as required basis hence contributing towards the last point of our frontend public roadmap

**Comment by akmadian** [comment]
Refreshing this @brenoferreira

**Comment by brenoferreira** [comment]
I'm not sure we'll benefit much from lazy loading the components, at least not at this moment. If you want to do some research with https://www.npmjs.com/package/webpack-bundle-analyzer and see if code splitting would decrease bundle sizes, please go ahead. We can then decide if it's worth doing lazy routes

**Comment by kgodey** [comment]
Marking this help wanted, but **please do the research mentioned in the comment above** and post it here. Do not send a PR without doing the research.

**Comment by Albaalah** [comment]
sure, I'll be researching this today and will post my results here

**Comment by Albaalah** [comment]
As per my output, the chunks total adds up to be higher but code splitting is producing chunks in smaller sizes. Screenshots attached for reference.
Before:
![1](https://user-images.githubusercontent.com/51597921/78485520-5f709180-7760-11ea-83ad-d26660e080fd.PNG)
After:
![2](https://user-images.githubusercontent.com/51597921/78485694-6bf4ea00-7760-11ea-94f2-2d5a226af854.PNG)

**Comment by zackkrida** [comment]
Hi @Albaalah, I agree with you that we should lazy load routes. The biggest benefit would be reducing the initial page load of the site, which is a significant factor in SEO and user bounce. 

I am in the middle of evaluating [some changes to our SSR approach](https://github.com/creativecommons/cccatalog-frontend/issues/1108), after that work is completed I will have an answer for you on how we should move forward. Thank you for bringing this issue up!

**Comment by zackkrida** [comment]
@Albaalah I am going to close this ticket—however we move forward (Nuxt.js _or_ keeping our current SSR, we will switch to code-splitting by route, and i'll create a new ticket if necessary. Thank you!
