### ISSUE TITLE
Update search syntax guide to use simplified query syntax

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#767]
We've switched to a simplified query parser. It has the advantage of being harder for users to break with special characters and unmatched brackets while still providing the main search operations that a user would be interested in.

You can find a detailed guide about the available operations [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-syntax).

**Comment by Rishabh606** [comment]
@aldenstpage Hi! I am a GSoC applicant. Is this issue open?

**Comment by kgodey** [comment]
Yes, if an issue is marked help wanted, it is open and you can send PRs for it without approval/permission.
