### ISSUE TITLE
Text and headings in Image Details page, touches the edge on Phone Screens

### ISSUE THREAD

**Issue by GeekBoySupreme** [creativecommons/cccatalog-frontend#771]
## Describe the bug
Text Descriptions touching the edge of the screen when viewed in a Mobile Browser

## To Reproduce
1. Go to CC Search.
2. Click on a Search Result.
3. Scroll down to 'Image Attribution'

## Expected behavior
Margin/Spacing on both sides of the text div.

## Screenshots
![image](https://user-images.githubusercontent.com/15321738/77103291-2e921c00-6a40-11ea-94dd-0ef329c80292.png)

## Desktop (please complete the following information)
 - OS - macOS Catalina
 - Browser - Chrome
 - Version - 80

## Smartphone (please complete the following information)
 - Device: Nokia 6.1
 - OS: Android 9.0
 - Browser: Firefox
 - Version: 68.6.0

**Comment by akmadian** [comment]
I'm gonna close this since it was likely fixed with the merge of #723, please check if it's still an issue at https://ccsearch-dev.creativecommons.org. If it is, feel free to re-open this issue or open a new one :)
