### ISSUE TITLE
Excessive spacing between license icons

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cccatalog-frontend#772]
## Describe the bug

License icons are excessively spaced now that #723 has been merged, see attached pictures.

## To Reproduce

1. Go to https://ccsearch-dev.creativecommons.org/
2. Search for something
3. See error when hovering on an image
4. Click on image to see image details
5. See error under the Attribution tab
6. Click on the Info tab
7. See error again

## Screenshots

![s-i1](https://user-images.githubusercontent.com/28791774/77104023-90b73680-69d8-11ea-91ea-94ee6ba7c363.PNG)
![s-i2](https://user-images.githubusercontent.com/28791774/77104025-90b73680-69d8-11ea-9e5b-ced1cf5af3aa.PNG)
![s-i3](https://user-images.githubusercontent.com/28791774/77104026-914fcd00-69d8-11ea-885d-540cd74b9989.PNG)

## Desktop (please complete the following information)
 - OS: Win 10 Pro 1809
 - Browser: Firefox Dev. Ed. 74.0

**Comment by abhisheknaiidu** [comment]
Can I work on this ?

**Comment by abhisheknaiidu** [comment]
@akmadian I have corrected it in #773 :)
