### ISSUE TITLE
Search bar in search results page in mobile devices should be large 

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#774]
## Describe the bug
The current search bar in the mobile view looks clumsy and it affects both the user experience and interface.

## To Reproduce

1. Go to https://ccsearch-dev.creativecommons.org/
2. Search for something
3. See error

## Expected behavior
the button should be small compare to search bar

## Screenshots

![ui](https://user-images.githubusercontent.com/55599878/77119318-39f34080-6a5c-11ea-8471-c0498a68be10.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser Chrome

## Additional context
Want to work on it :)

**Comment by kgodey** [comment]
This was fixed in https://github.com/creativecommons/cccatalog-frontend/pull/786
