### ISSUE TITLE
Filter icon missing in search bar on mobile breakpoints 

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cccatalog-frontend#776]
## Describe the bug

After design sprint 1 (#723) was merged, the filter icon does not render in the search results page on mobile breakpoints

## To Reproduce

1. Go to ccsearch-dev.creativecommons.org
2. Search for something
3. Use browser to simulate a mobile breakpoint

## Screenshots

![searchbar0](https://user-images.githubusercontent.com/28791774/77197321-38e50200-6aa2-11ea-983c-0aad65929500.PNG)

## Desktop (please complete the following information)
 - OS: Win 10 Pro 1909
 - Browser: Firefox Dev. Ed. 75.0

**Comment by Albaalah** [comment]
can I take this up if it's available?

**Comment by akmadian** [comment]
@Albaalah This is going to be fixed in #786

**Comment by zackkrida** [comment]
Closing as this was fixed in #786 and by subsequent redesigns
