### ISSUE TITLE
Search button cut off on results page on mobile breakpoints on Firefox

### ISSUE THREAD

**Issue by akmadian** [creativecommons/cccatalog-frontend#777]
## Describe the bug

After design sprint 1 (#723) was merged, the search button in the results page is not visible

## To Reproduce

1. Go to ccsearch-dev.creativecommons.org
2. Search for something
3. Use browser to simulate a mobile breakpoint

## Expected behavior

The search button should be visible, as seen in this screenshot of the ipad resolution:
![searchbar0-intended](https://user-images.githubusercontent.com/28791774/77197606-bad52b00-6aa2-11ea-8d76-4c8a27a62d0a.PNG)

## Screenshots

![searchbar0](https://user-images.githubusercontent.com/28791774/77197619-be68b200-6aa2-11ea-90bb-e10decc7a4f7.PNG)

## Desktop (please complete the following information)
 - OS: Win 10 Pro 1909
 - Browser: Firefox Dev. Ed. 75.0

**Comment by CptChix** [comment]
I can take it if it's needed

**Comment by akmadian** [comment]
go ahead @CptChix :)

**Comment by abhisheknaiidu** [comment]
@akmadian I don't find that issue in my local setup, I am attaching some of the Screenshots

Screenshots :

iPhone X 

![ix](https://user-images.githubusercontent.com/55599878/77225582-627f5580-6b96-11ea-851f-7e5676ea6840.png)

iPhone 6/7/8

![i6](https://user-images.githubusercontent.com/55599878/77225598-7460f880-6b96-11ea-9f43-35897062edb7.png)

**Comment by akmadian** [comment]
@abhisheknaiidu thanks for posting this, it seems like it's not an issue on Chrome :)

**Comment by abhisheknaiidu** [comment]
Can I work on this , @akmadian then ?

**Comment by CptChix** [comment]
Just a heads up. Might be a false positive that’s caused by the emulators.
Here’s how it looks on firefox ios iphone11 max
![D441DF02-971E-4215-9675-320393796EF6](https://user-images.githubusercontent.com/22933152/77234732-babf5300-6ba8-11ea-98f7-c36e3798acc8.png)

**Comment by abhisheknaiidu** [comment]
@CptChix it's ccsearch-dev.creativecommons.org and ccsearch.creativecommons.org

**Comment by akmadian** [comment]
@abhisheknaiidu No, like I said in the other issue, please read through the issue thread to see if someone else is working on the issue already

**Comment by abhisheknaiidu** [comment]
@akmadian oops my mistake again! 😓
