### ISSUE TITLE
URI with filtering options does not load correctly

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-frontend#78]
This is a bug
Steps to reproduce
1. Go to https://ccsearch.creativecommons.org
2. Search for cats (because that is what the internet is for of course)
3. Filter on CC BY-NC licenses
4. Change 'cats' to 'cat' and search again, notice that the address bar now states, also note that are no search results: 
''''
https://ccsearch.creativecommons.org/search?q=cat&provider=&li=by-nc&lt=
''''
5. copy that URL and paste in a new tab.

Notice that the filter is not being set by the URI

**Comment by sebworks** [comment]
@mzeinstra, thank you for creating this issue.  It should now be closed.
