### ISSUE TITLE
Get icons from Vocabulary into CC Search

### ISSUE THREAD

**Issue by kgodey** [creativecommons/cccatalog-frontend#785]
Use the icons provided [here](https://cc-fonts.netlify.com/?path=/docs/vocabulary-icons--page)

And the [logos](https://cc-vocabulary.netlify.com/?path=/docs/assets-logos--cc-logomark)

**Comment by csayaan** [comment]
I can take it. Please describe the issue with an image.

**Comment by brenoferreira** [comment]
@csayaan I'm working on this already
