### ISSUE TITLE
Add svg to contents of photo details page for better experience

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#787]
## Problem Description
Before :

![svg_b](https://user-images.githubusercontent.com/55599878/77428900-d91e8c00-6dfe-11ea-95cb-96d1924094c7.jpg)

After :

![svg](https://user-images.githubusercontent.com/55599878/77428966-f18ea680-6dfe-11ea-8f12-00b0ba69c700.png)

## Solution Description

Add SVG Icons just like before :)

## Additional context
Want to work on this, if CC staffs thinks its a legit issue!

**Comment by csayaan** [comment]
I want to work on this .

**Comment by akmadian** [comment]
I'm gonna ping @panchovm for this one to get his thoughts. I think the current design looks cleaner without the icons, but Francisco is the designer so I'll defer to him :)

**Comment by panchovm** [comment]
There is no specific problem detailed in this ticket. As a design principle, we want to reach a clean design. So let's keep the design.

**Comment by abhisheknaiidu** [comment]
Yea @panchovm agree with you!
