### ISSUE TITLE
Proper spacing should be given in between the tags of photo detail page for mobile users

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#788]
## Describe the bug
At present, there is not a proper alignment or space between the given tags of a particular photo.

## To Reproduce

1. Go to ccsearch-dev.creativecommons.org
2. Search for something
3. Use a browser to simulate a mobile breakpoint

## Expected behavior
Proper spacing should be given in between the tags.

## Screenshots

![tags](https://user-images.githubusercontent.com/55599878/77429731-159eb780-6e00-11ea-81e0-c52666328d99.png)

## Desktop (please complete the following information)
 - OS: Chrome
 - Browser firefox

## Additional context
want to work on this, if CC staff thinks its a legit issue!

**Comment by akmadian** [comment]
Hey @abhisheknaiidu, what changes, specifically, would you make? Until you reply I'll add the `ticket work required` label

**Comment by abhisheknaiidu** [comment]
@akmadian to provide proper spacing in between tags, like if you see in this one there is no proper spacing exists, between the 1st and 4th tag.

**Comment by abhisheknaiidu** [comment]
@brenoferreira @akmadian  Since I'm the one, who opened this issue, so can I work on this ?

**Comment by annatuma** [comment]
@abhisheknaiidu feel free to work on this. Thank you for suggesting this fix.
