### ISSUE TITLE
Change the placeholder text in Homepage

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#792]
On the homepage, the text of the search bar says `Search for images...`. It should change to `I'd like to see...`.

**Comment by Tanuj22** [comment]
@kgodey Should I make multiple PRs for these set of issues or single PR is good?

**Comment by kgodey** [comment]
One PR per issue please (there was a question about that on this issue but it seems to have been deleted).

**Comment by Tanuj22** [comment]
Sorry about that. I figured that should be the case.
