### ISSUE TITLE
Change to corners of search bar and button in Homepage

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#793]
In Homepage, the search bar should have `0px` for top-right and bottom-right corners. And the button `Search` `0px` for top-left and bottom-left corners.

### Expected design
<img width="794" alt="Screen Shot 2020-03-24 at 16 23 54" src="https://user-images.githubusercontent.com/895819/77468108-e67e4b00-6deb-11ea-99a5-02b58b1b8393.png">

**Comment by abhisheknaiidu** [comment]
May i work on this ?

**Comment by kushaggarwal** [comment]
If this issue is still open can I attend to this @panchovm @kgodey 
Please help

**Comment by kgodey** [comment]
Issues marked "help wanted" are open, no need to ask.
