### ISSUE TITLE
The space between search bar and filters in home page should be larger

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#794]
On the home page, the space between the search bar and **I want something I can** filters should be `64 px` for desktop resolution.

### Current implementation
<img width="824" alt="Screen Shot 2020-03-24 at 16 47 23" src="https://user-images.githubusercontent.com/895819/77470282-2abf1a80-6def-11ea-8506-2c7800028198.png">

**Comment by abhisheknaiidu** [comment]
I want to work on this.
