### ISSUE TITLE
Add the magnifying glass icon to the search bar 

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#796]
In the search result page, the search bar doesn’t have the magnifying glass/search icon on the left side. We need to add it.

### Expected design
<img width="464" alt="Screen Shot 2020-03-24 at 16 53 20" src="https://user-images.githubusercontent.com/895819/77470776-fb5cdd80-6def-11ea-8f7d-5fb3cc57b2ad.png">

**Comment by abhisheknaiidu** [comment]
May I work on this?

**Comment by lamhoangpham20** [comment]
I want to work on this if nobody is fixing this.

**Comment by brenoferreira** [comment]
This is fixed in #850
