### ISSUE TITLE
Add the filters above the gallery on search result page

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#797]
In the search result page, we need to show the filters that the user selected.

### Expected design
<img width="464" alt="Screen Shot 2020-03-24 at 16 53 20" src="https://user-images.githubusercontent.com/895819/77471060-6e665400-6df0-11ea-926d-c584bdabdee9.png">

**Comment by ankurshr01** [comment]
Hey can I Work on this? 
I think this issue is also addressed at https://github.com/creativecommons/cccatalog-frontend/issues/620 by me.

**Comment by abhisheknaiidu** [comment]
@ankurshr01 are u still working on this? or need any help?
