### ISSUE TITLE
Change the space between `Search by Creator` and `Clear filters`

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#799]
In the search result page, the distance between filter `Search by Creator` and `Clear filters` is not correct. It should be `24px` with a line separating the actions.

### Expected design
<img width="740" alt="Screen Shot 2020-03-24 at 17 09 38" src="https://user-images.githubusercontent.com/895819/77472169-4546c300-6df2-11ea-8214-ec3a8c86ef58.png">

**Comment by abhisheknaiidu** [comment]
May I work on this?

**Comment by kgodey** [comment]
We will be adding "help wanted" labels to issues suitable for community contribution, please be patient. Once those are up, you can send PRs without any prior approval per our new contribution guidelines.

**Comment by abhisheknaiidu** [comment]
oh ohkk @kgodey
