### ISSUE TITLE
Hover content on every image of gallery is incorrect

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#800]
In the search result page, the content displayed over the image during the hover state should be as follows:

## Expected design
<img width="501" alt="Screen Shot 2020-03-24 at 17 11 43" src="https://user-images.githubusercontent.com/895819/77472386-98207a80-6df2-11ea-93f5-020779511ffb.png">

* License icons on the top-left
* No external links for on the work's name.

**Comment by abhisheknaiidu** [comment]
Want to work on this

**Comment by dos077** [comment]
I did the image grid layout last time. You want me to take care of this? I never touch the thumbnail hover, the scss looks pretty messy. I can either clean it up and just render whatever is necessary, or I can just remove the background gradient and hack the black background box with shadow in there. Also that markup doesn't have the image provider icon, should that be remove?

**Comment by kgodey** [comment]
This issue is marked help wanted, feel free to send a PR @dos077.

**Comment by dhruvkb** [comment]
Also linking creativecommons/vocabulary#208 fixing creativecommons/vocabulary#58.

**Comment by dos077** [comment]
Okay, did some quick fiddling around with the css. Removed the gradients and adjusted the padding to 8px(y) and 16px(x). Added a black background to the image title detail box, added the typography setting from the vocabulary pr, Source Sans, 13px size, and 19px line height. Still unclear about what to do with the search provider logo, it looks odd.

![Screenshot 2020-03-25 at 8 32 37 PM](https://user-images.githubusercontent.com/45016741/77598459-40f4d580-6ed8-11ea-9b89-9cbec0a339d2.png)

**Comment by panchovm** [comment]
The logo must disappear from that place

**Comment by dhruvkb** [comment]
@brenoferreira PR creativecommons/vocabulary#208 is merged.
