### ISSUE TITLE
The back to search results action doesn't have the icon.

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#801]
In the single result page, the `Back to search results` action does not have the arrow icon as the mockup indicates.

### Expected design
<img width="439" alt="Screen Shot 2020-03-24 at 17 33 57" src="https://user-images.githubusercontent.com/895819/77474330-aa4fe800-6df5-11ea-8791-dae8a19d2f96.png">

**Comment by samcaspus** [comment]
@panchovm @kgodey I believe I fixed the issue at this pull request here [#819](https://github.com/creativecommons/cccatalog-frontend/pull/819) please do review Thanks

**Comment by samcaspus** [comment]
made a minor tweak for the issue and I believe i have fixed it as desired at [#819](https://github.com/creativecommons/cccatalog-frontend/pull/819)
