### ISSUE TITLE
The size of license icons should be 30px

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#803]
In the single result page, the license icons should be `30px`

### Current implementation
<img width="260" alt="Screen Shot 2020-03-24 at 17 40 11" src="https://user-images.githubusercontent.com/895819/77474871-9f498780-6df6-11ea-8164-8bfec2d78b6c.png">

**Comment by lamhoangpham20** [comment]
can I be assigned to fix this issue?

**Comment by kgodey** [comment]
We are no longer doing assignments; anyone is free to submit a PR for issues marked "help wanted". Please read our [contribution guidelines](https://opensource.creativecommons.org/contributing-code/).

**Comment by lamhoangpham20** [comment]
Thanks. Good to know that.
