### ISSUE TITLE
The distance between elements in the “Attribution tab” doesn’t follow the mockup.

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#804]
In the single result page, attribution tab, the distance between sections should be `24px`. The sections ares:
1. Section title.
2. Attribution information as rich text.
3. Html information.
4. Link to the survey.
5. Verify at the source content.

### Current implementation
<img width="601" alt="Screen Shot 2020-03-24 at 17 44 55" src="https://user-images.githubusercontent.com/895819/77475204-33b3ea00-6df7-11ea-949d-e2229f37aff2.png">

**Comment by hemanth-hk** [comment]
I'm working on this

**Comment by samcaspus** [comment]
I kinda fixed it

**Comment by hemanth-hk** [comment]
Oops, you should have commented here
Anyways it's okay :)

**Comment by samcaspus** [comment]
will keep that in mind thanks
