### ISSUE TITLE
The layout design of Collections page doesn't follow the mockup

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#810]
The Collections page does not follow the [mockup](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A645&viewport=294%2C377%2C0.7013667225837708). The changes include:

- Background color.
- Sizes and main wrapper based on the grid.
- Text-styles.
- The style of cards.
  - Card's name.
  - Text style for Collection size content.

**Comment by koiranos** [comment]
Hi there, I would like to work on this issue but I cannot see the mockup file. The page shows 404. Could you please give me more information about it?

**Comment by kgodey** [comment]
@koiranos I fixed the permissions for the mockup, can you try again?

**Comment by cangreja533** [comment]
can i work on this issue ?

**Comment by koiranos** [comment]
@kgodey Everything is good! Can I work on it?

**Comment by kgodey** [comment]
Anyone is free to submit a PR for issues marked "help wanted", you don't need our permission or assignment. Please read our [contribution guidelines](https://opensource.creativecommons.org/contributing-code/).

**Comment by koiranos** [comment]
@kgodey Ok thanks!
