### ISSUE TITLE
Filtering on CC BY shows other licenses as well

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-frontend#82]
Steps to reproduce

1. go to https://ccsearch.creativecommons.org/search?q=Cat&provider=500px&li=by&lt=
(notice I filtered on CC BY)
2. Click on an image
(Notice that other more restrictive license applies, you might have to try a few images)

When filtering on CC BY I expect only getting those images that are licensed as such.

**Comment by aldenstpage** [comment]
Hi Maarten, thanks for the report! Your query should work correctly now.

Fixed in API v0.16.1
