### ISSUE TITLE
Load More Results button should be small for mobile users for better experience.

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#836]
## Problem Description
Now the load more results button in mobile is as big as it is shown in desktop version.

## Solution Description
Load More Results button should be small somewhat for mobile users for better experience.

![Screenshot_20200328-025107__01__01](https://user-images.githubusercontent.com/55599878/77802602-3c2f4d80-70a1-11ea-9105-a3c05a6c0a47.jpg)

## Additional context
Want to work on this :)

**Comment by amycruz97** [comment]
I want to work on this

**Comment by amycruz97** [comment]
I want to work on this

**Comment by amycruz97** [comment]
i am working on it

**Comment by kgodey** [comment]
@panchovm could you review this please?

**Comment by panchovm** [comment]
It looks like a good idea. Although this is button is a component that might affect many other pages. I agree with having a responsive change but would like to see opinions from @hugosolar and @dhruvkb

**Comment by hugosolar** [comment]
@brenoferreira do you think this can be accomplished by using Bulma's responsive features? I'm not sure about how you're using it in Vue but I think it could be a better approach to that... maybe using [Responsive mixins](https://bulma.io/documentation/overview/responsiveness/)

**Comment by kgodey** [comment]
Marking this help wanted since Francisco approved it, solutions can be evaluated in code.

**Comment by abhisheknaiidu** [comment]
@kgodey Already @amycruz97 has made a PR #839 regarding this

**Comment by amycruz97** [comment]
Please what is the update on the PR.

**Comment by brenoferreira** [comment]
<img width="1688" alt="Screen Shot 2020-04-29 at 16 19 33" src="https://user-images.githubusercontent.com/707019/80637386-4bedd900-8a35-11ea-8f2d-3a7c69c90461.png">

I think this looks better as a small button even on desktop. Can we change it to make it small on both desktop and mobile?

**Comment by panchovm** [comment]
For desktop version lets use `normal` style, but for mobile the `small` style.

**Comment by amycruz97** [comment]
can i work on it

**Comment by abhisheknaiidu** [comment]
Yess @amycruz97 , since you are the one who first opened PR, you should only make the requested changes in your existing PR 🙂

**Comment by abhisheknaiidu** [comment]
Are you still working on this @amycruz97 ? If not I'll make a PR!

**Comment by amycruz97** [comment]
You can go ahead pls... I got caught up with workload
