### ISSUE TITLE
Modify about page to use API

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#84]
Modify about page to use api for displaying provider statistics.

**Comment by sebworks** [comment]
Closed in #100

**Comment by janeatcc** [comment]
These seems to be broken as with today's release this page did not update. @aldenstpage can you advise?

**Comment by janeatcc** [comment]
e.g. I don't see Cleveland in there

**Comment by brenoferreira** [comment]
@aldenstpage @sclachar it would be nice to have the web page address in the DB table too. But while that's not done, I'll just do a quick update and manually add those to the about page

**Comment by kgodey** [comment]
This is fixed.
