### ISSUE TITLE
Updates to Results Page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#845]
We want to make some changes to the Results page in CC Search.

These changes apply only to the Filter side bar on the Results page. 

Reference the following screens in Figma when going through the list, to understand what these changes entail:
Results commercially
Results modify
Results license (for modal)
License Filter update

See mockups in [Figma](https://www.figma.com/file/0tnxdVJPRUhDJCN0LO8P5d/Mockup---Sprint-2?node-id=0%3A286).

These are the changes we want to implement:

- [x] Move the expand/collapse filter icon into the Filter side bar when expanded. (It is currently to the right of the side bar, in line with the search bar). (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [x] Add title to Filter side bar: “Filter results by”. (Complete: https://github.com/creativecommons/cccatalog-frontend/pull/867)

- [ ] Allow users to filter by both Use and License
- [ ] -- If “Use commercially” is checked, NC licenses should not be available for selection from License filter.
- [ ] -- If “Modify or adapt” is checked, ND licenses should not be available for selection from License filter.

This was being addressed in https://github.com/creativecommons/cccatalog-frontend/pull/867 but there was a misunderstanding regarding the proposed functionality.

- [x] Update the License filter, to include the License icons, as well as the License abbreviation, for example as shown in the “License Filter update” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

- [x] Add question mark icon to each license, with modal on hover, which shows bullets per license, styled as indicated in “Results license” screen. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989 but there are some styling issues, which will be dealt with separately: https://github.com/creativecommons/cccatalog-frontend/issues/1047)

- [x] Add visual indicators to Aspect Ratio filter, for tall, wide, square, as shown in mockup. (Done: https://github.com/creativecommons/cccatalog-frontend/pull/989)

Please note that we do not want to change the background color of the Filter side bar, that should remain as it currently is.

**Comment by abhisheknaiidu** [comment]
@annatuma Want to work on this :)
And @annatuma by the way I already added Modal to filter form for Mobile users, could you once review that also!

**Comment by AyanChoudhary** [comment]
@annatuma I would like to take this up.

**Comment by abhisheknaiidu** [comment]
@AyanChoudhary As you can see I already shown interest first, so I am supposed to be assigned, right ?

**Comment by devRD** [comment]
In the proposed set of changes, the first point proposes that the expand/collapse filter icon be moved to the Filter sidebar. If clicking on the toggle icon collapses the filter sidebar, how will the user expand it back if the whole sidebar is collapsed? (Or am I missing something?)

**Comment by abhisheknaiidu** [comment]
@devRD No, I guess we need to make a new sticky div above the filters form and it should be aligned with the search input. So now if someone toggles icon also, then form only collapses but the icon div stays sticky!

Actually this issue, should be fixed after solving #684 
and since I showed up the interest first here, so I'm supposed to get assigned!

**Comment by devRD** [comment]
@abhisheknaiidu Hmm, that makes sense. You indeed showed interest I see, but it has been inactive for around a week so I thought I might just do it. :)

**Comment by abhisheknaiidu** [comment]
@devRD Thanks,but as I said I'm just waiting for #684 to get fixed first then I can work on this :)

**Comment by kgodey** [comment]
@abhisheknaiidu @devRD we are no longer assigning people to things, anyone is welcome to send a PR for issues marked "help wanted", regardless of issue activity. you are free to work it out between yourselves if only one of you wants to submit a PR, but we do not mind multiple PRs.

**Comment by krysal** [comment]
Guys I think that more than one person can work on this issue, there are several points to address. For example, one can take the _Add question mark icon to each license_ point and other can work on _Add visual indicators to Aspect Ratio filter, for tall, wide, square_. 
It's just a suggestion, I already made a PR to the first two points and will be working on the third!

**Comment by abhisheknaiidu** [comment]
@krysal Sounds cool. but how can we suppose to move forward? Should we need to make a new PR for the changes or can we allow to make changes in your branch only?

**Comment by krysal** [comment]
Kriti said there is no problem with multiple PRs so I believe this is the way to go.
Just remember to say what you will be working on to avoid duplicate efforts :)

**Comment by abhisheknaiidu** [comment]
okayy @krysal , I'll be working on 4,5 and 6 points!

**Comment by devRD** [comment]
Can I work on the 3rd feature of the filter sidebar if it's not taken already?

**Comment by abhisheknaiidu** [comment]
@devRD Don't you see, @krysal already said that she's working on it!

**Comment by krysal** [comment]
Yes, @devRD the third feature is done, with the PR of @abhisheknaiidu this issue should be completed now.

**Comment by annatuma** [comment]
@krysal @abhisheknaiidu thanks for your work on this, I've left feedback in each pull review with some changes that need to be implemented before code review.

**Comment by annatuma** [comment]
@zackkrida there's only one item left on this, so I'm pulling it into "Ready for Development" and we'll include it in the next sprint.

Also noting that it's worth looking at the PR referenced in the ticket above (I updated the description) because I believe some of the remaining functionality for the interaction between Use and License filters was already built.
