### ISSUE TITLE
Convert User Flag UI from Moqups to Figma

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#851]
We have a wireframe in Moqups for a new UI in CC Search:
[Moqups](https://app.moqups.com/OD23yiSWK9/edit/page/a3da463b6)

We'd like to create this in Figma, using our Design Library, to ensure seamless implementation.

Once completed, this will unblock https://github.com/creativecommons/cccatalog-frontend/issues/425

**Comment by panchovm** [comment]
[Here is the flow](https://www.figma.com/file/LR3KYeaqVkDYmgNm1rnsHx/Mockup---Sprint-1?node-id=0%3A335&viewport=45%2C154%2C0.06598864495754242) of flagging content. The mockups use Design Library components.
