### ISSUE TITLE
Tooltip is not aligned under downloads section

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#854]
## Problem Description
Tooltip present under the downloads section is not well aligned

## Solution Description
It should be aligned properly

![tool](https://user-images.githubusercontent.com/55599878/78456779-55e51c00-76c3-11ea-9744-8e010b7d7dda.png)

## Additional context
Want to work in it, if CC Staff thinks its a legit issue.

**Comment by hemanth-hk** [comment]
The text is centered and everything looks good to me, can you explain a little bit about what you mean by the alignment? @abhisheknaiidu

**Comment by abhisheknaiidu** [comment]
@hemanth-hk see the tooltip icons carefully, it's not aligned with the text!

**Comment by hemanth-hk** [comment]
I don't think that's an issue, usually, the help-symbol or the references are superscripted like we have it in Wikipedia. So a same kind of design pattern may be followed here but I may be wrong so I guess you need to wait for a review from the designer who proposed this :)

**Comment by abhisheknaiidu** [comment]
@hemanth-hk I agree with you, but in our case its icons and not numbers, numbers look better and more advised to be superscripted like you said in Wikipedia. 
Suppose, we are making icons also superscripted, I believe it should be just after the text and not after 2-3 blank spaces and then making!

**Comment by hemanth-hk** [comment]
Ya, that's what I was telling that you need to wait till someone reviews it

**Comment by abhisheknaiidu** [comment]
@hemanth-hk Yea I know Man, no need to tell!

**Comment by brenoferreira** [comment]
The download section will be removed (#860), so we don't need to fix this
