### ISSUE TITLE
help links on homepage overlaps on medium screen

### ISSUE THREAD

**Issue by Abbas-000** [creativecommons/cccatalog-frontend#856]
## Describe the bug
The line contains two links on the left side of check-boxes are overlapping with the check-boxes on 
the medium screens.

## To Reproduce

1. Go to [homepage](https://ccsearch.creativecommons.org/)
2. resize the window 
3. take a close look on the line beside the check-boxes

## Expected behavior
The following should happen

- on medium screen the line should not overlap with the check-boxes

- or should come below the check-boxes

## Screenshots

![cc-issue-1](https://user-images.githubusercontent.com/25281338/78468167-69799c80-772e-11ea-91a5-fae1769c12ec.PNG)

## Desktop (please complete the following information)
 - OS: Microsoft Windows 10 pro Education
 - Browser: chrome
 - Version: Version 80.0.3987.149 (Official Build) (64-bit)

**Comment by abhisheknaiidu** [comment]
@Abbas-000  Yess, After design sprint 1 (#723) was merged, the links on homepage overlap when window screen resizes

**Comment by abhisheknaiidu** [comment]
@Abbas-000 If you're not interested in working on this, can I take it?

**Comment by annatuma** [comment]
This is approved to be worked on, so if @abhisheknaiidu or @Abbas-000 would still be interested in fixing this, please do. Thank you for reporting the issue.

**Comment by abhisheknaiidu** [comment]
@annatuma I found that @devRD has already made a PR regarding this!

**Comment by techievivek** [comment]
@annatuma help-links should be below or above the license-filter?

**Comment by abhisheknaiidu** [comment]
@techievivek It should be present below the license-filter! and @Abbas-000 already fixed it correctly I guess.

**Comment by techievivek** [comment]
Just by changing the value of bottom will help us achieve what is expected, so won't that be a better solution? I have tested it locally and it's working fine.

**Comment by abhisheknaiidu** [comment]
@techievivek yess, why don't you suggest these changes to @Abbas-000 in his PR. Then he can make those suggested changes.
