### ISSUE TITLE
Two tooltips appear simultaneously in the download section

### ISSUE THREAD

**Issue by hemanth-hk** [creativecommons/cccatalog-frontend#857]
## Describe the bug
So in the download section of the image-view page, there are tooltips for helping out the user and they appear when you click on the `?` icon however when you click the second one the first one remains and it's hard to read both of them

## To Reproduce
1. Go to cc search locally that's `localhost:8443`
2. Search for something, say `kittens`
3. Click on any image
4. Go to the download section and click on both the tooltip triggers
5. See error

## Expected behavior
Only one tooltip should appear so if the user clicks on another one the later one should close

## Screenshots
![2tooltips](https://user-images.githubusercontent.com/43946715/78501080-ca799280-7777-11ea-8eab-93de6534d812.png)
## Desktop (please complete the following information)
 - OS: Ubuntu 19.10
 - Browser Chrome
 - Version 80.0.3987.162

## Additional context
I want to work on this : )

**Comment by abhisheknaiidu** [comment]
Since we have just two tooltips only, we can just rotate the direction of 2nd tooltip, I guess it will then solves the issue of reading, rather than what you are saying! @hemanth-hk 
because afterall it's a **tooltip** only!

**Comment by hemanth-hk** [comment]
Ya, basically they should not overlap :)

**Comment by brenoferreira** [comment]
The download section will be removed (#860), so we don't need to fix this
