### ISSUE TITLE
CC0 3.0 does not exist

### ISSUE THREAD

**Issue by mzeinstra** [creativecommons/cccatalog-frontend#87]
Seems like a fault in the dataset (also unsure if I should post it here).

1. Go to https://ccsearch.creativecommons.org/photos/9540075
2. Notice the CC0 3.0 sign on the right. 
There is no cc0 3.0 there is only 1.0

For bonus points:
3. Click on CC link
Notice that this is a 404, of course.

**Comment by sebworks** [comment]
Closed in #100

**Comment by mzeinstra** [comment]
Issue should not be closed in my opinion. 

1. Go to https://ccsearch.creativecommons.org/photos/9540075
2. Notice the CC0 3.0 sign on the right.
There is no cc0 3.0 there is only 1.0 

CC0 3.0 should never appear on ccsearch.

Only bonus points have been solved ;)
