### ISSUE TITLE
Hamburger in navbar should be aligned correctly

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#871]
## Describe the bug
The hamburger present in the navbar should be aligned correctly little bit right to the page
It makes a somewhat bad user experience now!

![or](https://user-images.githubusercontent.com/55599878/79039940-6e44c180-7c02-11ea-94d4-01372e752b50.png)

## Expected behavior
![ex](https://user-images.githubusercontent.com/55599878/79039914-3a699c00-7c02-11ea-802b-303448105c58.png)

## Desktop (please complete the following information)
 - OS: Ubuntu
 - Browser: Chrome
 - Version (ex. 22)

## Additional context
Want to work on this :)

**Comment by annatuma** [comment]
I'm not able to replicate this in Chrome or Safari on Mac OS. Could this be Ubuntu specific?

Happy for this to be fixed, as long as it doesn't impact the correct behavior on other browsers/operating systems.

**Comment by zackkrida** [comment]
Hello @abhisheknaiidu! Are you still seeing this issue in your browser/OS? If so, please feel free to contribute a PR. I personally have not been able to replicate this bug. Thank you!

**Comment by abhisheknaiidu** [comment]
@zackkrida No, it's fine now. I think this has been fixed.
