### ISSUE TITLE
Bottom to Top button should also be present in Photodetails Page for mobile users

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#872]
## Problem Description
Bottom to Top button should also be present in Photodetails Page! Since it contains Related Images section, that somewhat increases the length of the page.

![Screenshot_20200412-232512__01](https://user-images.githubusercontent.com/55599878/79076195-dc2ddd80-7d15-11ea-8dd8-a7b307dcfdd1.jpg)

## Additional context
Want to work on this :)

**Comment by hemanth-hk** [comment]
I don't think this is required
 - On the desktop, there is no point in keeping that button
 - On tablets or mobile resolutions, the related images are fairly minimum that we can go to the top in just one swipe

Do wait for the opinions of members and other contributors :)

**Comment by abhisheknaiidu** [comment]
@hemanth-hk Yes, I agree that there's no point in keeping it in Desktop version, but it needs to be there in Mobile version especially, there it will enhance both user experience and usability!

**Comment by hemanth-hk** [comment]
Maybe it will increase the user experience but I'm not positive on it because as I said the number of related images is less and we can go to the top just in 1 swipe.

**Comment by annatuma** [comment]
I'm inclined to agree with @hemanth-hk here, there is a limited number of related images, so this seems unnecessary.

That said, I'd like to input from @brenoferreira and @akmadian regarding the usability angle here. Blocking this from being worked on until we've discussed it further.

**Comment by akmadian** [comment]
On the vast majority of mobile devices, tapping the top of the screen scrolls you back up to the top, so this functionality is already implemented from the mobile os side. I'm not sure how that functionality works in terms of accessibility though, so this may or may not be a good idea from an accessibility standpoint.

As for improvements to the UX, I don't think this is a good idea. Adding something to the screen that isn't needed is generally not a good idea, especially on smaller screens.

**Comment by annatuma** [comment]
Thanks for your input @akmadian 

I'll assign this to @AyanChoudhary so this is included in their upcoming work, one way or another.

**Comment by AyanChoudhary** [comment]
Yes, I agree with @akmadian this isn't necessarily related to user accessibility but definitely concerns the UX. @annatuma it would be great if a design mockup could be provided for it.

**Comment by brenoferreira** [comment]
The reason for the Back to Top button on the results page is just for convenience when users have scrolled maybe 5+ pages down. Users can always just hit the `Home` button on their keyboard, and on mobile tap the top of the screen does something similar, like @akmadian said.

Since the details page isn't that long, I don't think this is necessary.

**Comment by akmadian** [comment]
Closing because the consensus for this suggestion seems to be that we do not want to move forward with an implementation.
