### ISSUE TITLE
Filter sidebar spacing.

### ISSUE THREAD

**Issue by devRD** [creativecommons/cccatalog-frontend#875]
## Describe the bug

The features `Search By Creator` and `Clear Filters` look odd as they lack proper spacing between the footer.

## To Reproduce

1. Search for something.
2. Go to Results Page.
3. Scroll down to the end of the filter sidebar.
4. See error.

## Expected behavior

There should be proper spacing between the filter features and the footer.
![Screenshot from 2020-04-15 21-14-12](https://user-images.githubusercontent.com/35831931/79357891-38833e00-7f5e-11ea-8296-6723ba1e2f58.png)
![Screenshot from 2020-04-15 21-14-23](https://user-images.githubusercontent.com/35831931/79357899-3a4d0180-7f5e-11ea-8392-22907c9b1846.png)

### Current Behaviour

There isn't proper spacing between the filter features `Search By Creator` and the `Clear filters` button.

![Screenshot from 2020-04-15 20-54-06](https://user-images.githubusercontent.com/35831931/79357307-7895f100-7f5d-11ea-98e2-26da667efb32.png)
![Screenshot from 2020-04-15 20-53-56](https://user-images.githubusercontent.com/35831931/79357325-7d5aa500-7f5d-11ea-92a3-2e33a1a82905.png)

## Desktop
 - OS: (ex. iOS) Fedora 31
 - Browser (ex. chrome, safari) Google Chrome
 - Version (ex. 22) 80

## Additional context

I would like to take up this issue if reasonable. :)

**Comment by abhisheknaiidu** [comment]
It works fine for me @devRD in both chrome and firefox

`Chrome`

![chrome](https://user-images.githubusercontent.com/55599878/79367118-f0b6e380-7f6a-11ea-8e5e-afcb1695ee98.png)

`Firefox`

![mozilla](https://user-images.githubusercontent.com/55599878/79367162-05937700-7f6b-11ea-9a51-de5b113302e5.png)

**Comment by annatuma** [comment]
Replicated in Firefox 74.0.1

It is possible this will be addressed by the upcoming changes to the filter section:
https://github.com/creativecommons/cccatalog-frontend/issues/909

Leaving this ticket open though. If this issue is fixed before we make changes to the filter section that's fine. Regardless we should verify once changes are in that this behavior does not continue.

**Comment by zackkrida** [comment]
This was resolved by recent design updates to the filters. Thanks all!
