### ISSUE TITLE
Texts not aligned on Search Page

### ISSUE THREAD

**Issue by GeekBoySupreme** [creativecommons/cccatalog-frontend#883]
## Describe the bug
The redirect link to go back to Legacy Portal and search syntax guide are unaligned with respect to the rest of the body elements. It is just floating to the left of the page.

## To Reproduce
1. Go to https://ccsearch.creativecommons.org/ on a Computer

## Expected behavior
As every other content in the page barring the Header and Footer are center-aligned, these texts should be too.

## Screenshot
<img width="635" alt="Screenshot 2020-04-17 at 4 29 21 PM" src="https://user-images.githubusercontent.com/15321738/79563251-0858ae00-80ca-11ea-9ca8-564f29d997f4.png">
<img width="1180" alt="Screenshot 2020-04-17 at 4 41 38 PM" src="https://user-images.githubusercontent.com/15321738/79563394-5bcafc00-80ca-11ea-9684-46cdadc9028a.png">

## Desktop (please complete the following information)
 - OS: macOS Catalina
 - Browser: Chrome, Safari, Firefox
 - Version: Chrome 81, Firefox 74

## Additional context
The links should have been either aligned center to maintain a hierarchy or be close to the Footer or any other element. As of this moment, they are just floating around.
In a non-full-screen Firefox, the links even overlap - 
Ref- 
<img width="1061" alt="Screenshot 2020-04-17 at 4 45 30 PM" src="https://user-images.githubusercontent.com/15321738/79563755-03e0c500-80cb-11ea-9b9e-377f3a0a7285.png">

**Comment by abhisheknaiidu** [comment]
I think this is the duplication of issue #856 , and its already fixed in #870

**Comment by GeekBoySupreme** [comment]
Hey, thanks for looping this in. 
The PR resolves the overlap. Opened this issue to address the alignment, if that can be fixed.

**Comment by akmadian** [comment]
What was the screen resolution used in the screenshots?

**Comment by GeekBoySupreme** [comment]
For the Overlap, the screen size ranged from - 897*610 to 904*610 (in Pixels)
The alignment issue is always there, irrespective of Screen Size.

**Comment by brenoferreira** [comment]
This was fixed in #890 
Thanks for your contribution.
