### ISSUE TITLE
Elements not loading properly when running in localhost

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#884]
## Describe the bug
Some of the Vocabulary elements not loading properly

## Screenshots

`Arrows are missing`

![nw3](https://user-images.githubusercontent.com/55599878/79677558-57a8f680-8210-11ea-8d28-ac5b34324e7c.png)

![nw2](https://user-images.githubusercontent.com/55599878/79677569-89ba5880-8210-11ea-9f06-e0714182049d.png)

`I tried in some of my other branches also, results remains the same - `

![nw1](https://user-images.githubusercontent.com/55599878/79677566-7dce9680-8210-11ea-888c-e95a9b0ad005.png)

**Comment by devRD** [comment]
It seems to be working fine for me in my localhost.

![Screenshot from 2020-04-19 12-21-01](https://user-images.githubusercontent.com/35831931/79681522-889d2180-8238-11ea-938f-cf54005f61e2.png)

**Comment by abhisheknaiidu** [comment]
Yup, Now its working fine, I guess it might be because of the new footer that's being updated!

**Comment by abhisheknaiidu** [comment]
Oh, but it seems to be an issue now also, did you checked after fetching the latest commits ?

**Comment by devRD** [comment]
Yes, I just fetched the latest changes and tested again. It seems to be working alright. 

![Screenshot from 2020-04-19 13-53-14](https://user-images.githubusercontent.com/35831931/79683100-44644e00-8245-11ea-883d-5d6c1164bf78.png)

**Comment by krysal** [comment]
I updated my repo too and arrows are present. Is any other element missing?

**Comment by abhisheknaiidu** [comment]
Thanks, It's better to close this issue then
