### ISSUE TITLE
License Language Improvements to Single Result Page

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#889]
We are going to make changes to the Single Result Page, to improve license explanations, attribution options, and introduce a clearer CTA for users to access the image they're viewing.

- [ ] [The reuse tab design is here](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60) and the [updated license description language is here](https://docs.google.com/document/d/14NoqosLebbIIZFR9y7e0-qJsqHO1lelZwZl2J0MBDE4/edit)

- [ ] We need to create another custom event in Google Analytics for "Go to Source". We currently track "Attribution" as an event, to indicate that someone has copied our attribution code. This event should not be lost, but should now record when someone clicks on "Copy ...." in the attribution tool. [Information on setting up events](https://developers.google.com/analytics/devguides/collection/gtagjs/events)

- [ ] Note that the location of the User Reporting flag changes in this design, to be under the image on the far left, visible regardless of which tab the user selects.

**Comment by Arunhari333** [comment]
Could I work on this issue?
