### ISSUE TITLE
Add External Link to Extension Page in Navbar

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#892]
The CC Search Extension page is now live:
https://opensource.creativecommons.org/ccsearch-browser-extension/

We'd like to link to it from the CC Search navbar.

Because it is an external link we should:
1) Open it in a new tab
2) Use the ("External Link" icon)[https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=3%3A9] from the Design Library

For now let's place it on the far right of the navbar.

**Comment by abhisheknaiidu** [comment]
I want to work on this @annatuma

**Comment by DantrazTrev** [comment]
Wouldn't it be better if there was a text beside it stating it's purpose . Rather than just being an external redirect icon

**Comment by abhisheknaiidu** [comment]
@DantrazTrev yess, I already mentioned about this, in my PR!

**Comment by kgodey** [comment]
I'm pretty sure @annatuma meant that the link should say "Extension" with the icon next to the text.

**Comment by annatuma** [comment]
Yes, apologies for not making that clear.

It should be "Extension [external link icon]".

Thanks @kgodey for clarifying.

**Comment by abhisheknaiidu** [comment]
@annatuma  @kgodey  So, which will be clickable? link icon or both Extension with link-icon?

**Comment by kgodey** [comment]
@abhisheknaiidu both

**Comment by abhisheknaiidu** [comment]
Done @kgodey
