### ISSUE TITLE
No information about the file type 

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#895]
## Problem Description
Provided that there is a filter for the category for the file type and there is no efficient way whatsoever about finding the file type , like there is in the case of other filters, it's not easy finding the file type unless it's stated .

## Solution Description
A section in the info tab stating the file type .
![screenshot](https://user-images.githubusercontent.com/43457420/80306526-7f382a00-87e1-11ea-99ec-a846888a5b5c.png)

## Additional context
Although it's possible to find the file type in the attribution , but it's not a good idea considering not everyone can find it

**Comment by dos077** [comment]
There is a filter option for file type.
![Screenshot 2020-04-30 at 4 42 26 PM](https://user-images.githubusercontent.com/45016741/80757360-0b0fc600-8b02-11ea-9cc9-0900769e4f83.png)

But the search result objects do not include that. Simple addition of a computed property capturing the extension from the URL can be a short term fix, but the best practice, I believe, is for the back-end side to include MIME Type in the result object. Here's the quick fix I wiped up:
![Screenshot 2020-04-30 at 4 41 53 PM](https://user-images.githubusercontent.com/45016741/80757466-3397c000-8b02-11ea-915b-8ab3c005ff85.png)

**Comment by DantrazTrev** [comment]
Yes I totally agree @dos077 with the fix . And #911 is totally the kind of fix I was thinking but ,I suggest  that we should wait for the organizational rep to continue on it . And in case you're one the repo maintainers , then yeah we should go for it its totally the correct solution

**Comment by annatuma** [comment]
Thanks for suggesting this improvement @DantrazTrev 

We are in the process of implementing an updated design to the results page, so the solution suggested by @dos077 will unfortunately not work with that design.

See: https://github.com/creativecommons/cccatalog-frontend/issues/889 and https://github.com/creativecommons/cccatalog-frontend/pull/916

Once the new design is live (likely next week) @dos077 you are welcome to suggest a fix. Also flagging @panchovm to think about where file type could be cleanly included.

**Comment by panchovm** [comment]
Thanks for the suggestion. I will include it in the new mockups that we are designing.

**Comment by zackkrida** [comment]
Closing, as this is addressed in #1049 and will be fixed soon.
