### ISSUE TITLE
(Research required) Orientation bug creating inconsistency in the search results and single results page

### ISSUE THREAD

**Issue by DantrazTrev** [creativecommons/cccatalog-frontend#898]
## Describe the bug
The image in the search page is in portrait orientation ,while the image when opened results to a landscape one . Not sure if this is image specific but the bug is still there. More cases need to reported to understand the behaviour 

## To Reproduce

1. Search bts 
2. Set image size filter as large 
3. Find File:Bangkok BTS (31067429086).jpg
4. See that it's in portrait orientation
5. Click on the image
6. See in the image orientation to be changed 

## Expected behavior
The orientations should match although this could be an image specific bug 

## Screenshots
![#3](https://user-images.githubusercontent.com/43457420/80372007-6e0a1e80-88b0-11ea-976e-0c15637fb374.png)

![#4](https://user-images.githubusercontent.com/43457420/80372017-73676900-88b0-11ea-985f-53990307021f.png)

## Desktop (please complete the following information)
 - OS: macOS 10.15
 - Browser Safari
 - Version: 13.0.2

## Additional context
This could be an image/ device specific bug . More cases would be needed to verify

**Comment by annatuma** [comment]
I'm able to replicate the issue for this photo specifically, but not elsewhere.

Adding "help wanted", and noting that this is a **research required** issue, meaning I'd like this bug to be fully researched and understood before a solution is proposed.

I'm putting this in our Parking Lot, as this isn't urgent to solve, given that we only have one case at present. We can prioritize this if a consistent pattern is found.

**Comment by zackkrida** [comment]
This is resolved for the image in question. If an issue like this is found again we should defer to the catalog/api repos and create an issue there. The original issue appears to have been a discrepancy between the thumbnail and the full-size image, not an issue with this repo. 

Thanks for reporting @DantrazTrev
