### ISSUE TITLE
Feedback is not persistant for a given query.

### ISSUE THREAD

**Issue by techievivek** [creativecommons/cccatalog-frontend#899]
## Describe the bug
Even after providing the feedback for a given query result, it keeps asking for feedback. Please refer to gif below.
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/35863227/80399591-1632de00-88d7-11ea-8295-b2d49f86a6fc.gif)

## To Reproduce

1. Search any query on [CC search website](ccsearch.creativecommons.org/).
2. Submit the feedback.
3. Click on any image and move back to the search result page, the feedback is still there.

## Expected behavior
Once a user submits a feedback for a **given query** this should close the popup for that query.

## Screenshots
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/35863227/80399591-1632de00-88d7-11ea-8295-b2d49f86a6fc.gif)

## Desktop (please complete the following information)
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version (ex. 22)

## Smartphone (please complete the following information)
 - Device: (ex. iPhone6)
 - OS: (ex. iOS8.1)
 - Browser (ex. stock browser, safari)
 - Version (ex. 22)

**Comment by krysal** [comment]
The current state and the expected behavior gif are the same.

**Comment by abhisheknaiidu** [comment]
@krysal No, I think he added the gif under the `Screenshots` section and not under `Expected behavior`

**Comment by techievivek** [comment]
@krysal Yes, as Abhishek said.

**Comment by akmadian** [comment]
I think this would be a good idea on the surface, but it would likely require some client side storage with cookies or similar which I don't like the idea of. I'm not sure if we have some sort of policy about client side storage or cookie use though, so I'll defer to @brenoferreira. Pending his approval, you can go ahead and get started :)

**Comment by krysal** [comment]
Oh, I see, my bad... What about saving the answer in the Vue store? Since new images are added and the cccatalog is reindexed results could vary I think.
