### ISSUE TITLE
Modify data model to track image views 

### ISSUE THREAD

**Issue by sebworks** [creativecommons/cccatalog-frontend#9]
In order for the UI to display metrics such as "trending" and "popular", we need to track image views via the data model. 

@aldenstpage

**Comment by dhruvkb** [comment]
This issue seems very closely linked to creativecommons/cccatalog-api#102. The changes to the model required in the case of this issue are akin, to some extent, to the ones that would be needed to make this feature possible.

**Comment by aldenstpage** [comment]
We're tracking views on the back end now
