### ISSUE TITLE
Add Logo Section to Homepage

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#908]
We'd like to add a non-clickable section of logos on the CC Search homepage, with movement from left to right. This should be a logo transition of the collections available on CC Search to the homepage.

Here is an example of the expected behavior. There is a single set of logos with no interaction, and the speed movement should be slow. We can evaluate how it looks once it is in development.

Similar concept: [Infinite Slideshow](https://codepen.io/chriscoyier/pen/EyxPPm)

[Homepage Design with Logo Scroll](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=0%3A1)

**Comment by abhisheknaiidu** [comment]
Can I work on this @annatuma ?

**Comment by Arunhari333** [comment]
Could I work on this?

**Comment by Tanuj22** [comment]
@annatuma `Homepage Design with Logo Scroll` link is giving a 404 error.

**Comment by ritiktaneja** [comment]
Can I work on this issue @annatuma ?

**Comment by krysal** [comment]
Anyone who wants is welcome to contribute, currently the mockup is open, feel free to work on this.

**Comment by zackkrida** [comment]
Basic implementation can be found here: https://github.com/creativecommons/cccatalog-frontend/pull/926

If @ritiktaneja or @Tanuj22 want to take a look, since you were interested in contributing, please do so! Thanks.

**Comment by Tanuj22** [comment]
@zackkrida I hadn't actually started working on this yet. Please feel free to continue with your PR!

**Comment by annatuma** [comment]
Just noting that we've discussed some concerns around the scrolling functionality, and at this time loading a static file instead seems to make sense. We can discuss in more detail during sprint planning.
