### ISSUE TITLE
Results Page Filter Expanded State (A/B Test Required)

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#909]
As part of Design Sprint 3, which focuses on License Language Changes, we're making a number of changes to the Filter section on the Results page.

One of those changes is that we'd like the filter section to be permanently expanded (i.e. no capability to minimize/collapse), and it should have its own scroll, meaning a user can scroll through the filter section independent of scrolling through image results.

We want to run an A/B test on the "permanent expansion and independent scrolling" version of the filters, versus the current "expand/collapse and page scrolling" version. The actions we'd like to measure are:
1) Searches executed
2) Filters selected

The ideal outcome is that there is equal or more engagement with filters on the new version.

**Comment by brenoferreira** [comment]
@annatuma can you elaborate on this AB test? What are we trying to measure?

**Comment by DantrazTrev** [comment]
@annatuma I would like to suggest an bug/improvement in the current filter section. The current filter section when used in mobile devices does not work when the user has scrolled down , the user has to scroll up in order to use the filter in spite the filter icon visible during that period but is unusable
![image](https://user-images.githubusercontent.com/43457420/80859542-8054d580-8c7f-11ea-8230-ff77f3f5502f.png)

Like here

 Considering the A/B test is for the filter section , it would be better that this bug should be fixed first to make the test fair on both design styles of filter

**Comment by krysal** [comment]
@DantrazTrev That is a good finding, Do you want to create an issue for that problem? It will be better to discuss a solution in its own thread.

**Comment by annatuma** [comment]
Agreed with @krysal! @DantrazTrev that's a bug worth fixing before we dive into this ticket. Please create a separate issue for it.

**Comment by annatuma** [comment]
This work has not been completed. It looks like there was a misunderstanding in terms of what the desired changes were. We want _each individual filter_ to be permanently expanded (not the entire filter section).

This means that a user can show/hide the filter side bar as they please, but when they show the filter side bar, they will see the full contents of all filters at all times. We also want the filter side bar to have its own scroll.

As indicated in the ticket, we do want to ensure this doesn't lead to negative engagement with filters.

A: current version, users can expand/collapse each individual filter within the filter side bar, and scrolling only happens on the page as a whole.

B: new version, users can no longer expand/collapse each individual filter but rather the full options for each filter are always shown, and the entire filter side bar has its own scroll, so users can either scroll up and down within available filters, or up and down within the results.

@zackkrida this is also a good opportunity to learn to use Sixpack, our A/B testing framework.

**Comment by annatuma** [comment]
Also noting there's a community ticket and associated PRs tied to scrolling on the filter side bar: https://github.com/creativecommons/cccatalog-frontend/issues/689

If we complete this ticket, then that ticket and associated PRs can be closed, but perhaps worth seeing if any of those PRs already solve for this.
