### ISSUE TITLE
Update search timeout (ERROR FETCHING IMAGES: TIMEOUT OF 5000MS EXCEEDED)

### ISSUE THREAD

**Issue by aldenstpage** [creativecommons/cccatalog-frontend#912]
We should set  from the frontend, since it will also be set off by the user having a slow connection. You can't tell if the problem is server-side or client-side from the frontend. This is going to result in false alarms from users.

Also, a minority of queries straight up will take more than 5 seconds to answer depending on how complex the query is, whether anyone has searched the term before, periods of high load, a number of other possible factors... the client should instead wait for the response from the server. Canceling the request client-side does nothing to relieve pressure server-side. It may even make things worse because now the user is going to resend the same query again when we're already hard at work answering their last query. Ideally any timeouts should be set at the API level.

EDIT: the timeout should change to 30 seconds, and not remove it altogether. In the UI, the time should be displayed in seconds instead of milliseconds

**Comment by vane** [comment]
Maybe it will be better to retry operation on timeout error inside axios interceptor and at least once double timeout time.
