### ISSUE TITLE
Audit and Update Google Analytics Setup

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#913]
Something isn't properly set up in Google Analytics, when comparing Prod and Dev data.

Contracted with expert via Upwork, will be worked on in June 2020. Will put any necessary code updates in tickets as they arise.

Related tickets:
https://github.com/creativecommons/cccatalog-frontend/issues/1027

**Comment by zackkrida** [comment]
Hi Anna, something that may be of use here...

The site currently checks to see if it should use the production or development Google Analytics account via checking the url for `ccsearch.`, the previous domain. This means that https://search.creativecommons.org is using the development GA code and https://ccsearch.creativecommons.org is using the production version.

<img width="1920" alt="Screen Shot 2020-05-27 at 9 19 20 AM" src="https://user-images.githubusercontent.com/6351754/83023958-9e51f380-9ffb-11ea-95f5-60f0946298c6.png">

The source code of this issue can be viewed here: https://github.com/creativecommons/cccatalog-frontend/search?q=gaID&unscoped_q=gaID

**Comment by annatuma** [comment]
Thanks @zackkrida for digging in - there's a ticket to get it fixed now!

**Comment by zackkrida** [comment]
The prod and dev data descrepancy was fixed via #1027 — in the future we may make a new issue for enhancements to tracking metrics.
