### ISSUE TITLE
Add meta image search to CC Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#922]
See https://github.com/creativecommons/cccatalog-frontend/issues/921 for background.

Implementation:
1. Add link below "Load more results" that says "Not finding what you need? Search other sources".

See ['image results' mockup in Figma](https://www.figma.com/file/jlDHPOrQPvP2DtbJRWmDyM/Old-CC-Search-integration?node-id=270%3A953).

2. Upon click, load modal. Modal functionality is as such:
- User enters search query in search bar
- User can select one or both available filters
- User clicks on an available source
-- Results for the source selected open in a new tab of the user's browser, which is brought into focus

See ['search other sources' mockup in Figma](https://www.figma.com/file/jlDHPOrQPvP2DtbJRWmDyM/Old-CC-Search-integration?node-id=270%3A1614) for exact design.

The sources that we want to include for v1 of meta image search are:
Google Images
Open Clip Art Library

Look at [Legacy Search](https://oldsearch.creativecommons.org/) to understand how filters are set for each of these sources currently for a meta search, and how to dynamically update those filters based on what the user has set.

**Comment by wendko** [comment]
Hi @annatuma, I'm looking into this and I just wanted to understand for point 2 

> User can select one more more sources
> Results for each source selected open in new tabs of user's browser

 If the user selects two sources and clicks search, is it going to open two tabs?

**Comment by annatuma** [comment]
@wendko that was the original intention, but after technical review we have concluded it is best to only allow for selection/opening one source at a time, therefore the functionality here will mirror the proposed functionality in https://github.com/creativecommons/cccatalog-frontend/issues/923

The ticket has been updated.

**Comment by wendko** [comment]
That's great :) Alright, I can work with that!

One more thing - if there are no image results, how should this link to extra sources be displayed? Or should it not be displayed at all?
![image](https://user-images.githubusercontent.com/12908560/82152403-7e039580-9893-11ea-9a07-4d6ea8e7b30d.png)

**Comment by tichnas** [comment]
@wendko Are you working on this issue?

**Comment by wendko** [comment]
Hi @tichnas, yes, I have made some progress on this issue but I have not completed it yet, I was waiting for clarification on the last comment.

**Comment by wendko** [comment]
Hey @tichnas due to personal circumstances, I won’t be able to work on this for a while, feel free to pick this up if you’d like

**Comment by annatuma** [comment]
Sorry about the delay folks - for the time being the messaging you suggested @wendko is fine. We may tweak it on the next iteration.

Also sorry to hear about personal circumstances, I do hope everything is alright.

**Comment by abhisheknaiidu** [comment]
@zackkrida Is any working on this?

**Comment by zackkrida** [comment]
@abhisheknaiidu me! You can see the progress here: #1050

Feel free to fork and work on any of the remaining issues in that PR. There are some todos in the text of the PR.
