### ISSUE TITLE
Add meta audio and video search to CC Search

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#923]
See https://github.com/creativecommons/cccatalog-frontend/issues/921 for background.

Implementation:
1. Add tabbed navigation to CC Search for additional content types: Audio and Video

See ['audio results' mockup in Figma](https://www.figma.com/file/jlDHPOrQPvP2DtbJRWmDyM/Old-CC-Search-integration?node-id=270%3A2236) for full design.

2. Upon clicking on Audio or Video, instead of our normal "results" page, load instead Filters with only "Use" available, and a page with source selections available.

- User enters search query in main search bar
- User can select one or both available filters from the filter side bar
- User clicks on an available source
-- Results for the source selected open in a new tab of the user's browser, which is brought into focus

The sources that we want to include for v1 of meta audio search are:
Europeana
Wikimedia Commons
Jamendo
ccMixter
SoundCloud

The sources that we want to include for v1 of meta video search are:
Europeana
Wikimedia Commons
YouTube

Look at [Legacy Search](https://oldsearch.creativecommons.org/) to understand how filters are set for each of these sources currently for a meta search, and how to dynamically update those filters based on what the user has set. Note that Jamendo's search functionality has changed, so this will need to be figured out from scratch. See also comments around sample queries here: https://github.com/creativecommons/cccatalog-frontend/issues/315#issuecomment-617463884 regarding filtering by file type as well for multimedia sources, such as Europeana and Wikimedia Commons.

**Comment by brenoferreira** [comment]
https://github.com/creativecommons/search/blob/master/search.js
