### ISSUE TITLE
No spacing in between the tags under filter-by section (Mobile breakpoint)

### ISSUE THREAD

**Issue by abhisheknaiidu** [creativecommons/cccatalog-frontend#927]
## Problem Description
No spacing in between the tags under filter-by section in Mobile breakpoint

## Solution Description
`CURRENT : `

![fby](https://user-images.githubusercontent.com/55599878/81464791-5735c700-91e2-11ea-87e7-6373026c2fe8.png)

`EXPECTED : `

![fby-m](https://user-images.githubusercontent.com/55599878/81464801-6a489700-91e2-11ea-9171-2c5f73f33173.png)

**Comment by fakela** [comment]
Can i send a PR for this?

**Comment by abhisheknaiidu** [comment]
@fakela Yess, you can! but let's wait what @akmadian and @brenoferreira has to say about this issue!

**Comment by akmadian** [comment]
I think this is a good idea, thanks for catching this :)
