### ISSUE TITLE
Server rendering renders initial state and application scripts twice

### ISSUE THREAD

**Issue by jesusbotella** [creativecommons/cccatalog-frontend#940]
## Describe the bug
When loading any page rendered by Vue Server Side rendering you can find scripts and initial state for hydration rendered twice.

## To Reproduce
1. Go to any CC Search page rendered server side
2. Open up your browser's development tools and inspect DOM nodes
3. See how application scripts and state are duplicated when rendered from server side

## Expected behavior
It would be better to render them just once to save some KBs when transferring them to the client.

## Screenshots
![Captura de pantalla 2020-05-14 a las 14 15 32](https://user-images.githubusercontent.com/4319728/81933297-6d31f600-95ed-11ea-9780-af0c29c0097e.png)

## Desktop
 - Applicable to all desktop devices

## Smartphone
- Applicable to all smartphones

## Additional context
https://github.com/creativecommons/cccatalog-frontend/blob/dec2433a0f9360227c3ba2d9f429053ce1f473ac/index-server.html#L26-L28
The HTML comment placeholder is already injecting those scripts and state, while the template is calling `renderState` and `renderScripts` at the same time.

It will not reduce much from the HTML transference (a few KBs in my local tests), but will parse and download JS files just once.

I would like to open a pull request addressing those changes if you think that this is important enough to be solved. Thank you!

**Comment by zackkrida** [comment]
Hi @jesusbotella, please go ahead and open a PR if you are still interested. We definitely do not want to continue to send users our JavaScript bundle twice. Thank you _so much_ for finding this issue!

**Comment by jesusbotella** [comment]
Sure, I'll open it tomorrow. I would have opened it before, but preferred to ask beforehand :)

**Comment by zackkrida** [comment]
One thing I noticed here @jesusbotella — I originally thought we could just remove these two lines:

https://github.com/creativecommons/cccatalog-frontend/blob/dec2433a0f9360227c3ba2d9f429053ce1f473ac/index-server.html#L27-L28

but it seems to affect some of the pages ability to render, at least in local testing.

**Comment by jesusbotella** [comment]
That's what I thought too 🤔 

Which pages are those? I can take a look at them and see what happens.

**Comment by zackkrida** [comment]
If you remove those render calls, and run locally, submit a search, and then refresh the results page, the search state seems to be lost. You can compare to the live site to see how the behavior differs

**Comment by jesusbotella** [comment]
Yes, I saw that as well :(

It seems like there's some weird behavior that makes it work the second time, but not the first. Going to give it another look today and see if I can solve it.

**Comment by zackkrida** [comment]
I do have _some_ additional info—we will be removing the separate https://github.com/creativecommons/cccatalog-frontend/blob/develop/src/pages/CollectionBrowsePage.vue route, which seems to be the main source of issue in my testing

**Comment by zackkrida** [comment]
We will fix this via a migration to Nuxt to handle our routing configuration. Marking this as blocked until then.
