### ISSUE TITLE
Create locale messages format JSON structure

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#942]
Once the Vue-i18n infrastructure is setup, the [locale message format](https://kazupon.github.io/vue-i18n/guide/formatting.html) JSON structure needs to be defined.

Because once this is setup, text changes won't be done in the components themselves, but rather in this JSON file. The structure needs some logical order so that it's easy to find in this large JSON object a particular piece of text, otherwise it quickly becomes very hard to maintain.

One possible structure could be:

```
// this is a suggested example and not the complete structure
{
  // text that could be reused on multiple components
  licenses: {
    by: "Credit the creator",
    sa: "Share adaptations under the same terms",
    ...
  },
  navbar: {
    about: "About",
    collections: "Collections",
    ...
  },
  footer: {
    ...
  },
  // then break in page and components
  
  home_page: {
    header: "SEARCH FOR CONTENT TO REUSE",
    input_placeholder: "I would like to see",
    search_button: "Search",
    ...
  },
  photo_details_page: {
    back: "Back to search results",
    tabs: {
      reuse: {
        title: "Reuse",
        license: "License",
        description: 'This image was marked with a {license} license',
        ...
      }
    }
  }
  ...
}
```

**Comment by zackkrida** [comment]
closing these in favor of the current meta issue.
