### ISSUE TITLE
Set up translation service infrastructure

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#944]
Set up the infrastructure to allow the use of the translation service https://www.transifex.com/.

It seems like the only integration provided by Transifex that could help in the case of this project is the [Github Integration](https://docs.transifex.com/transifex-github-integrations/github-tx-client), which seems to support translations in a .json file

**Comment by AyanChoudhary** [comment]
reopening, this is still pending.

**Comment by AyanChoudhary** [comment]
@zackkrida even this is done, so we can close this.
