### ISSUE TITLE
Set up locale detection on the server

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#945]
CC Search uses [Server Side Rendering (SSR)](https://github.com/creativecommons/cccatalog-frontend/blob/develop/CODEBASE.md#server-side-rendering), so it would be nice if the server renderer could detect the users' locale using the [Accept-Language](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language) header and load the appropriate locale data, if it exists.

For example:

If we have translations for English, French and Portuguese, and a user sends a request to load the CC Search homepage with the header:

`Accept-Language: fr-CH, fr;q=0.9, en;q=0.8, de;q=0.7, *;q=0.5`

fr-CH is the French - Switzerland language code, so we could load the French translations and send the response already in their browser preferred language.

If the language provided in the `Accept-Language` header doesn't match any of our available translations, the server would default to English

**Comment by zackkrida** [comment]
@AyanChoudhary, wanted to check in if you've thought much about this yet. We'd have to set the default language first with the `Accept-Language` header server-side, replace that with `navigator.language` if it is set client-side, and then finally override that default with the user's chosen language from localstorage. Basically, localstorage.locale || navigator.language || 'Accept-Language' || 'en' (in pseudocode).

**Comment by AyanChoudhary** [comment]
I was also thinking of something along those lines, I will try to set up the required things once the design is ready so that we can at least have the translations coming while I work on the locale detection.

**Comment by zackkrida** [comment]
This will depend on our possible transition to nuxt.js, so waiting and marking as blocked.
