### ISSUE TITLE
Incorrect spacing between main CTA and sentence to form

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#952]
## Describe the bug
The space between the CTA and the sentence that sends to feedback form is not correct.

## Expected behavior
The space parameter should be 8px, as indicates the [Figma mockup (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=9358%2C5775%2C1.702396035194397).

## Screenshots
<img width="509" alt="Screen Shot 2020-05-14 at 12 09 24" src="https://user-images.githubusercontent.com/895819/81959072-f0971b80-95dc-11ea-9e66-5ec49f550290.png">

**Comment by ariessa** [comment]
Hi, I've fixed this issue and created pull request [#975](https://github.com/creativecommons/cccatalog-frontend/pull/975)
