### ISSUE TITLE
The bottom-padding spacing in content section is incorrect

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#953]
## Describe the bug
The spacing used as bottom-padding in the section where the image is presented is incorrect.

## Expected behavior
The spacing should be 64px, as defined in [the mockup (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=4014%2C2158%2C0.5814259648323059).

## Screenshots
<img width="1439" alt="Screen Shot 2020-05-14 at 12 19 41" src="https://user-images.githubusercontent.com/895819/81959439-73b87180-95dd-11ea-9a0e-76a824cb5155.png">

**Comment by ariessa** [comment]
Hi, I've fixed the issue and created pull request [#978](https://github.com/creativecommons/cccatalog-frontend/pull/978)
