### ISSUE TITLE
The text styles of title sections are not correct

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#954]
## Describe the bug
The text style of sections **Tags** and **Related images** are not correct.

## Expected behavior
Those titles should be in `Heading 3B` is [the mockup indicates (Mockup S3)](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=3484%2C2112%2C0.5814259648323059).

## Screenshots
<img width="432" alt="Screen Shot 2020-05-14 at 12 48 27" src="https://user-images.githubusercontent.com/895819/81962268-7e750580-95e1-11ea-85c8-9ee60e176e28.png">

**Comment by ariessa** [comment]
Hi, I've fixed this bug and created pull request [#969](https://github.com/creativecommons/cccatalog-frontend/pull/969)
