### ISSUE TITLE
The icons of licenses should not be links

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#957]
## Describe the bug
The license's icons are links the license description. These icons should not be linked.

## Expected behavior
Show the icons without any interaction.

## Screenshots
<img width="511" alt="Screen Shot 2020-05-14 at 13 18 23" src="https://user-images.githubusercontent.com/895819/81964989-68694400-95e5-11ea-83e2-9ccd7e7c0004.png">

**Comment by ariessa** [comment]
Hi, I've fixed this issue and created pull request [#974](https://github.com/creativecommons/cccatalog-frontend/pull/974)

**Comment by zackkrida** [comment]
This has been fixed; closing this issue. Thanks all!
