### ISSUE TITLE
The title section doesn't have the correct spacing

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#958]
## Describe the bug
The section where title and author are doesn't have the correct spacing

## Expected behavior
The margin-bottom should be 24px. See [the mockup S3](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=5820%2C3973%2C1) definition.

## Screenshots
<img width="549" alt="Screen Shot 2020-05-14 at 13 29 45" src="https://user-images.githubusercontent.com/895819/81966241-3c4ec280-95e7-11ea-8bed-15562f80bd64.png">

**Comment by ariessa** [comment]
Hi, I fixed the issue and created pull request [#972](https://github.com/creativecommons/cccatalog-frontend/pull/972)
