### ISSUE TITLE
The H5 elements doesn't have consistent spacing

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#959]
## Describe the bug
The H5 elements in the right section of the image don't have the same spacing.

## Expected behavior
It should have a distance of 16px in every case. See [the Mockup - S3](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=205%3A60&viewport=5820%2C3973%2C1).

## Screenshots
<img width="573" alt="Screen Shot 2020-05-14 at 13 34 10" src="https://user-images.githubusercontent.com/895819/81966735-e9c1d600-95e7-11ea-9c17-c75fe6b72009.png">

**Comment by ariessa** [comment]
Hi, I fixed the bug and created pull request [#970](https://github.com/creativecommons/cccatalog-frontend/pull/970)
