### ISSUE TITLE
The left spacing in related image's gallery is incorrect

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#960]
## Describe the bug
There is a space on the left side of the gallery, in the related images section.

## Expected behavior
There should be no space, either the left and right sides.

## Screenshots
<img width="508" alt="Screen Shot 2020-05-14 at 13 37 43" src="https://user-images.githubusercontent.com/895819/81967034-55a43e80-95e8-11ea-9ef0-932d99064462.png">

**Comment by akanksha-v** [comment]
I have solved this issue, please review my pr #980
