### ISSUE TITLE
The grid doesn't have the spaces defined

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#961]
## Describe the bug
The layout of first section doesn't have the spaces defined for the grid in [Mockup S3](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=969%2C732%2C0.13086995482444763). 

## Expected behavior
Use the grid and the columns defined for placing elements.

## Screenshots
<img width="1440" alt="layout grid" src="https://user-images.githubusercontent.com/895819/81968868-01e72480-95eb-11ea-8cf7-c34f80e0364d.png">

**Comment by brenoferreira** [comment]
@panchovm can you provide more details as to what exactly needs to be fixed in the grid? Is it the column sizes? Gap size? It's a bit unclear

**Comment by panchovm** [comment]
Both. I can't give more details about how is implemented but comparing it with the mockup. There is a difference in columns and gap sizes.
