### ISSUE TITLE
the text style of code doesn't follow the Design Library definition

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#962]
## Describe the bug
The text style of code in the attribution tool, html tab, has a different text style.

## Expected behavior
The text style should be `code-normal` as it indicates [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A110&viewport=-651%2C-1185%2C0.6580211520195007).

## Screenshots
<img width="481" alt="Screen Shot 2020-05-14 at 14 02 54" src="https://user-images.githubusercontent.com/895819/81969253-a0738580-95eb-11ea-82c7-9b44ded518e8.png">

**Comment by akanksha-v** [comment]
I would love to work upon this, please assign it to me if it's available

**Comment by Tanuj22** [comment]
@akanksha-v You don't need to ask permission for issues makes `help wanted` or `good first issue`.

**Comment by akanksha-v** [comment]
@panchovm  Could you please link here the concerned file which needs to have changes

**Comment by panchovm** [comment]
The bug appears in every single result page, attribution toolbox. You can search for any image to see the implementation

**Comment by akanksha-v** [comment]
@panchovm please review my pr #979 and suggest changes if any. Has the bug not resolved yet?
