### ISSUE TITLE
The popup element in reporting content doesn't follow the mockup

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#963]
## Describe the bug
The whole section has the following errors:
1. The section's title should use the `Heading 5B` style
2. The title + description section should have a 16px margin-bottom
3. Each radio button input should have an 8px distance.
4. The line-height of the final paragraph should follow the `caption` style.
5. The distance between final paragraph and the next button should be 8px.
6. The disabled state of the next button should follow [the Design Library](https://www.figma.com/file/l4Mt3dn3Ndtrvrb4aLcwXI/Design-Library?node-id=0%3A222&viewport=45%2C71%2C0.408292680978775) definition.

## Screenshots
<img width="404" alt="Screen Shot 2020-05-14 at 14 04 24" src="https://user-images.githubusercontent.com/895819/81969857-969e5200-95ec-11ea-8fe6-cab11dfb1c87.png">

**Comment by ariessa** [comment]
Hi, I fixed the bug and created pull request [#971](https://github.com/creativecommons/cccatalog-frontend/pull/971)
