### ISSUE TITLE
Hover styles of back and close actions

### ISSUE THREAD

**Issue by panchovm** [creativecommons/cccatalog-frontend#964]
## Describe the bug
In the pop-up of **report this content**, option "other", the `back` and `close` actions have incorrect styles during hover state.

## Expected behavior
In hover state, it should happen the following:
1. The back action should change the text color from `Gray` to `DarkGray`.
2. The fill color of the cross icon should change `Gray` to `DarkGray`.
See the [Mockup S3 in Figma](https://www.figma.com/file/KEXxItd8EloJGbXswuUDqq/Mockup---S3-(License-Language-Changes)?node-id=199%3A354&viewport=968%2C-5669%2C1.085633635520935).

## Screenshots
<img width="377" alt="Screen Shot 2020-05-14 at 15 34 57" src="https://user-images.githubusercontent.com/895819/81977733-7e343480-95f8-11ea-9a12-3aed5e7c34a5.png">
<img width="379" alt="Screen Shot 2020-05-14 at 15 34 53" src="https://user-images.githubusercontent.com/895819/81977737-7ffdf800-95f8-11ea-9ec2-aa24297a6bf1.png">

**Comment by tichnas** [comment]
I want to take this as my first issue. Can someone please help me with how to get started? How to find which file needs to be edited?

**Comment by akanksha-v** [comment]
Hi, I have fixed this issue #977

**Comment by iamananya** [comment]
I wanted to ask that if the issue is still open can I work on it??

**Comment by zackkrida** [comment]
Hi @iamananya sure, you may work on this. Thank you!
