### ISSUE TITLE
Updates to "Credit the Creator" Box

### ISSUE THREAD

**Issue by annatuma** [creativecommons/cccatalog-frontend#983]
As part of Design Sprint 3, we updated our attribution tool on single result pages. It is in the Reuse tab, called "Credit the Creator". [Example single result page](https://search.creativecommons.org/photos/e4e54b5c-504b-48f0-8deb-e97d7d8df85c).

There are a couple of minor changes necessary:

1) Change the tab called "Text" to "Rich Text".

2) Add "To view a copy of this license, visit https://license-url-goes-here" to the end of the string in "Plain Text". Note that it should not be a hyperlink, just a URL in plain text.

Example:
BestWork by BestAuthor is licensed under CC BY 4.0. To view a copy of this license, visit https://creativecommons.org/licenses/by/4.0

**Comment by tichnas** [comment]
Can I please work on this issue?

**Comment by akanksha-v** [comment]
@annatuma could you please confirm me one thing that in Plain Text we need to write, for e.g.-
"A cute Dog 2" by Chen Vision is licensed under CC BY-NC 2.0. To view a copy of this license, visit CC BY-NC 2.0"
That's it ?

**Comment by annatuma** [comment]
@akanksha-v no, it should be "visit https://......" with the license URL fully visible, not hyperlinked. This is for people to copy/paste into plain text, like print materials for instance.

It may be helpful to look at how it is done on the [License Chooser Beta](https://chooser-beta.creativecommons.org/) where it looks like this:

![Screen Shot 2020-05-19 at 1 56 03 PM](https://user-images.githubusercontent.com/3051816/82366844-7dc0e280-99d8-11ea-8ffc-dc009b4b35f9.png)

**Comment by annatuma** [comment]
@tichnas this issue is open for anyone to contribute.
