### ISSUE TITLE
Setup instructions in the readme don't work

### ISSUE THREAD

**Issue by localjo** [creativecommons/cccatalog-frontend#985]
## Describe the bug

Following the setup instructions in the readme doesn't work. Running the app locally fails with errors about missing modules (even though the modules have been installed), and running in Docker doesn't make the site available at http://localhost:8443/ 

## To Reproduce

1) Set up a fresh Node/npm install (I tested with version 12.16.1 and 12.4.0)
2) Clone the repo
3) Follow the steps in the readme

## Expected behavior

App should run

## Desktop (please complete the following information)
 - OS: macOS Catalina
 - Browser (ex. chrome, safari): N/A
 - Version (ex. 22): master branch, tagged as v1.0.0

## Additional context

I was able to get the app running with the following steps in a clean Node/npm install:

```bash
npm install --global webpack webpack-dev-server
git clone https://github.com/creativecommons/cccatalog-frontend.git
cd cccatalog-frontend.git
npm install
vim package.json # remove "type": "module" from package.json
webpack-dev-server
```

While I was able to get the app running, I'm not sure if these are the correct steps, and the readme needs to be updated, or if there are some bugs preventing the intended setup steps from working on macOS.

**Comment by zackkrida** [comment]
Hi @localjo, the project currently works with node v10 or lower _unless_ the `  "type": "module"` line is removed from `package.json`, as node v12+ supports native es6 modules and changes behavior when this line is present.

You shouldn't need to install any global modules to get it to work: just remove `  "type": "module"` and follow the instructions as-provided.

I'll make an issue for this; thanks for pointing it out!
