### ISSUE TITLE
Improve elements markup

### ISSUE THREAD

**Issue by brenoferreira** [creativecommons/cccatalog-frontend#999]
The [pa11y reports](https://drive.google.com/drive/folders/1WiUJimkGmDmXM4Hi36SfUrVYCtA5gQLj) has found some problems with the HTML markup, of which some of the most frequently seen include:

* landmarks: [this one](https://dequeuniversity.com/rules/axe/3.5/landmark-one-main?application=axeAPI) and [this one](https://dequeuniversity.com/rules/axe/3.5/region?application=axeAPI)
* links with icons have no text (the links on the footer for social media)
* Buttons with no name (might be fixable by arial labels)

**Comment by AyanChoudhary** [comment]
reopening as we might have to look at some other aspects as well after the screen reader audits.

**Comment by AyanChoudhary** [comment]
All the work involving this has been completed in #1068 and #1072
